// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fuelsequencer/bridge/events.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type EventSupplyDeltaReported struct {
	// supply_delta is the latest supply delta reported to Ethereum.
	SupplyDelta cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=supply_delta,json=supplyDelta,proto3,customtype=cosmossdk.io/math.Int" json:"supply_delta"`
	// nonce is the latest nonce reported to Ethereum.
	Nonce cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=nonce,proto3,customtype=cosmossdk.io/math.Int" json:"nonce"`
}

func (m *EventSupplyDeltaReported) Reset()         { *m = EventSupplyDeltaReported{} }
func (m *EventSupplyDeltaReported) String() string { return proto.CompactTextString(m) }
func (*EventSupplyDeltaReported) ProtoMessage()    {}
func (*EventSupplyDeltaReported) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fe1bf01b286796a, []int{0}
}
func (m *EventSupplyDeltaReported) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventSupplyDeltaReported) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventSupplyDeltaReported.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventSupplyDeltaReported) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventSupplyDeltaReported.Merge(m, src)
}
func (m *EventSupplyDeltaReported) XXX_Size() int {
	return m.Size()
}
func (m *EventSupplyDeltaReported) XXX_DiscardUnknown() {
	xxx_messageInfo_EventSupplyDeltaReported.DiscardUnknown(m)
}

var xxx_messageInfo_EventSupplyDeltaReported proto.InternalMessageInfo

type EventWithdrawToEthereumReported struct {
	// nonce uniquely identifies any message that we send to Ethereum.
	Nonce cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=nonce,proto3,customtype=cosmossdk.io/math.Int" json:"nonce"`
	// from is the user address that is withdrawing the tokens from the Sequencer.
	// can be in Hex or Bech32 format.
	From string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	// to is the user address on Ethereum that will be receiving the tokens.
	To string `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	// amount is the tokens being sent, which must be the expected bridge token.
	Amount types.Coin `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount"`
}

func (m *EventWithdrawToEthereumReported) Reset()         { *m = EventWithdrawToEthereumReported{} }
func (m *EventWithdrawToEthereumReported) String() string { return proto.CompactTextString(m) }
func (*EventWithdrawToEthereumReported) ProtoMessage()    {}
func (*EventWithdrawToEthereumReported) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fe1bf01b286796a, []int{1}
}
func (m *EventWithdrawToEthereumReported) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventWithdrawToEthereumReported) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventWithdrawToEthereumReported.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventWithdrawToEthereumReported) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventWithdrawToEthereumReported.Merge(m, src)
}
func (m *EventWithdrawToEthereumReported) XXX_Size() int {
	return m.Size()
}
func (m *EventWithdrawToEthereumReported) XXX_DiscardUnknown() {
	xxx_messageInfo_EventWithdrawToEthereumReported.DiscardUnknown(m)
}

var xxx_messageInfo_EventWithdrawToEthereumReported proto.InternalMessageInfo

func (m *EventWithdrawToEthereumReported) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *EventWithdrawToEthereumReported) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *EventWithdrawToEthereumReported) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

type EventDepositEventProcessed struct {
	// the sending Ethereum address in hex format
	Depositor string `protobuf:"bytes,1,opt,name=depositor,proto3" json:"depositor,omitempty"`
	// recipient Ethereum address in hex or bech32 format
	Recipient string `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	// amount is the tokens being sent, which must be denominated in the expected
	// bridge token.
	Amount types.Coin `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount"`
	// vesting duration encoded in string to prevent loss of precision. Sign is
	// also preserved. This can be zero if no duration is specified.
	Lockup string `protobuf:"bytes,4,opt,name=lockup,proto3" json:"lockup,omitempty"`
}

func (m *EventDepositEventProcessed) Reset()         { *m = EventDepositEventProcessed{} }
func (m *EventDepositEventProcessed) String() string { return proto.CompactTextString(m) }
func (*EventDepositEventProcessed) ProtoMessage()    {}
func (*EventDepositEventProcessed) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fe1bf01b286796a, []int{2}
}
func (m *EventDepositEventProcessed) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventDepositEventProcessed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventDepositEventProcessed.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventDepositEventProcessed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventDepositEventProcessed.Merge(m, src)
}
func (m *EventDepositEventProcessed) XXX_Size() int {
	return m.Size()
}
func (m *EventDepositEventProcessed) XXX_DiscardUnknown() {
	xxx_messageInfo_EventDepositEventProcessed.DiscardUnknown(m)
}

var xxx_messageInfo_EventDepositEventProcessed proto.InternalMessageInfo

func (m *EventDepositEventProcessed) GetDepositor() string {
	if m != nil {
		return m.Depositor
	}
	return ""
}

func (m *EventDepositEventProcessed) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *EventDepositEventProcessed) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

func (m *EventDepositEventProcessed) GetLockup() string {
	if m != nil {
		return m.Lockup
	}
	return ""
}

type EventDepositEventFailed struct {
	// event_details is the marshalled event that failed to be processed.
	EventDetails []byte `protobuf:"bytes,1,opt,name=event_details,json=eventDetails,proto3" json:"event_details,omitempty"`
}

func (m *EventDepositEventFailed) Reset()         { *m = EventDepositEventFailed{} }
func (m *EventDepositEventFailed) String() string { return proto.CompactTextString(m) }
func (*EventDepositEventFailed) ProtoMessage()    {}
func (*EventDepositEventFailed) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fe1bf01b286796a, []int{3}
}
func (m *EventDepositEventFailed) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventDepositEventFailed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventDepositEventFailed.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventDepositEventFailed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventDepositEventFailed.Merge(m, src)
}
func (m *EventDepositEventFailed) XXX_Size() int {
	return m.Size()
}
func (m *EventDepositEventFailed) XXX_DiscardUnknown() {
	xxx_messageInfo_EventDepositEventFailed.DiscardUnknown(m)
}

var xxx_messageInfo_EventDepositEventFailed proto.InternalMessageInfo

func (m *EventDepositEventFailed) GetEventDetails() []byte {
	if m != nil {
		return m.EventDetails
	}
	return nil
}

type EventEthereumBlockSynced struct {
	// block_number is the Ethereum block that was synced partially or fully.
	BlockNumber uint64 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	// full_sync is true if the Ethereum block has been fully synced.
	FullSync bool `protobuf:"varint,2,opt,name=full_sync,json=fullSync,proto3" json:"full_sync,omitempty"`
}

func (m *EventEthereumBlockSynced) Reset()         { *m = EventEthereumBlockSynced{} }
func (m *EventEthereumBlockSynced) String() string { return proto.CompactTextString(m) }
func (*EventEthereumBlockSynced) ProtoMessage()    {}
func (*EventEthereumBlockSynced) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fe1bf01b286796a, []int{4}
}
func (m *EventEthereumBlockSynced) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventEthereumBlockSynced) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventEthereumBlockSynced.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventEthereumBlockSynced) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventEthereumBlockSynced.Merge(m, src)
}
func (m *EventEthereumBlockSynced) XXX_Size() int {
	return m.Size()
}
func (m *EventEthereumBlockSynced) XXX_DiscardUnknown() {
	xxx_messageInfo_EventEthereumBlockSynced.DiscardUnknown(m)
}

var xxx_messageInfo_EventEthereumBlockSynced proto.InternalMessageInfo

func (m *EventEthereumBlockSynced) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *EventEthereumBlockSynced) GetFullSync() bool {
	if m != nil {
		return m.FullSync
	}
	return false
}

type EventSkippedEventTx struct {
	// reason_for_skip is the reason for skipping the event tx.
	ReasonForSkip string `protobuf:"bytes,1,opt,name=reason_for_skip,json=reasonForSkip,proto3" json:"reason_for_skip,omitempty"`
	// eth_block_number is the Ethereum height corresponding to the skipped event
	// tx.
	EthBlockNumber uint64 `protobuf:"varint,2,opt,name=eth_block_number,json=ethBlockNumber,proto3" json:"eth_block_number,omitempty"`
	// eth_log_index is the index of the Ethereum log corresponding to the skipped
	// event tx.
	EthLogIndex uint64 `protobuf:"varint,3,opt,name=eth_log_index,json=ethLogIndex,proto3" json:"eth_log_index,omitempty"`
	// eth_tx_index is the index of the Ethereum tx corresponding to the skipped
	// event tx.
	EthTxIndex uint64 `protobuf:"varint,4,opt,name=eth_tx_index,json=ethTxIndex,proto3" json:"eth_tx_index,omitempty"`
	// eth_tx_hash is the hash of the Ethereum tx corresponding to the skipped
	// event tx.
	EthTxHash string `protobuf:"bytes,5,opt,name=eth_tx_hash,json=ethTxHash,proto3" json:"eth_tx_hash,omitempty"`
}

func (m *EventSkippedEventTx) Reset()         { *m = EventSkippedEventTx{} }
func (m *EventSkippedEventTx) String() string { return proto.CompactTextString(m) }
func (*EventSkippedEventTx) ProtoMessage()    {}
func (*EventSkippedEventTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fe1bf01b286796a, []int{5}
}
func (m *EventSkippedEventTx) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventSkippedEventTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventSkippedEventTx.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventSkippedEventTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventSkippedEventTx.Merge(m, src)
}
func (m *EventSkippedEventTx) XXX_Size() int {
	return m.Size()
}
func (m *EventSkippedEventTx) XXX_DiscardUnknown() {
	xxx_messageInfo_EventSkippedEventTx.DiscardUnknown(m)
}

var xxx_messageInfo_EventSkippedEventTx proto.InternalMessageInfo

func (m *EventSkippedEventTx) GetReasonForSkip() string {
	if m != nil {
		return m.ReasonForSkip
	}
	return ""
}

func (m *EventSkippedEventTx) GetEthBlockNumber() uint64 {
	if m != nil {
		return m.EthBlockNumber
	}
	return 0
}

func (m *EventSkippedEventTx) GetEthLogIndex() uint64 {
	if m != nil {
		return m.EthLogIndex
	}
	return 0
}

func (m *EventSkippedEventTx) GetEthTxIndex() uint64 {
	if m != nil {
		return m.EthTxIndex
	}
	return 0
}

func (m *EventSkippedEventTx) GetEthTxHash() string {
	if m != nil {
		return m.EthTxHash
	}
	return ""
}

func init() {
	proto.RegisterType((*EventSupplyDeltaReported)(nil), "fuelsequencer.bridge.EventSupplyDeltaReported")
	proto.RegisterType((*EventWithdrawToEthereumReported)(nil), "fuelsequencer.bridge.EventWithdrawToEthereumReported")
	proto.RegisterType((*EventDepositEventProcessed)(nil), "fuelsequencer.bridge.EventDepositEventProcessed")
	proto.RegisterType((*EventDepositEventFailed)(nil), "fuelsequencer.bridge.EventDepositEventFailed")
	proto.RegisterType((*EventEthereumBlockSynced)(nil), "fuelsequencer.bridge.EventEthereumBlockSynced")
	proto.RegisterType((*EventSkippedEventTx)(nil), "fuelsequencer.bridge.EventSkippedEventTx")
}

func init() { proto.RegisterFile("fuelsequencer/bridge/events.proto", fileDescriptor_7fe1bf01b286796a) }

var fileDescriptor_7fe1bf01b286796a = []byte{
	// 653 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xcf, 0x4f, 0xd4, 0x40,
	0x14, 0xc7, 0xb7, 0xcb, 0x42, 0xd8, 0xd9, 0x05, 0xcd, 0x88, 0xba, 0xa0, 0x29, 0x50, 0x13, 0x43,
	0x62, 0x68, 0x83, 0x1e, 0xbc, 0x18, 0x13, 0x57, 0x20, 0x92, 0x18, 0x62, 0x0a, 0xd1, 0x84, 0x4b,
	0xd3, 0x1f, 0x6f, 0xdb, 0xc9, 0xb6, 0x33, 0x75, 0x66, 0x8a, 0xbb, 0xff, 0x85, 0xff, 0x86, 0x07,
	0x6f, 0xfe, 0x03, 0xde, 0xb8, 0x98, 0x10, 0x4f, 0xc6, 0x03, 0x31, 0xf0, 0x8f, 0x98, 0x99, 0xe9,
	0xb2, 0x10, 0x4f, 0x78, 0x9b, 0xf7, 0x7d, 0xdf, 0x79, 0xf3, 0x79, 0x7d, 0xd3, 0x41, 0xeb, 0x83,
	0x0a, 0x72, 0x01, 0x1f, 0x2b, 0xa0, 0x31, 0x70, 0x2f, 0xe2, 0x24, 0x49, 0xc1, 0x83, 0x63, 0xa0,
	0x52, 0xb8, 0x25, 0x67, 0x92, 0xe1, 0xa5, 0x6b, 0x16, 0xd7, 0x58, 0x56, 0x96, 0x52, 0x96, 0x32,
	0x6d, 0xf0, 0xd4, 0xca, 0x78, 0x57, 0x96, 0x63, 0x26, 0x0a, 0x26, 0x02, 0x93, 0x30, 0x41, 0x9d,
	0xb2, 0x4d, 0xe4, 0x45, 0xa1, 0x00, 0xef, 0x78, 0x2b, 0x02, 0x19, 0x6e, 0x79, 0x31, 0x23, 0x74,
	0xb2, 0x35, 0x65, 0x2c, 0xcd, 0xc1, 0xd3, 0x51, 0x54, 0x0d, 0xbc, 0x90, 0x8e, 0x4d, 0xca, 0xf9,
	0x6a, 0xa1, 0xde, 0x8e, 0x42, 0x3a, 0xa8, 0xca, 0x32, 0x1f, 0x6f, 0x43, 0x2e, 0x43, 0x1f, 0x4a,
	0xc6, 0x25, 0x24, 0x78, 0x1f, 0x75, 0x85, 0x96, 0x83, 0x44, 0xe9, 0x3d, 0x6b, 0xcd, 0xda, 0x68,
	0xf7, 0x9f, 0x9c, 0x9c, 0xad, 0x36, 0x7e, 0x9f, 0xad, 0xde, 0x35, 0xa7, 0x8a, 0x64, 0xe8, 0x12,
	0xe6, 0x15, 0xa1, 0xcc, 0xdc, 0x3d, 0x2a, 0x7f, 0x7e, 0xdb, 0x44, 0x35, 0xdc, 0x1e, 0x95, 0x7e,
	0x47, 0x4c, 0xeb, 0xe2, 0x57, 0x68, 0x96, 0x32, 0x1a, 0x43, 0xaf, 0x79, 0xf3, 0x42, 0x66, 0xa7,
	0xf3, 0xdd, 0x42, 0xab, 0x9a, 0xf7, 0x03, 0x91, 0x59, 0xc2, 0xc3, 0x4f, 0x87, 0x6c, 0x47, 0x66,
	0xc0, 0xa1, 0x2a, 0x2e, 0xb1, 0x2f, 0x8f, 0xb1, 0xfe, 0xf7, 0x18, 0x8c, 0x51, 0x6b, 0xc0, 0x59,
	0x61, 0x40, 0x7d, 0xbd, 0xc6, 0x8b, 0xa8, 0x29, 0x59, 0x6f, 0x46, 0x2b, 0x4d, 0xc9, 0xf0, 0x73,
	0x34, 0x17, 0x16, 0xac, 0xa2, 0xb2, 0xd7, 0x5a, 0xb3, 0x36, 0x3a, 0x4f, 0x97, 0xdd, 0xba, 0x8e,
	0x1a, 0x83, 0x5b, 0x8f, 0xc1, 0x7d, 0xcd, 0x08, 0xed, 0xb7, 0x14, 0x82, 0x5f, 0xdb, 0x9d, 0x2f,
	0x16, 0x5a, 0xd1, 0x3d, 0x6c, 0x43, 0xc9, 0x04, 0x91, 0x7a, 0xfd, 0x8e, 0xb3, 0x18, 0x84, 0x80,
	0x04, 0x3f, 0x44, 0xed, 0xc4, 0x24, 0x18, 0x37, 0x2d, 0xf8, 0x53, 0x41, 0x65, 0x39, 0xc4, 0xa4,
	0x24, 0x40, 0x65, 0x8d, 0x37, 0x15, 0xae, 0x30, 0xcd, 0xdc, 0x88, 0x09, 0xdf, 0x43, 0x73, 0x39,
	0x8b, 0x87, 0x55, 0xa9, 0x9b, 0x69, 0xfb, 0x75, 0xe4, 0xbc, 0x44, 0xf7, 0xff, 0x41, 0xdd, 0x0d,
	0x49, 0x0e, 0x09, 0x7e, 0x84, 0x16, 0xf4, 0x65, 0x0e, 0x12, 0x90, 0x21, 0xc9, 0x85, 0x66, 0xed,
	0xfa, 0x5d, 0x30, 0x7e, 0xad, 0x39, 0x47, 0xf5, 0xf5, 0x9a, 0x0c, 0xa9, 0xaf, 0xea, 0x1e, 0x8c,
	0x69, 0x0c, 0x09, 0x5e, 0x47, 0xdd, 0x48, 0x85, 0x01, 0xad, 0x8a, 0x08, 0x4c, 0xaf, 0x2d, 0xbf,
	0xa3, 0xb5, 0x7d, 0x2d, 0xe1, 0x07, 0xa8, 0x3d, 0xa8, 0xf2, 0x3c, 0x10, 0x63, 0x1a, 0xeb, 0x6e,
	0xe7, 0xfd, 0x79, 0x25, 0xa8, 0x0a, 0xce, 0x0f, 0x0b, 0xdd, 0x31, 0x77, 0x77, 0x48, 0xca, 0x12,
	0x12, 0xbd, 0x3e, 0x1c, 0xe1, 0xc7, 0xe8, 0x16, 0x87, 0x50, 0x30, 0x1a, 0x0c, 0x18, 0x0f, 0xc4,
	0x90, 0x94, 0xf5, 0x67, 0x5c, 0x30, 0xf2, 0x2e, 0xe3, 0x6a, 0x07, 0xde, 0x40, 0xb7, 0x41, 0x66,
	0xc1, 0x35, 0x86, 0xa6, 0x66, 0x58, 0x04, 0x99, 0xf5, 0xaf, 0x60, 0x38, 0x68, 0x41, 0x39, 0x73,
	0x96, 0x06, 0x84, 0x26, 0x30, 0xd2, 0x5f, 0xb7, 0xe5, 0x77, 0x40, 0x66, 0x6f, 0x59, 0xba, 0xa7,
	0x24, 0xbc, 0x86, 0xba, 0xca, 0x23, 0x47, 0xb5, 0xa5, 0xa5, 0x2d, 0x08, 0x64, 0x76, 0x38, 0x32,
	0x0e, 0x1b, 0x75, 0x6a, 0x47, 0x16, 0x8a, 0xac, 0x37, 0x6b, 0x86, 0xa7, 0x0d, 0x6f, 0x42, 0x91,
	0xf5, 0xdf, 0x9f, 0x9c, 0xdb, 0xd6, 0xe9, 0xb9, 0x6d, 0xfd, 0x39, 0xb7, 0xad, 0xcf, 0x17, 0x76,
	0xe3, 0xf4, 0xc2, 0x6e, 0xfc, 0xba, 0xb0, 0x1b, 0x47, 0x2f, 0x52, 0x22, 0xb3, 0x2a, 0x72, 0x63,
	0x56, 0x78, 0xea, 0xc9, 0xd8, 0x24, 0x74, 0xc0, 0x43, 0x21, 0x79, 0x15, 0xcb, 0x8a, 0x83, 0xd1,
	0xa6, 0x4f, 0xcd, 0x68, 0xf2, 0xd8, 0xc8, 0x71, 0x09, 0x22, 0x9a, 0xd3, 0xbf, 0xfa, 0xb3, 0xbf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x1c, 0xcb, 0x21, 0xe3, 0x91, 0x04, 0x00, 0x00,
}

func (m *EventSupplyDeltaReported) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventSupplyDeltaReported) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventSupplyDeltaReported) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Nonce.Size()
		i -= size
		if _, err := m.Nonce.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.SupplyDelta.Size()
		i -= size
		if _, err := m.SupplyDelta.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *EventWithdrawToEthereumReported) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventWithdrawToEthereumReported) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventWithdrawToEthereumReported) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.To) > 0 {
		i -= len(m.To)
		copy(dAtA[i:], m.To)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.To)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.From) > 0 {
		i -= len(m.From)
		copy(dAtA[i:], m.From)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.From)))
		i--
		dAtA[i] = 0x12
	}
	{
		size := m.Nonce.Size()
		i -= size
		if _, err := m.Nonce.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *EventDepositEventProcessed) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventDepositEventProcessed) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventDepositEventProcessed) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Lockup) > 0 {
		i -= len(m.Lockup)
		copy(dAtA[i:], m.Lockup)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Lockup)))
		i--
		dAtA[i] = 0x22
	}
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Depositor) > 0 {
		i -= len(m.Depositor)
		copy(dAtA[i:], m.Depositor)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Depositor)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventDepositEventFailed) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventDepositEventFailed) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventDepositEventFailed) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EventDetails) > 0 {
		i -= len(m.EventDetails)
		copy(dAtA[i:], m.EventDetails)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.EventDetails)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventEthereumBlockSynced) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventEthereumBlockSynced) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventEthereumBlockSynced) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FullSync {
		i--
		if m.FullSync {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.BlockNumber != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.BlockNumber))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EventSkippedEventTx) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventSkippedEventTx) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventSkippedEventTx) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EthTxHash) > 0 {
		i -= len(m.EthTxHash)
		copy(dAtA[i:], m.EthTxHash)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.EthTxHash)))
		i--
		dAtA[i] = 0x2a
	}
	if m.EthTxIndex != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.EthTxIndex))
		i--
		dAtA[i] = 0x20
	}
	if m.EthLogIndex != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.EthLogIndex))
		i--
		dAtA[i] = 0x18
	}
	if m.EthBlockNumber != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.EthBlockNumber))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ReasonForSkip) > 0 {
		i -= len(m.ReasonForSkip)
		copy(dAtA[i:], m.ReasonForSkip)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.ReasonForSkip)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvents(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvents(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventSupplyDeltaReported) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.SupplyDelta.Size()
	n += 1 + l + sovEvents(uint64(l))
	l = m.Nonce.Size()
	n += 1 + l + sovEvents(uint64(l))
	return n
}

func (m *EventWithdrawToEthereumReported) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Nonce.Size()
	n += 1 + l + sovEvents(uint64(l))
	l = len(m.From)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.To)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovEvents(uint64(l))
	return n
}

func (m *EventDepositEventProcessed) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Depositor)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovEvents(uint64(l))
	l = len(m.Lockup)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventDepositEventFailed) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.EventDetails)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventEthereumBlockSynced) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BlockNumber != 0 {
		n += 1 + sovEvents(uint64(m.BlockNumber))
	}
	if m.FullSync {
		n += 2
	}
	return n
}

func (m *EventSkippedEventTx) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ReasonForSkip)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.EthBlockNumber != 0 {
		n += 1 + sovEvents(uint64(m.EthBlockNumber))
	}
	if m.EthLogIndex != 0 {
		n += 1 + sovEvents(uint64(m.EthLogIndex))
	}
	if m.EthTxIndex != 0 {
		n += 1 + sovEvents(uint64(m.EthTxIndex))
	}
	l = len(m.EthTxHash)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func sovEvents(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvents(x uint64) (n int) {
	return sovEvents(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventSupplyDeltaReported) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventSupplyDeltaReported: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventSupplyDeltaReported: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SupplyDelta", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SupplyDelta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Nonce.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventWithdrawToEthereumReported) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventWithdrawToEthereumReported: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventWithdrawToEthereumReported: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Nonce.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field From", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.From = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field To", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.To = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventDepositEventProcessed) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventDepositEventProcessed: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventDepositEventProcessed: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Depositor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Depositor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lockup", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Lockup = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventDepositEventFailed) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventDepositEventFailed: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventDepositEventFailed: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EventDetails", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EventDetails = append(m.EventDetails[:0], dAtA[iNdEx:postIndex]...)
			if m.EventDetails == nil {
				m.EventDetails = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventEthereumBlockSynced) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventEthereumBlockSynced: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventEthereumBlockSynced: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockNumber", wireType)
			}
			m.BlockNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockNumber |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FullSync", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.FullSync = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventSkippedEventTx) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventSkippedEventTx: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventSkippedEventTx: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReasonForSkip", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReasonForSkip = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EthBlockNumber", wireType)
			}
			m.EthBlockNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EthBlockNumber |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EthLogIndex", wireType)
			}
			m.EthLogIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EthLogIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EthTxIndex", wireType)
			}
			m.EthTxIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EthTxIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EthTxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EthTxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvents(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvents
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvents
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvents
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvents        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvents          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvents = fmt.Errorf("proto: unexpected end of group")
)
