// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fuelsequencer/bridge/events.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type EventSupplyDeltaReported struct {
	// supply_delta is the latest supply delta reported to Ethereum.
	SupplyDelta cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=supply_delta,json=supplyDelta,proto3,customtype=cosmossdk.io/math.Int" json:"supply_delta"`
	// nonce is the latest nonce reported to Ethereum.
	Nonce cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=nonce,proto3,customtype=cosmossdk.io/math.Int" json:"nonce"`
}

func (m *EventSupplyDeltaReported) Reset()         { *m = EventSupplyDeltaReported{} }
func (m *EventSupplyDeltaReported) String() string { return proto.CompactTextString(m) }
func (*EventSupplyDeltaReported) ProtoMessage()    {}
func (*EventSupplyDeltaReported) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fe1bf01b286796a, []int{0}
}
func (m *EventSupplyDeltaReported) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventSupplyDeltaReported) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventSupplyDeltaReported.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventSupplyDeltaReported) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventSupplyDeltaReported.Merge(m, src)
}
func (m *EventSupplyDeltaReported) XXX_Size() int {
	return m.Size()
}
func (m *EventSupplyDeltaReported) XXX_DiscardUnknown() {
	xxx_messageInfo_EventSupplyDeltaReported.DiscardUnknown(m)
}

var xxx_messageInfo_EventSupplyDeltaReported proto.InternalMessageInfo

type EventWithdrawToEthereumReported struct {
	// nonce uniquely identifies any message that we send to Ethereum.
	Nonce cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=nonce,proto3,customtype=cosmossdk.io/math.Int" json:"nonce"`
	// from is the user address on FuelSequencer that is sending the tokens.
	From string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	// to is the user address on Ethereum that will be receiving the tokens.
	To string `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	// amount is the tokens being sent, which must be the expacted bridge token.
	Amount types.Coin `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount"`
}

func (m *EventWithdrawToEthereumReported) Reset()         { *m = EventWithdrawToEthereumReported{} }
func (m *EventWithdrawToEthereumReported) String() string { return proto.CompactTextString(m) }
func (*EventWithdrawToEthereumReported) ProtoMessage()    {}
func (*EventWithdrawToEthereumReported) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fe1bf01b286796a, []int{1}
}
func (m *EventWithdrawToEthereumReported) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventWithdrawToEthereumReported) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventWithdrawToEthereumReported.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventWithdrawToEthereumReported) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventWithdrawToEthereumReported.Merge(m, src)
}
func (m *EventWithdrawToEthereumReported) XXX_Size() int {
	return m.Size()
}
func (m *EventWithdrawToEthereumReported) XXX_DiscardUnknown() {
	xxx_messageInfo_EventWithdrawToEthereumReported.DiscardUnknown(m)
}

var xxx_messageInfo_EventWithdrawToEthereumReported proto.InternalMessageInfo

func (m *EventWithdrawToEthereumReported) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *EventWithdrawToEthereumReported) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *EventWithdrawToEthereumReported) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

type EventSendToSequencerEventProcessed struct {
	// from is the user address on FuelSequencer that is sending the tokens.
	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// to is the user address on Ethereum that will be receiving the tokens.
	To string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	// amount is the tokens being sent, which must be the expected bridge token.
	Amount types.Coin `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount"`
	// vesting duration encoded in string to prevent loss of precision. Sign is
	// also preserved
	Duration string `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
}

func (m *EventSendToSequencerEventProcessed) Reset()         { *m = EventSendToSequencerEventProcessed{} }
func (m *EventSendToSequencerEventProcessed) String() string { return proto.CompactTextString(m) }
func (*EventSendToSequencerEventProcessed) ProtoMessage()    {}
func (*EventSendToSequencerEventProcessed) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fe1bf01b286796a, []int{2}
}
func (m *EventSendToSequencerEventProcessed) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventSendToSequencerEventProcessed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventSendToSequencerEventProcessed.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventSendToSequencerEventProcessed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventSendToSequencerEventProcessed.Merge(m, src)
}
func (m *EventSendToSequencerEventProcessed) XXX_Size() int {
	return m.Size()
}
func (m *EventSendToSequencerEventProcessed) XXX_DiscardUnknown() {
	xxx_messageInfo_EventSendToSequencerEventProcessed.DiscardUnknown(m)
}

var xxx_messageInfo_EventSendToSequencerEventProcessed proto.InternalMessageInfo

func (m *EventSendToSequencerEventProcessed) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *EventSendToSequencerEventProcessed) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *EventSendToSequencerEventProcessed) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

func (m *EventSendToSequencerEventProcessed) GetDuration() string {
	if m != nil {
		return m.Duration
	}
	return ""
}

func init() {
	proto.RegisterType((*EventSupplyDeltaReported)(nil), "fuelsequencer.bridge.EventSupplyDeltaReported")
	proto.RegisterType((*EventWithdrawToEthereumReported)(nil), "fuelsequencer.bridge.EventWithdrawToEthereumReported")
	proto.RegisterType((*EventSendToSequencerEventProcessed)(nil), "fuelsequencer.bridge.EventSendToSequencerEventProcessed")
}

func init() { proto.RegisterFile("fuelsequencer/bridge/events.proto", fileDescriptor_7fe1bf01b286796a) }

var fileDescriptor_7fe1bf01b286796a = []byte{
	// 445 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xb1, 0x6e, 0xd4, 0x40,
	0x10, 0x86, 0x6f, 0x2f, 0x47, 0x44, 0x36, 0x88, 0xc2, 0x0a, 0x92, 0x73, 0x85, 0x2f, 0x5c, 0x15,
	0x09, 0xc5, 0xab, 0x40, 0x41, 0x43, 0xc3, 0x41, 0x8a, 0x34, 0x08, 0x39, 0x11, 0x48, 0x34, 0xd1,
	0xda, 0x9e, 0xf3, 0x59, 0x9c, 0x77, 0xcc, 0xee, 0x6c, 0xe0, 0xde, 0x82, 0x17, 0xe0, 0x11, 0xe8,
	0x78, 0x01, 0xba, 0x94, 0x11, 0x15, 0xa2, 0x88, 0xd0, 0xdd, 0x8b, 0x20, 0xef, 0xfa, 0x1c, 0x21,
	0x68, 0x92, 0x6e, 0xe7, 0x9f, 0x7f, 0x66, 0x3e, 0xed, 0x0c, 0x7f, 0x38, 0xb5, 0x30, 0x37, 0xf0,
	0xc1, 0x82, 0xca, 0x40, 0x8b, 0x54, 0x97, 0x79, 0x01, 0x02, 0xce, 0x41, 0x91, 0x89, 0x6b, 0x8d,
	0x84, 0xc1, 0xce, 0x5f, 0x96, 0xd8, 0x5b, 0x86, 0x3b, 0x05, 0x16, 0xe8, 0x0c, 0xa2, 0x79, 0x79,
	0xef, 0x70, 0x37, 0x43, 0x53, 0xa1, 0x39, 0xf3, 0x09, 0x1f, 0xb4, 0xa9, 0xc8, 0x47, 0x22, 0x95,
	0x06, 0xc4, 0xf9, 0x61, 0x0a, 0x24, 0x0f, 0x45, 0x86, 0xa5, 0x5a, 0x97, 0x16, 0x88, 0xc5, 0x1c,
	0x84, 0x8b, 0x52, 0x3b, 0x15, 0x52, 0x2d, 0x7c, 0x6a, 0xfc, 0x95, 0xf1, 0xf0, 0xa8, 0x41, 0x3a,
	0xb1, 0x75, 0x3d, 0x5f, 0xbc, 0x84, 0x39, 0xc9, 0x04, 0x6a, 0xd4, 0x04, 0x79, 0xf0, 0x8a, 0xdf,
	0x33, 0x4e, 0x3e, 0xcb, 0x1b, 0x3d, 0x64, 0x7b, 0x6c, 0x7f, 0x6b, 0xf2, 0xe8, 0xe2, 0x6a, 0xd4,
	0xfb, 0x75, 0x35, 0x7a, 0xe0, 0xa7, 0x9a, 0xfc, 0x7d, 0x5c, 0xa2, 0xa8, 0x24, 0xcd, 0xe2, 0x63,
	0x45, 0x3f, 0xbe, 0x1d, 0xf0, 0x16, 0xee, 0x58, 0x51, 0xb2, 0x6d, 0xae, 0xfb, 0x06, 0xcf, 0xf9,
	0x1d, 0x85, 0x2a, 0x83, 0xb0, 0x7f, 0xf3, 0x46, 0xbe, 0x72, 0xfc, 0x9d, 0xf1, 0x91, 0xe3, 0x7d,
	0x5b, 0xd2, 0x2c, 0xd7, 0xf2, 0xe3, 0x29, 0x1e, 0xd1, 0x0c, 0x34, 0xd8, 0xaa, 0xc3, 0xee, 0xc6,
	0xb0, 0xdb, 0x8e, 0x09, 0x02, 0x3e, 0x98, 0x6a, 0xac, 0x3c, 0x68, 0xe2, 0xde, 0xc1, 0x7d, 0xde,
	0x27, 0x0c, 0x37, 0x9c, 0xd2, 0x27, 0x0c, 0x9e, 0xf2, 0x4d, 0x59, 0xa1, 0x55, 0x14, 0x0e, 0xf6,
	0xd8, 0xfe, 0xf6, 0xe3, 0xdd, 0xb8, 0xed, 0xd3, 0xac, 0x21, 0x6e, 0xd7, 0x10, 0xbf, 0xc0, 0x52,
	0x4d, 0x06, 0x0d, 0x42, 0xd2, 0xda, 0xc7, 0x5f, 0x18, 0x1f, 0xfb, 0x3f, 0x07, 0x95, 0x9f, 0xe2,
	0xc9, 0x7a, 0xff, 0x4e, 0x7b, 0xad, 0x31, 0x03, 0x63, 0x20, 0xef, 0x18, 0xd8, 0x3f, 0x0c, 0xfd,
	0xff, 0x30, 0x6c, 0xdc, 0x88, 0x21, 0x18, 0xf2, 0xbb, 0xb9, 0xd5, 0x92, 0x4a, 0x54, 0x0e, 0x7f,
	0x2b, 0xe9, 0xe2, 0xc9, 0x9b, 0x8b, 0x65, 0xc4, 0x2e, 0x97, 0x11, 0xfb, 0xbd, 0x8c, 0xd8, 0xe7,
	0x55, 0xd4, 0xbb, 0x5c, 0x45, 0xbd, 0x9f, 0xab, 0xa8, 0xf7, 0xee, 0x59, 0x51, 0xd2, 0xcc, 0xa6,
	0x71, 0x86, 0x95, 0x68, 0x4e, 0xf7, 0xa0, 0x54, 0x53, 0x2d, 0x0d, 0x69, 0x9b, 0x91, 0xd5, 0xe0,
	0xb5, 0xeb, 0x93, 0xff, 0xb4, 0x3e, 0x7a, 0x5a, 0xd4, 0x60, 0xd2, 0x4d, 0x77, 0x72, 0x4f, 0xfe,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x92, 0xb6, 0x77, 0xbc, 0x19, 0x03, 0x00, 0x00,
}

func (m *EventSupplyDeltaReported) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventSupplyDeltaReported) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventSupplyDeltaReported) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Nonce.Size()
		i -= size
		if _, err := m.Nonce.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.SupplyDelta.Size()
		i -= size
		if _, err := m.SupplyDelta.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *EventWithdrawToEthereumReported) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventWithdrawToEthereumReported) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventWithdrawToEthereumReported) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.To) > 0 {
		i -= len(m.To)
		copy(dAtA[i:], m.To)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.To)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.From) > 0 {
		i -= len(m.From)
		copy(dAtA[i:], m.From)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.From)))
		i--
		dAtA[i] = 0x12
	}
	{
		size := m.Nonce.Size()
		i -= size
		if _, err := m.Nonce.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *EventSendToSequencerEventProcessed) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventSendToSequencerEventProcessed) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventSendToSequencerEventProcessed) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Duration) > 0 {
		i -= len(m.Duration)
		copy(dAtA[i:], m.Duration)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Duration)))
		i--
		dAtA[i] = 0x22
	}
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.To) > 0 {
		i -= len(m.To)
		copy(dAtA[i:], m.To)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.To)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.From) > 0 {
		i -= len(m.From)
		copy(dAtA[i:], m.From)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.From)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvents(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvents(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventSupplyDeltaReported) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.SupplyDelta.Size()
	n += 1 + l + sovEvents(uint64(l))
	l = m.Nonce.Size()
	n += 1 + l + sovEvents(uint64(l))
	return n
}

func (m *EventWithdrawToEthereumReported) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Nonce.Size()
	n += 1 + l + sovEvents(uint64(l))
	l = len(m.From)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.To)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovEvents(uint64(l))
	return n
}

func (m *EventSendToSequencerEventProcessed) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.From)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.To)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovEvents(uint64(l))
	l = len(m.Duration)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func sovEvents(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvents(x uint64) (n int) {
	return sovEvents(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventSupplyDeltaReported) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventSupplyDeltaReported: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventSupplyDeltaReported: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SupplyDelta", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SupplyDelta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Nonce.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventWithdrawToEthereumReported) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventWithdrawToEthereumReported: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventWithdrawToEthereumReported: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Nonce.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field From", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.From = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field To", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.To = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventSendToSequencerEventProcessed) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventSendToSequencerEventProcessed: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventSendToSequencerEventProcessed: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field From", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.From = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field To", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.To = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Duration", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Duration = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvents(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvents
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvents
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvents
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvents        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvents          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvents = fmt.Errorf("proto: unexpected end of group")
)
