// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fuelsequencer/bridge/genesis.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the bridge module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// supply_delta_info is the starting point for changes in the bridge token
	// supply that we should report to Ethereum.
	SupplyDeltaInfo *SupplyDeltaInfo `protobuf:"bytes,2,opt,name=supply_delta_info,json=supplyDeltaInfo,proto3" json:"supply_delta_info,omitempty"`
	// last_ethereum_nonce is the last nonce used in messages towards Ethereum.
	// In other words, the next nonce to be used is this value +1.
	LastEthereumNonce cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=last_ethereum_nonce,json=lastEthereumNonce,proto3,customtype=cosmossdk.io/math.Int" json:"last_ethereum_nonce"`
	// last_ethereum_block_synced is the last Ethereum block synced.
	// In other words, the next block to be synced is this value +1.
	LastEthereumBlockSynced cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=last_ethereum_block_synced,json=lastEthereumBlockSynced,proto3,customtype=cosmossdk.io/math.Int" json:"last_ethereum_block_synced"`
	// eth_events_tx defines the last eth_events_tx.
	EthEventsTx *EthEventsTx `protobuf:"bytes,5,opt,name=eth_events_tx,json=ethEventsTx,proto3" json:"eth_events_tx,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6f7e37f0f3ae9a8, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetSupplyDeltaInfo() *SupplyDeltaInfo {
	if m != nil {
		return m.SupplyDeltaInfo
	}
	return nil
}

func (m *GenesisState) GetEthEventsTx() *EthEventsTx {
	if m != nil {
		return m.EthEventsTx
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "fuelsequencer.bridge.GenesisState")
}

func init() {
	proto.RegisterFile("fuelsequencer/bridge/genesis.proto", fileDescriptor_e6f7e37f0f3ae9a8)
}

var fileDescriptor_e6f7e37f0f3ae9a8 = []byte{
	// 445 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x4f, 0x8b, 0xd3, 0x40,
	0x18, 0xc6, 0x1b, 0x57, 0x17, 0x9c, 0x5d, 0x91, 0xc6, 0x15, 0x63, 0x91, 0xec, 0x1f, 0x10, 0x16,
	0x71, 0x13, 0xff, 0x5c, 0x05, 0xa1, 0x58, 0xa4, 0x17, 0xd1, 0x56, 0x3c, 0x78, 0x19, 0xa7, 0xd3,
	0x37, 0xc9, 0xb0, 0xc9, 0x4c, 0x9c, 0x79, 0x23, 0xed, 0xb7, 0xf0, 0x63, 0x78, 0xf4, 0xe0, 0xc9,
	0x4f, 0xb0, 0xc7, 0xc5, 0x93, 0x78, 0x58, 0xa4, 0x3d, 0xf8, 0x35, 0x24, 0x33, 0x29, 0xdb, 0x62,
	0x4e, 0x5e, 0xc2, 0xcc, 0x3b, 0xbf, 0x79, 0x9e, 0x77, 0x9e, 0xbc, 0xe4, 0x28, 0xa9, 0x20, 0x37,
	0xf0, 0xb1, 0x02, 0xc9, 0x41, 0xc7, 0x13, 0x2d, 0xa6, 0x29, 0xc4, 0x29, 0x48, 0x30, 0xc2, 0x44,
	0xa5, 0x56, 0xa8, 0xfc, 0xbd, 0x0d, 0x26, 0x72, 0x4c, 0xaf, 0xcb, 0x0a, 0x21, 0x55, 0x6c, 0xbf,
	0x0e, 0xec, 0xed, 0xa5, 0x2a, 0x55, 0x76, 0x19, 0xd7, 0xab, 0xa6, 0x7a, 0x97, 0x2b, 0x53, 0x28,
	0x43, 0xdd, 0x81, 0xdb, 0x34, 0x47, 0x87, 0xad, 0xee, 0x25, 0xd3, 0xac, 0x58, 0x21, 0x0f, 0x5b,
	0x11, 0x53, 0x95, 0x65, 0x3e, 0xa7, 0x53, 0xc8, 0x91, 0x51, 0x21, 0x93, 0x95, 0xd7, 0xe3, 0x56,
	0x1a, 0x30, 0xa3, 0xf0, 0x09, 0x24, 0x1a, 0x8a, 0x9a, 0x49, 0xc3, 0x38, 0x0a, 0x25, 0xdd, 0x95,
	0xa3, 0xef, 0x5b, 0x64, 0xf7, 0xa5, 0x7b, 0xef, 0x18, 0x19, 0x82, 0xff, 0x9c, 0x6c, 0xbb, 0x0e,
	0x02, 0xef, 0xc0, 0x3b, 0xde, 0x79, 0x72, 0x2f, 0x6a, 0x7b, 0x7f, 0xf4, 0xda, 0x32, 0xfd, 0xeb,
	0x67, 0x17, 0xfb, 0x9d, 0x2f, 0x7f, 0xbe, 0x3e, 0xf0, 0x46, 0xcd, 0x35, 0xff, 0x0d, 0xe9, 0xfe,
	0xd3, 0x5f, 0x70, 0xc5, 0x6a, 0xdd, 0x6f, 0xd7, 0x1a, 0x5b, 0xfc, 0x45, 0x4d, 0x0f, 0x65, 0xa2,
	0x46, 0x37, 0xcd, 0x66, 0xc1, 0xff, 0x40, 0x6e, 0xe5, 0xcc, 0x20, 0x05, 0xcc, 0x40, 0x43, 0x55,
	0x50, 0xa9, 0x24, 0x87, 0x60, 0xeb, 0xc0, 0x3b, 0xde, 0xed, 0x3f, 0xaa, 0x5b, 0xf8, 0x75, 0xb1,
	0x7f, 0xdb, 0x65, 0x6b, 0xa6, 0xa7, 0x91, 0x50, 0x71, 0xc1, 0x30, 0x8b, 0x86, 0x12, 0x7f, 0x7c,
	0x3b, 0x21, 0x4d, 0xe8, 0x43, 0x89, 0xae, 0xd3, 0x6e, 0x2d, 0x36, 0x68, 0xb4, 0x5e, 0xd5, 0x52,
	0x7e, 0x41, 0x7a, 0x9b, 0x0e, 0x93, 0x5c, 0xf1, 0x53, 0x6a, 0xe6, 0x92, 0xc3, 0x34, 0xb8, 0xfa,
	0x9f, 0x46, 0x77, 0xd6, 0x8d, 0xfa, 0xb5, 0xe2, 0xd8, 0x0a, 0xfa, 0x03, 0x72, 0x63, 0xfd, 0xaf,
	0xcc, 0x82, 0x6b, 0x36, 0x9f, 0xc3, 0xf6, 0x7c, 0x06, 0x98, 0x0d, 0x2c, 0xf9, 0x76, 0x36, 0xda,
	0x81, 0xcb, 0x4d, 0xff, 0xdd, 0xd9, 0x22, 0xf4, 0xce, 0x17, 0xa1, 0xf7, 0x7b, 0x11, 0x7a, 0x9f,
	0x97, 0x61, 0xe7, 0x7c, 0x19, 0x76, 0x7e, 0x2e, 0xc3, 0xce, 0xfb, 0x67, 0xa9, 0xc0, 0xac, 0x9a,
	0x44, 0x5c, 0x15, 0x71, 0xad, 0x79, 0x22, 0x64, 0xa2, 0x99, 0x41, 0x5d, 0x71, 0xac, 0x34, 0xb8,
	0xda, 0xe5, 0xa4, 0xcc, 0x56, 0xb3, 0x82, 0xf3, 0x12, 0xcc, 0x64, 0xdb, 0xce, 0xc6, 0xd3, 0xbf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xbd, 0x9c, 0xd2, 0x16, 0x1f, 0x03, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EthEventsTx != nil {
		{
			size, err := m.EthEventsTx.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	{
		size := m.LastEthereumBlockSynced.Size()
		i -= size
		if _, err := m.LastEthereumBlockSynced.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.LastEthereumNonce.Size()
		i -= size
		if _, err := m.LastEthereumNonce.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.SupplyDeltaInfo != nil {
		{
			size, err := m.SupplyDeltaInfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.SupplyDeltaInfo != nil {
		l = m.SupplyDeltaInfo.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.LastEthereumNonce.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.LastEthereumBlockSynced.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.EthEventsTx != nil {
		l = m.EthEventsTx.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SupplyDeltaInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SupplyDeltaInfo == nil {
				m.SupplyDeltaInfo = &SupplyDeltaInfo{}
			}
			if err := m.SupplyDeltaInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastEthereumNonce", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LastEthereumNonce.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastEthereumBlockSynced", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LastEthereumBlockSynced.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EthEventsTx", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.EthEventsTx == nil {
				m.EthEventsTx = &EthEventsTx{}
			}
			if err := m.EthEventsTx.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
