// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fuelsequencer/bridge/index.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Index struct {
	// TODO
	NumInjectedTxsTotal uint64 `protobuf:"varint,1,opt,name=num_injected_txs_total,json=numInjectedTxsTotal,proto3" json:"num_injected_txs_total,omitempty"`
	// TODO
	NumInjectedTxsAnte uint64 `protobuf:"varint,2,opt,name=num_injected_txs_ante,json=numInjectedTxsAnte,proto3" json:"num_injected_txs_ante,omitempty"`
	// TODO
	NumSpecialTxsTotal uint64 `protobuf:"varint,3,opt,name=num_special_txs_total,json=numSpecialTxsTotal,proto3" json:"num_special_txs_total,omitempty"`
	// TODO
	NumSpecialTxsExec uint64 `protobuf:"varint,4,opt,name=num_special_txs_exec,json=numSpecialTxsExec,proto3" json:"num_special_txs_exec,omitempty"`
}

func (m *Index) Reset()         { *m = Index{} }
func (m *Index) String() string { return proto.CompactTextString(m) }
func (*Index) ProtoMessage()    {}
func (*Index) Descriptor() ([]byte, []int) {
	return fileDescriptor_da0963ea93fd9c30, []int{0}
}
func (m *Index) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Index) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Index.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Index) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Index.Merge(m, src)
}
func (m *Index) XXX_Size() int {
	return m.Size()
}
func (m *Index) XXX_DiscardUnknown() {
	xxx_messageInfo_Index.DiscardUnknown(m)
}

var xxx_messageInfo_Index proto.InternalMessageInfo

func (m *Index) GetNumInjectedTxsTotal() uint64 {
	if m != nil {
		return m.NumInjectedTxsTotal
	}
	return 0
}

func (m *Index) GetNumInjectedTxsAnte() uint64 {
	if m != nil {
		return m.NumInjectedTxsAnte
	}
	return 0
}

func (m *Index) GetNumSpecialTxsTotal() uint64 {
	if m != nil {
		return m.NumSpecialTxsTotal
	}
	return 0
}

func (m *Index) GetNumSpecialTxsExec() uint64 {
	if m != nil {
		return m.NumSpecialTxsExec
	}
	return 0
}

func init() {
	proto.RegisterType((*Index)(nil), "fuelsequencer.bridge.Index")
}

func init() { proto.RegisterFile("fuelsequencer/bridge/index.proto", fileDescriptor_da0963ea93fd9c30) }

var fileDescriptor_da0963ea93fd9c30 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x31, 0x4f, 0x84, 0x30,
	0x18, 0x86, 0xa9, 0x9e, 0x0e, 0x6c, 0x22, 0x1a, 0xbc, 0xa1, 0xb9, 0x38, 0xb9, 0x08, 0x31, 0xb7,
	0xba, 0x68, 0xe2, 0x70, 0xab, 0x5e, 0x1c, 0x5c, 0x08, 0x94, 0xef, 0xb0, 0x06, 0x5a, 0x6c, 0xbf,
	0x26, 0xf5, 0x5f, 0xf8, 0xb3, 0x1c, 0x2f, 0x71, 0x71, 0x34, 0xf0, 0x47, 0x0c, 0xd4, 0x3b, 0x45,
	0xb7, 0xb6, 0xcf, 0xfb, 0xf4, 0x4d, 0x5e, 0x7f, 0xb6, 0x32, 0x50, 0x69, 0x78, 0x36, 0x20, 0x18,
	0xa8, 0x24, 0x57, 0xbc, 0x28, 0x21, 0xe1, 0xa2, 0x00, 0x1b, 0x37, 0x4a, 0xa2, 0x0c, 0xc2, 0x51,
	0x22, 0x76, 0x89, 0x69, 0x58, 0xca, 0x52, 0x0e, 0x81, 0xa4, 0x3f, 0xb9, 0xec, 0xf4, 0x84, 0x49,
	0x5d, 0x4b, 0x9d, 0x3a, 0xe0, 0x2e, 0x0e, 0x9d, 0xbe, 0x13, 0x7f, 0x6f, 0xd1, 0x7f, 0x1b, 0xcc,
	0xfd, 0x63, 0x61, 0xea, 0x94, 0x8b, 0x27, 0x60, 0x08, 0x45, 0x8a, 0x56, 0xa7, 0x28, 0x31, 0xab,
	0x22, 0x32, 0x23, 0x67, 0x93, 0xdb, 0x43, 0x61, 0xea, 0xc5, 0x37, 0x5c, 0x5a, 0xbd, 0xec, 0x51,
	0x70, 0xe1, 0x1f, 0xfd, 0x93, 0x32, 0x81, 0x10, 0xed, 0x0c, 0x4e, 0x30, 0x76, 0xae, 0x04, 0xc2,
	0x46, 0xd1, 0x0d, 0x30, 0x9e, 0x55, 0xbf, 0x6a, 0x76, 0xb7, 0xca, 0x9d, 0x63, 0xdb, 0x96, 0xc4,
	0x0f, 0xff, 0x2a, 0x60, 0x81, 0x45, 0x93, 0xc1, 0x38, 0x18, 0x19, 0x37, 0x16, 0xd8, 0xf5, 0xfd,
	0x5b, 0x4b, 0xc9, 0xba, 0xa5, 0xe4, 0xb3, 0xa5, 0xe4, 0xb5, 0xa3, 0xde, 0xba, 0xa3, 0xde, 0x47,
	0x47, 0xbd, 0x87, 0xcb, 0x92, 0xe3, 0xa3, 0xc9, 0x63, 0x26, 0xeb, 0xa4, 0x5f, 0xf0, 0x9c, 0x8b,
	0x95, 0xca, 0x34, 0x2a, 0xc3, 0xd0, 0x28, 0x70, 0x6f, 0x3f, 0xc3, 0xdb, 0xcd, 0xf4, 0xf8, 0xd2,
	0x80, 0xce, 0xf7, 0x87, 0xd1, 0xe6, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x39, 0x05, 0x3c, 0x41,
	0x9f, 0x01, 0x00, 0x00,
}

func (m *Index) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Index) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Index) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NumSpecialTxsExec != 0 {
		i = encodeVarintIndex(dAtA, i, uint64(m.NumSpecialTxsExec))
		i--
		dAtA[i] = 0x20
	}
	if m.NumSpecialTxsTotal != 0 {
		i = encodeVarintIndex(dAtA, i, uint64(m.NumSpecialTxsTotal))
		i--
		dAtA[i] = 0x18
	}
	if m.NumInjectedTxsAnte != 0 {
		i = encodeVarintIndex(dAtA, i, uint64(m.NumInjectedTxsAnte))
		i--
		dAtA[i] = 0x10
	}
	if m.NumInjectedTxsTotal != 0 {
		i = encodeVarintIndex(dAtA, i, uint64(m.NumInjectedTxsTotal))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintIndex(dAtA []byte, offset int, v uint64) int {
	offset -= sovIndex(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Index) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NumInjectedTxsTotal != 0 {
		n += 1 + sovIndex(uint64(m.NumInjectedTxsTotal))
	}
	if m.NumInjectedTxsAnte != 0 {
		n += 1 + sovIndex(uint64(m.NumInjectedTxsAnte))
	}
	if m.NumSpecialTxsTotal != 0 {
		n += 1 + sovIndex(uint64(m.NumSpecialTxsTotal))
	}
	if m.NumSpecialTxsExec != 0 {
		n += 1 + sovIndex(uint64(m.NumSpecialTxsExec))
	}
	return n
}

func sovIndex(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozIndex(x uint64) (n int) {
	return sovIndex(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Index) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIndex
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Index: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Index: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumInjectedTxsTotal", wireType)
			}
			m.NumInjectedTxsTotal = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndex
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumInjectedTxsTotal |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumInjectedTxsAnte", wireType)
			}
			m.NumInjectedTxsAnte = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndex
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumInjectedTxsAnte |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumSpecialTxsTotal", wireType)
			}
			m.NumSpecialTxsTotal = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndex
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumSpecialTxsTotal |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumSpecialTxsExec", wireType)
			}
			m.NumSpecialTxsExec = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIndex
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumSpecialTxsExec |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipIndex(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIndex
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipIndex(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowIndex
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIndex
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIndex
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthIndex
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupIndex
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthIndex
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthIndex        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowIndex          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupIndex = fmt.Errorf("proto: unexpected end of group")
)
