// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fuelsequencer/bridge/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	// bridge_denom is the assumed denom for the bridged token, used when minting
	// upon deposits, burning when withdrawing, and tracking changes in its
	// supply that will be reported to Ethereum, amongst other scenarios.
	BridgeDenom string `protobuf:"bytes,1,opt,name=bridge_denom,json=bridgeDenom,proto3" json:"bridge_denom,omitempty"`
	// ethereum_proxy_contract_address is the contract address we expect to
	// receive deposit and authorize messages from.
	EthereumProxyContractAddress string `protobuf:"bytes,2,opt,name=ethereum_proxy_contract_address,json=ethereumProxyContractAddress,proto3" json:"ethereum_proxy_contract_address,omitempty"`
	// authorize_messages_allowed is a whitelist for authorize messages that we
	// can receive and process.
	AuthorizeMessagesAllowed []string `protobuf:"bytes,3,rep,name=authorize_messages_allowed,json=authorizeMessagesAllowed,proto3" json:"authorize_messages_allowed,omitempty"`
	// supply_delta_period is the frequency in block at which we report supply
	// delta info to Ethereum.
	SupplyDeltaPeriod uint64 `protobuf:"varint,4,opt,name=supply_delta_period,json=supplyDeltaPeriod,proto3" json:"supply_delta_period,omitempty"`
	// vesting_start_time is the common vesting starting time for vesting accounts
	// that will be created through deposits from Ethereum.
	VestingStartTime time.Time `protobuf:"bytes,5,opt,name=vesting_start_time,json=vestingStartTime,proto3,stdtime" json:"vesting_start_time"`
	// additional_blocked_addresses is a list of Cosmos SDK-based addresses that
	// are explicitly disallowed from being controlled by authorize messages
	// within the Sequencer system. This can include addresses of module accounts,
	// validator operators, or any other addresses deemed necessary to protect
	// from unauthorized control actions.
	AdditionalBlockedAddresses []string `protobuf:"bytes,6,rep,name=additional_blocked_addresses,json=additionalBlockedAddresses,proto3" json:"additional_blocked_addresses,omitempty"`
	// max_eth_block_update_delay is the maximum amount of time that the Sequencer
	// allows validators to not sync up with Ethereum. Once
	// max_eth_block_update_delay is exceeded, the Sequencer's block production
	// will halt until validators sync up with next Ethereum block.
	MaxEthBlockUpdateDelay time.Duration `protobuf:"bytes,7,opt,name=max_eth_block_update_delay,json=maxEthBlockUpdateDelay,proto3,stdduration" json:"max_eth_block_update_delay"`
	// injected_event_tx_max_bytes is the maximum amount of block space that an
	// injected event tx can take in terms of bytes. An Authorize event gets
	// skipped and never included in a block if it can't be converted into a tx
	// that can respect this limit. On the other hand, if a Deposit event cannot
	// be converted into a Tx that can respect this limit, the chain halts.
	InjectedEventTxMaxBytes uint64 `protobuf:"varint,8,opt,name=injected_event_tx_max_bytes,json=injectedEventTxMaxBytes,proto3" json:"injected_event_tx_max_bytes,omitempty"`
	// max_authorize_messages is the maximum amount of Cosmos SDK messages that an
	// Authorize transaction can have
	MaxAuthorizeMessages uint64 `protobuf:"varint,9,opt,name=max_authorize_messages,json=maxAuthorizeMessages,proto3" json:"max_authorize_messages,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_99c31778739894e8, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetBridgeDenom() string {
	if m != nil {
		return m.BridgeDenom
	}
	return ""
}

func (m *Params) GetEthereumProxyContractAddress() string {
	if m != nil {
		return m.EthereumProxyContractAddress
	}
	return ""
}

func (m *Params) GetAuthorizeMessagesAllowed() []string {
	if m != nil {
		return m.AuthorizeMessagesAllowed
	}
	return nil
}

func (m *Params) GetSupplyDeltaPeriod() uint64 {
	if m != nil {
		return m.SupplyDeltaPeriod
	}
	return 0
}

func (m *Params) GetVestingStartTime() time.Time {
	if m != nil {
		return m.VestingStartTime
	}
	return time.Time{}
}

func (m *Params) GetAdditionalBlockedAddresses() []string {
	if m != nil {
		return m.AdditionalBlockedAddresses
	}
	return nil
}

func (m *Params) GetMaxEthBlockUpdateDelay() time.Duration {
	if m != nil {
		return m.MaxEthBlockUpdateDelay
	}
	return 0
}

func (m *Params) GetInjectedEventTxMaxBytes() uint64 {
	if m != nil {
		return m.InjectedEventTxMaxBytes
	}
	return 0
}

func (m *Params) GetMaxAuthorizeMessages() uint64 {
	if m != nil {
		return m.MaxAuthorizeMessages
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "fuelsequencer.bridge.Params")
}

func init() { proto.RegisterFile("fuelsequencer/bridge/params.proto", fileDescriptor_99c31778739894e8) }

var fileDescriptor_99c31778739894e8 = []byte{
	// 559 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x3f, 0x6f, 0xd3, 0x4e,
	0x18, 0xc7, 0xe3, 0x5f, 0xfb, 0x2b, 0xad, 0xcb, 0x40, 0x4d, 0x05, 0xc6, 0x14, 0x27, 0x65, 0x40,
	0x11, 0x12, 0xb6, 0x04, 0x4c, 0xa8, 0x03, 0x09, 0xc9, 0x58, 0x29, 0x0a, 0x85, 0x81, 0xe5, 0x74,
	0xf6, 0x3d, 0x71, 0x0c, 0xb6, 0xcf, 0xdc, 0x3d, 0x2e, 0x0e, 0x2f, 0x81, 0xa9, 0x23, 0x23, 0x2f,
	0x81, 0x97, 0xd1, 0xb1, 0x23, 0x13, 0xa0, 0x64, 0x80, 0x9d, 0x37, 0x80, 0xee, 0xce, 0x06, 0xb5,
	0x65, 0x89, 0x2e, 0xcf, 0xf7, 0xf3, 0xfc, 0xf1, 0xf7, 0x79, 0xec, 0xfd, 0x59, 0x05, 0x99, 0x84,
	0xb7, 0x15, 0x14, 0x31, 0x88, 0x30, 0x12, 0x29, 0x4b, 0x20, 0x2c, 0xa9, 0xa0, 0xb9, 0x0c, 0x4a,
	0xc1, 0x91, 0x3b, 0xbb, 0xe7, 0x90, 0xc0, 0x20, 0xde, 0x0e, 0xcd, 0xd3, 0x82, 0x87, 0xfa, 0xd7,
	0x80, 0xde, 0x6e, 0xc2, 0x13, 0xae, 0x9f, 0xa1, 0x7a, 0x35, 0xd1, 0x6e, 0xc2, 0x79, 0x92, 0x41,
	0xa8, 0xff, 0x45, 0xd5, 0x2c, 0xc4, 0x34, 0x07, 0x89, 0x34, 0x2f, 0x1b, 0xc0, 0xbf, 0x08, 0xb0,
	0x4a, 0x50, 0x4c, 0x79, 0x61, 0xf4, 0xbb, 0xbf, 0xd6, 0xed, 0x8d, 0x89, 0x1e, 0xc8, 0xd9, 0xb7,
	0xaf, 0x9a, 0xf6, 0x84, 0x41, 0xc1, 0x73, 0xd7, 0xea, 0x59, 0xfd, 0xad, 0xe9, 0xb6, 0x89, 0x8d,
	0x54, 0xc8, 0x19, 0xdb, 0x5d, 0xc0, 0x39, 0x08, 0xa8, 0x72, 0x52, 0x0a, 0x5e, 0x2f, 0x48, 0xcc,
	0x0b, 0x14, 0x34, 0x46, 0x42, 0x19, 0x13, 0x20, 0xa5, 0xfb, 0x9f, 0xce, 0xda, 0x6b, 0xb1, 0x89,
	0xa2, 0x9e, 0x35, 0xd0, 0xc0, 0x30, 0xce, 0x81, 0xed, 0xd1, 0x0a, 0xe7, 0x5c, 0xa4, 0xef, 0x81,
	0xe4, 0x20, 0x25, 0x4d, 0x40, 0x12, 0x9a, 0x65, 0xfc, 0x1d, 0x30, 0x77, 0xad, 0xb7, 0xd6, 0xdf,
	0x9a, 0xba, 0x7f, 0x88, 0xc3, 0x06, 0x18, 0x18, 0xdd, 0x09, 0xec, 0xeb, 0xb2, 0x2a, 0xcb, 0x6c,
	0x41, 0x18, 0x64, 0x48, 0x49, 0x09, 0x22, 0xe5, 0xcc, 0x5d, 0xef, 0x59, 0xfd, 0xf5, 0xe9, 0x8e,
	0x91, 0x46, 0x4a, 0x99, 0x68, 0xc1, 0x99, 0xda, 0xce, 0x31, 0x48, 0x4c, 0x8b, 0x84, 0x48, 0xa4,
	0x02, 0x89, 0xf2, 0xc8, 0xfd, 0xbf, 0x67, 0xf5, 0xb7, 0x1f, 0x7a, 0x81, 0xf1, 0x27, 0x68, 0xfd,
	0x09, 0x8e, 0x5a, 0x03, 0x87, 0x9b, 0xa7, 0x5f, 0xbb, 0x9d, 0x93, 0x6f, 0x5d, 0x6b, 0x7a, 0xad,
	0xc9, 0x7f, 0xae, 0xd2, 0x15, 0xe0, 0x3c, 0xb5, 0xf7, 0x28, 0x63, 0xa9, 0x32, 0x92, 0x66, 0x24,
	0xca, 0x78, 0xfc, 0x06, 0x58, 0xeb, 0x01, 0x48, 0x77, 0x43, 0x7f, 0x83, 0xf7, 0x97, 0x19, 0x1a,
	0x64, 0xd0, 0x12, 0x0e, 0xb1, 0xbd, 0x9c, 0xd6, 0x04, 0x70, 0x6e, 0xd2, 0x49, 0x55, 0x32, 0x8a,
	0xca, 0xfb, 0x8c, 0x2e, 0xdc, 0x2b, 0x7a, 0xba, 0x5b, 0x97, 0xa6, 0x1b, 0x35, 0xdb, 0x33, 0xc3,
	0x7d, 0x54, 0xc3, 0xdd, 0xc8, 0x69, 0x3d, 0xc6, 0xb9, 0x6e, 0xf0, 0x42, 0xd7, 0x18, 0xa9, 0x12,
	0xce, 0x81, 0x7d, 0x3b, 0x2d, 0x5e, 0x43, 0x8c, 0xc0, 0x08, 0x1c, 0x43, 0x81, 0x04, 0x6b, 0xa2,
	0x5a, 0x46, 0x0b, 0x04, 0xe9, 0x6e, 0x6a, 0xbb, 0x6e, 0xb6, 0xc8, 0x58, 0x11, 0x47, 0xf5, 0x21,
	0xad, 0x87, 0x4a, 0x76, 0x1e, 0xdb, 0xaa, 0x2e, 0xb9, 0xbc, 0x26, 0x77, 0x4b, 0x27, 0xee, 0xe6,
	0xb4, 0x1e, 0x5c, 0xdc, 0xd0, 0x93, 0x7b, 0x3f, 0x3f, 0x75, 0xad, 0x0f, 0x3f, 0x3e, 0xdf, 0xbf,
	0x73, 0xfe, 0xf2, 0xeb, 0xf6, 0xf6, 0xcd, 0xa9, 0x0d, 0x5f, 0x9e, 0x2e, 0x7d, 0xeb, 0x6c, 0xe9,
	0x5b, 0xdf, 0x97, 0xbe, 0x75, 0xb2, 0xf2, 0x3b, 0x67, 0x2b, 0xbf, 0xf3, 0x65, 0xe5, 0x77, 0x5e,
	0x1d, 0x24, 0x29, 0xce, 0xab, 0x28, 0x88, 0x79, 0x1e, 0xaa, 0x1a, 0x0f, 0xd2, 0x62, 0x26, 0xa8,
	0x44, 0x51, 0xc5, 0x58, 0x09, 0x30, 0xb1, 0x7f, 0x14, 0xc6, 0x45, 0x09, 0x32, 0xda, 0xd0, 0x46,
	0x3d, 0xfa, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xbb, 0x2b, 0x29, 0xa6, 0x79, 0x03, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.BridgeDenom != that1.BridgeDenom {
		return false
	}
	if this.EthereumProxyContractAddress != that1.EthereumProxyContractAddress {
		return false
	}
	if len(this.AuthorizeMessagesAllowed) != len(that1.AuthorizeMessagesAllowed) {
		return false
	}
	for i := range this.AuthorizeMessagesAllowed {
		if this.AuthorizeMessagesAllowed[i] != that1.AuthorizeMessagesAllowed[i] {
			return false
		}
	}
	if this.SupplyDeltaPeriod != that1.SupplyDeltaPeriod {
		return false
	}
	if !this.VestingStartTime.Equal(that1.VestingStartTime) {
		return false
	}
	if len(this.AdditionalBlockedAddresses) != len(that1.AdditionalBlockedAddresses) {
		return false
	}
	for i := range this.AdditionalBlockedAddresses {
		if this.AdditionalBlockedAddresses[i] != that1.AdditionalBlockedAddresses[i] {
			return false
		}
	}
	if this.MaxEthBlockUpdateDelay != that1.MaxEthBlockUpdateDelay {
		return false
	}
	if this.InjectedEventTxMaxBytes != that1.InjectedEventTxMaxBytes {
		return false
	}
	if this.MaxAuthorizeMessages != that1.MaxAuthorizeMessages {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxAuthorizeMessages != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxAuthorizeMessages))
		i--
		dAtA[i] = 0x48
	}
	if m.InjectedEventTxMaxBytes != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.InjectedEventTxMaxBytes))
		i--
		dAtA[i] = 0x40
	}
	n1, err1 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.MaxEthBlockUpdateDelay, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MaxEthBlockUpdateDelay):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintParams(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x3a
	if len(m.AdditionalBlockedAddresses) > 0 {
		for iNdEx := len(m.AdditionalBlockedAddresses) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AdditionalBlockedAddresses[iNdEx])
			copy(dAtA[i:], m.AdditionalBlockedAddresses[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.AdditionalBlockedAddresses[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.VestingStartTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.VestingStartTime):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintParams(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x2a
	if m.SupplyDeltaPeriod != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.SupplyDeltaPeriod))
		i--
		dAtA[i] = 0x20
	}
	if len(m.AuthorizeMessagesAllowed) > 0 {
		for iNdEx := len(m.AuthorizeMessagesAllowed) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AuthorizeMessagesAllowed[iNdEx])
			copy(dAtA[i:], m.AuthorizeMessagesAllowed[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.AuthorizeMessagesAllowed[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.EthereumProxyContractAddress) > 0 {
		i -= len(m.EthereumProxyContractAddress)
		copy(dAtA[i:], m.EthereumProxyContractAddress)
		i = encodeVarintParams(dAtA, i, uint64(len(m.EthereumProxyContractAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.BridgeDenom) > 0 {
		i -= len(m.BridgeDenom)
		copy(dAtA[i:], m.BridgeDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.BridgeDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.BridgeDenom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.EthereumProxyContractAddress)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if len(m.AuthorizeMessagesAllowed) > 0 {
		for _, s := range m.AuthorizeMessagesAllowed {
			l = len(s)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if m.SupplyDeltaPeriod != 0 {
		n += 1 + sovParams(uint64(m.SupplyDeltaPeriod))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.VestingStartTime)
	n += 1 + l + sovParams(uint64(l))
	if len(m.AdditionalBlockedAddresses) > 0 {
		for _, s := range m.AdditionalBlockedAddresses {
			l = len(s)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MaxEthBlockUpdateDelay)
	n += 1 + l + sovParams(uint64(l))
	if m.InjectedEventTxMaxBytes != 0 {
		n += 1 + sovParams(uint64(m.InjectedEventTxMaxBytes))
	}
	if m.MaxAuthorizeMessages != 0 {
		n += 1 + sovParams(uint64(m.MaxAuthorizeMessages))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BridgeDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BridgeDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EthereumProxyContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EthereumProxyContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthorizeMessagesAllowed", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuthorizeMessagesAllowed = append(m.AuthorizeMessagesAllowed, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SupplyDeltaPeriod", wireType)
			}
			m.SupplyDeltaPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SupplyDeltaPeriod |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VestingStartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.VestingStartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AdditionalBlockedAddresses", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AdditionalBlockedAddresses = append(m.AdditionalBlockedAddresses, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxEthBlockUpdateDelay", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.MaxEthBlockUpdateDelay, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InjectedEventTxMaxBytes", wireType)
			}
			m.InjectedEventTxMaxBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InjectedEventTxMaxBytes |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxAuthorizeMessages", wireType)
			}
			m.MaxAuthorizeMessages = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxAuthorizeMessages |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
