// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fuelsequencer/bridge/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_374d0ea27e584428, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_374d0ea27e584428, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetSupplyDeltaInfoRequest struct {
}

func (m *QueryGetSupplyDeltaInfoRequest) Reset()         { *m = QueryGetSupplyDeltaInfoRequest{} }
func (m *QueryGetSupplyDeltaInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetSupplyDeltaInfoRequest) ProtoMessage()    {}
func (*QueryGetSupplyDeltaInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_374d0ea27e584428, []int{2}
}
func (m *QueryGetSupplyDeltaInfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSupplyDeltaInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSupplyDeltaInfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSupplyDeltaInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSupplyDeltaInfoRequest.Merge(m, src)
}
func (m *QueryGetSupplyDeltaInfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSupplyDeltaInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSupplyDeltaInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSupplyDeltaInfoRequest proto.InternalMessageInfo

type QueryGetSupplyDeltaInfoResponse struct {
	SupplyDeltaInfo SupplyDeltaInfo `protobuf:"bytes,1,opt,name=SupplyDeltaInfo,proto3" json:"SupplyDeltaInfo"`
}

func (m *QueryGetSupplyDeltaInfoResponse) Reset()         { *m = QueryGetSupplyDeltaInfoResponse{} }
func (m *QueryGetSupplyDeltaInfoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetSupplyDeltaInfoResponse) ProtoMessage()    {}
func (*QueryGetSupplyDeltaInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_374d0ea27e584428, []int{3}
}
func (m *QueryGetSupplyDeltaInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSupplyDeltaInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSupplyDeltaInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSupplyDeltaInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSupplyDeltaInfoResponse.Merge(m, src)
}
func (m *QueryGetSupplyDeltaInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSupplyDeltaInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSupplyDeltaInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSupplyDeltaInfoResponse proto.InternalMessageInfo

func (m *QueryGetSupplyDeltaInfoResponse) GetSupplyDeltaInfo() SupplyDeltaInfo {
	if m != nil {
		return m.SupplyDeltaInfo
	}
	return SupplyDeltaInfo{}
}

type QueryGetLastEthereumNonceRequest struct {
}

func (m *QueryGetLastEthereumNonceRequest) Reset()         { *m = QueryGetLastEthereumNonceRequest{} }
func (m *QueryGetLastEthereumNonceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetLastEthereumNonceRequest) ProtoMessage()    {}
func (*QueryGetLastEthereumNonceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_374d0ea27e584428, []int{4}
}
func (m *QueryGetLastEthereumNonceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetLastEthereumNonceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetLastEthereumNonceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetLastEthereumNonceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetLastEthereumNonceRequest.Merge(m, src)
}
func (m *QueryGetLastEthereumNonceRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetLastEthereumNonceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetLastEthereumNonceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetLastEthereumNonceRequest proto.InternalMessageInfo

type QueryGetLastEthereumNonceResponse struct {
	Nonce string `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (m *QueryGetLastEthereumNonceResponse) Reset()         { *m = QueryGetLastEthereumNonceResponse{} }
func (m *QueryGetLastEthereumNonceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetLastEthereumNonceResponse) ProtoMessage()    {}
func (*QueryGetLastEthereumNonceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_374d0ea27e584428, []int{5}
}
func (m *QueryGetLastEthereumNonceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetLastEthereumNonceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetLastEthereumNonceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetLastEthereumNonceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetLastEthereumNonceResponse.Merge(m, src)
}
func (m *QueryGetLastEthereumNonceResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetLastEthereumNonceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetLastEthereumNonceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetLastEthereumNonceResponse proto.InternalMessageInfo

func (m *QueryGetLastEthereumNonceResponse) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

type QueryGetLastEthereumBlockSyncedRequest struct {
}

func (m *QueryGetLastEthereumBlockSyncedRequest) Reset() {
	*m = QueryGetLastEthereumBlockSyncedRequest{}
}
func (m *QueryGetLastEthereumBlockSyncedRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetLastEthereumBlockSyncedRequest) ProtoMessage()    {}
func (*QueryGetLastEthereumBlockSyncedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_374d0ea27e584428, []int{6}
}
func (m *QueryGetLastEthereumBlockSyncedRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetLastEthereumBlockSyncedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetLastEthereumBlockSyncedRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetLastEthereumBlockSyncedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetLastEthereumBlockSyncedRequest.Merge(m, src)
}
func (m *QueryGetLastEthereumBlockSyncedRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetLastEthereumBlockSyncedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetLastEthereumBlockSyncedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetLastEthereumBlockSyncedRequest proto.InternalMessageInfo

type QueryGetLastEthereumBlockSyncedResponse struct {
	Block uint64 `protobuf:"varint,1,opt,name=block,proto3" json:"block,omitempty"`
}

func (m *QueryGetLastEthereumBlockSyncedResponse) Reset() {
	*m = QueryGetLastEthereumBlockSyncedResponse{}
}
func (m *QueryGetLastEthereumBlockSyncedResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetLastEthereumBlockSyncedResponse) ProtoMessage()    {}
func (*QueryGetLastEthereumBlockSyncedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_374d0ea27e584428, []int{7}
}
func (m *QueryGetLastEthereumBlockSyncedResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetLastEthereumBlockSyncedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetLastEthereumBlockSyncedResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetLastEthereumBlockSyncedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetLastEthereumBlockSyncedResponse.Merge(m, src)
}
func (m *QueryGetLastEthereumBlockSyncedResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetLastEthereumBlockSyncedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetLastEthereumBlockSyncedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetLastEthereumBlockSyncedResponse proto.InternalMessageInfo

func (m *QueryGetLastEthereumBlockSyncedResponse) GetBlock() uint64 {
	if m != nil {
		return m.Block
	}
	return 0
}

type QueryGetEthereumEventIndexOffsetRequest struct {
}

func (m *QueryGetEthereumEventIndexOffsetRequest) Reset() {
	*m = QueryGetEthereumEventIndexOffsetRequest{}
}
func (m *QueryGetEthereumEventIndexOffsetRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetEthereumEventIndexOffsetRequest) ProtoMessage()    {}
func (*QueryGetEthereumEventIndexOffsetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_374d0ea27e584428, []int{8}
}
func (m *QueryGetEthereumEventIndexOffsetRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetEthereumEventIndexOffsetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetEthereumEventIndexOffsetRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetEthereumEventIndexOffsetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetEthereumEventIndexOffsetRequest.Merge(m, src)
}
func (m *QueryGetEthereumEventIndexOffsetRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetEthereumEventIndexOffsetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetEthereumEventIndexOffsetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetEthereumEventIndexOffsetRequest proto.InternalMessageInfo

type QueryGetEthereumEventIndexOffsetResponse struct {
	Offset uint64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (m *QueryGetEthereumEventIndexOffsetResponse) Reset() {
	*m = QueryGetEthereumEventIndexOffsetResponse{}
}
func (m *QueryGetEthereumEventIndexOffsetResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetEthereumEventIndexOffsetResponse) ProtoMessage()    {}
func (*QueryGetEthereumEventIndexOffsetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_374d0ea27e584428, []int{9}
}
func (m *QueryGetEthereumEventIndexOffsetResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetEthereumEventIndexOffsetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetEthereumEventIndexOffsetResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetEthereumEventIndexOffsetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetEthereumEventIndexOffsetResponse.Merge(m, src)
}
func (m *QueryGetEthereumEventIndexOffsetResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetEthereumEventIndexOffsetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetEthereumEventIndexOffsetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetEthereumEventIndexOffsetResponse proto.InternalMessageInfo

func (m *QueryGetEthereumEventIndexOffsetResponse) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type QuerySequencerAddressFromEthereumAddressRequest struct {
	EthereumAddress string `protobuf:"bytes,1,opt,name=ethereum_address,json=ethereumAddress,proto3" json:"ethereum_address,omitempty"`
}

func (m *QuerySequencerAddressFromEthereumAddressRequest) Reset() {
	*m = QuerySequencerAddressFromEthereumAddressRequest{}
}
func (m *QuerySequencerAddressFromEthereumAddressRequest) String() string {
	return proto.CompactTextString(m)
}
func (*QuerySequencerAddressFromEthereumAddressRequest) ProtoMessage() {}
func (*QuerySequencerAddressFromEthereumAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_374d0ea27e584428, []int{10}
}
func (m *QuerySequencerAddressFromEthereumAddressRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySequencerAddressFromEthereumAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySequencerAddressFromEthereumAddressRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySequencerAddressFromEthereumAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySequencerAddressFromEthereumAddressRequest.Merge(m, src)
}
func (m *QuerySequencerAddressFromEthereumAddressRequest) XXX_Size() int {
	return m.Size()
}
func (m *QuerySequencerAddressFromEthereumAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySequencerAddressFromEthereumAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySequencerAddressFromEthereumAddressRequest proto.InternalMessageInfo

func (m *QuerySequencerAddressFromEthereumAddressRequest) GetEthereumAddress() string {
	if m != nil {
		return m.EthereumAddress
	}
	return ""
}

type QuerySequencerAddressFromEthereumAddressResponse struct {
	SequencerAddress string `protobuf:"bytes,1,opt,name=sequencer_address,json=sequencerAddress,proto3" json:"sequencer_address,omitempty"`
}

func (m *QuerySequencerAddressFromEthereumAddressResponse) Reset() {
	*m = QuerySequencerAddressFromEthereumAddressResponse{}
}
func (m *QuerySequencerAddressFromEthereumAddressResponse) String() string {
	return proto.CompactTextString(m)
}
func (*QuerySequencerAddressFromEthereumAddressResponse) ProtoMessage() {}
func (*QuerySequencerAddressFromEthereumAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_374d0ea27e584428, []int{11}
}
func (m *QuerySequencerAddressFromEthereumAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySequencerAddressFromEthereumAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySequencerAddressFromEthereumAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySequencerAddressFromEthereumAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySequencerAddressFromEthereumAddressResponse.Merge(m, src)
}
func (m *QuerySequencerAddressFromEthereumAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *QuerySequencerAddressFromEthereumAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySequencerAddressFromEthereumAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySequencerAddressFromEthereumAddressResponse proto.InternalMessageInfo

func (m *QuerySequencerAddressFromEthereumAddressResponse) GetSequencerAddress() string {
	if m != nil {
		return m.SequencerAddress
	}
	return ""
}

type QueryGetLastEthBlockUpdateTimeRequest struct {
}

func (m *QueryGetLastEthBlockUpdateTimeRequest) Reset()         { *m = QueryGetLastEthBlockUpdateTimeRequest{} }
func (m *QueryGetLastEthBlockUpdateTimeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetLastEthBlockUpdateTimeRequest) ProtoMessage()    {}
func (*QueryGetLastEthBlockUpdateTimeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_374d0ea27e584428, []int{12}
}
func (m *QueryGetLastEthBlockUpdateTimeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetLastEthBlockUpdateTimeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetLastEthBlockUpdateTimeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetLastEthBlockUpdateTimeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetLastEthBlockUpdateTimeRequest.Merge(m, src)
}
func (m *QueryGetLastEthBlockUpdateTimeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetLastEthBlockUpdateTimeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetLastEthBlockUpdateTimeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetLastEthBlockUpdateTimeRequest proto.InternalMessageInfo

type QueryGetLastEthBlockUpdateTimeResponse struct {
	LastEthBlockUpdateTime time.Time `protobuf:"bytes,1,opt,name=last_eth_block_update_time,json=lastEthBlockUpdateTime,proto3,stdtime" json:"last_eth_block_update_time"`
}

func (m *QueryGetLastEthBlockUpdateTimeResponse) Reset() {
	*m = QueryGetLastEthBlockUpdateTimeResponse{}
}
func (m *QueryGetLastEthBlockUpdateTimeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetLastEthBlockUpdateTimeResponse) ProtoMessage()    {}
func (*QueryGetLastEthBlockUpdateTimeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_374d0ea27e584428, []int{13}
}
func (m *QueryGetLastEthBlockUpdateTimeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetLastEthBlockUpdateTimeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetLastEthBlockUpdateTimeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetLastEthBlockUpdateTimeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetLastEthBlockUpdateTimeResponse.Merge(m, src)
}
func (m *QueryGetLastEthBlockUpdateTimeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetLastEthBlockUpdateTimeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetLastEthBlockUpdateTimeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetLastEthBlockUpdateTimeResponse proto.InternalMessageInfo

func (m *QueryGetLastEthBlockUpdateTimeResponse) GetLastEthBlockUpdateTime() time.Time {
	if m != nil {
		return m.LastEthBlockUpdateTime
	}
	return time.Time{}
}

type QueryGetLastInjectedTxsSequenceRequest struct {
}

func (m *QueryGetLastInjectedTxsSequenceRequest) Reset() {
	*m = QueryGetLastInjectedTxsSequenceRequest{}
}
func (m *QueryGetLastInjectedTxsSequenceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetLastInjectedTxsSequenceRequest) ProtoMessage()    {}
func (*QueryGetLastInjectedTxsSequenceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_374d0ea27e584428, []int{14}
}
func (m *QueryGetLastInjectedTxsSequenceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetLastInjectedTxsSequenceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetLastInjectedTxsSequenceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetLastInjectedTxsSequenceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetLastInjectedTxsSequenceRequest.Merge(m, src)
}
func (m *QueryGetLastInjectedTxsSequenceRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetLastInjectedTxsSequenceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetLastInjectedTxsSequenceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetLastInjectedTxsSequenceRequest proto.InternalMessageInfo

type QueryGetLastInjectedTxsSequenceResponse struct {
	Sequence uint64 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
}

func (m *QueryGetLastInjectedTxsSequenceResponse) Reset() {
	*m = QueryGetLastInjectedTxsSequenceResponse{}
}
func (m *QueryGetLastInjectedTxsSequenceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetLastInjectedTxsSequenceResponse) ProtoMessage()    {}
func (*QueryGetLastInjectedTxsSequenceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_374d0ea27e584428, []int{15}
}
func (m *QueryGetLastInjectedTxsSequenceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetLastInjectedTxsSequenceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetLastInjectedTxsSequenceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetLastInjectedTxsSequenceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetLastInjectedTxsSequenceResponse.Merge(m, src)
}
func (m *QueryGetLastInjectedTxsSequenceResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetLastInjectedTxsSequenceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetLastInjectedTxsSequenceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetLastInjectedTxsSequenceResponse proto.InternalMessageInfo

func (m *QueryGetLastInjectedTxsSequenceResponse) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "fuelsequencer.bridge.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "fuelsequencer.bridge.v1.QueryParamsResponse")
	proto.RegisterType((*QueryGetSupplyDeltaInfoRequest)(nil), "fuelsequencer.bridge.v1.QueryGetSupplyDeltaInfoRequest")
	proto.RegisterType((*QueryGetSupplyDeltaInfoResponse)(nil), "fuelsequencer.bridge.v1.QueryGetSupplyDeltaInfoResponse")
	proto.RegisterType((*QueryGetLastEthereumNonceRequest)(nil), "fuelsequencer.bridge.v1.QueryGetLastEthereumNonceRequest")
	proto.RegisterType((*QueryGetLastEthereumNonceResponse)(nil), "fuelsequencer.bridge.v1.QueryGetLastEthereumNonceResponse")
	proto.RegisterType((*QueryGetLastEthereumBlockSyncedRequest)(nil), "fuelsequencer.bridge.v1.QueryGetLastEthereumBlockSyncedRequest")
	proto.RegisterType((*QueryGetLastEthereumBlockSyncedResponse)(nil), "fuelsequencer.bridge.v1.QueryGetLastEthereumBlockSyncedResponse")
	proto.RegisterType((*QueryGetEthereumEventIndexOffsetRequest)(nil), "fuelsequencer.bridge.v1.QueryGetEthereumEventIndexOffsetRequest")
	proto.RegisterType((*QueryGetEthereumEventIndexOffsetResponse)(nil), "fuelsequencer.bridge.v1.QueryGetEthereumEventIndexOffsetResponse")
	proto.RegisterType((*QuerySequencerAddressFromEthereumAddressRequest)(nil), "fuelsequencer.bridge.v1.QuerySequencerAddressFromEthereumAddressRequest")
	proto.RegisterType((*QuerySequencerAddressFromEthereumAddressResponse)(nil), "fuelsequencer.bridge.v1.QuerySequencerAddressFromEthereumAddressResponse")
	proto.RegisterType((*QueryGetLastEthBlockUpdateTimeRequest)(nil), "fuelsequencer.bridge.v1.QueryGetLastEthBlockUpdateTimeRequest")
	proto.RegisterType((*QueryGetLastEthBlockUpdateTimeResponse)(nil), "fuelsequencer.bridge.v1.QueryGetLastEthBlockUpdateTimeResponse")
	proto.RegisterType((*QueryGetLastInjectedTxsSequenceRequest)(nil), "fuelsequencer.bridge.v1.QueryGetLastInjectedTxsSequenceRequest")
	proto.RegisterType((*QueryGetLastInjectedTxsSequenceResponse)(nil), "fuelsequencer.bridge.v1.QueryGetLastInjectedTxsSequenceResponse")
}

func init() {
	proto.RegisterFile("fuelsequencer/bridge/v1/query.proto", fileDescriptor_374d0ea27e584428)
}

var fileDescriptor_374d0ea27e584428 = []byte{
	// 955 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcb, 0x6f, 0xdc, 0x44,
	0x1c, 0x8e, 0xab, 0x36, 0x6a, 0x07, 0xa1, 0x36, 0x43, 0x94, 0x16, 0xab, 0xda, 0x4d, 0x5c, 0x95,
	0xa4, 0x69, 0xb0, 0x49, 0x5a, 0x1e, 0x85, 0x8a, 0xd0, 0x15, 0x01, 0x22, 0x21, 0x1e, 0xbb, 0x49,
	0x0f, 0x80, 0x64, 0x66, 0xed, 0xf1, 0xc6, 0xb0, 0x9e, 0x71, 0x3d, 0xe3, 0xd5, 0xae, 0x10, 0x17,
	0x8e, 0x88, 0x43, 0x25, 0x0e, 0x1c, 0xb9, 0x72, 0xe4, 0xc8, 0x91, 0x63, 0x8f, 0x95, 0x90, 0x10,
	0x1c, 0x78, 0x28, 0x41, 0xe2, 0xdf, 0x40, 0x9e, 0xc7, 0x46, 0xeb, 0xc7, 0xae, 0x13, 0x7a, 0x89,
	0x76, 0x66, 0xbe, 0xf9, 0x7e, 0xdf, 0x37, 0xfe, 0x3d, 0x02, 0xae, 0x05, 0x29, 0xee, 0x33, 0xfc,
	0x20, 0xc5, 0xc4, 0xc3, 0x89, 0xd3, 0x4d, 0x42, 0xbf, 0x87, 0x9d, 0xc1, 0xa6, 0xf3, 0x20, 0xc5,
	0xc9, 0xc8, 0x8e, 0x13, 0xca, 0x29, 0xbc, 0x3c, 0x01, 0xb2, 0x25, 0xc8, 0x1e, 0x6c, 0x9a, 0x0b,
	0x28, 0x0a, 0x09, 0x75, 0xc4, 0x5f, 0x89, 0x35, 0x17, 0x7b, 0xb4, 0x47, 0xc5, 0x4f, 0x27, 0xfb,
	0xa5, 0x76, 0xaf, 0xf6, 0x28, 0xed, 0xf5, 0xb1, 0x83, 0xe2, 0xd0, 0x41, 0x84, 0x50, 0x8e, 0x78,
	0x48, 0x09, 0x53, 0xa7, 0xcf, 0x7a, 0x94, 0x45, 0x94, 0xb9, 0xf2, 0x9a, 0x5c, 0xa8, 0xa3, 0x75,
	0xb9, 0x72, 0xba, 0x88, 0x61, 0xa9, 0xc9, 0x19, 0x6c, 0x76, 0x31, 0x47, 0x9b, 0x4e, 0x8c, 0x7a,
	0x21, 0x11, 0x3c, 0x0a, 0xbb, 0x52, 0xea, 0x25, 0x46, 0x09, 0x8a, 0x34, 0xdd, 0x46, 0x29, 0x84,
	0xa5, 0x71, 0xdc, 0x1f, 0xb9, 0x3e, 0xee, 0x73, 0xe4, 0x86, 0x24, 0xd0, 0xaa, 0x97, 0x4b, 0xd1,
	0x21, 0xf1, 0xf1, 0x50, 0x21, 0x9a, 0xca, 0x97, 0x58, 0x75, 0xd3, 0xc0, 0xe1, 0x61, 0x84, 0x19,
	0x47, 0x51, 0x2c, 0x01, 0xd6, 0x22, 0x80, 0x1f, 0x66, 0xaa, 0x3f, 0x10, 0x2a, 0xda, 0x19, 0x17,
	0xe3, 0xd6, 0x7d, 0xf0, 0xcc, 0xc4, 0x2e, 0x8b, 0x29, 0x61, 0x18, 0x6e, 0x83, 0x79, 0xa9, 0xf6,
	0x8a, 0xb1, 0x6c, 0xac, 0x3d, 0xb5, 0x75, 0xd5, 0x2e, 0x7d, 0x78, 0x79, 0xab, 0x75, 0xe1, 0xd1,
	0x9f, 0xcd, 0xb9, 0x1f, 0xfe, 0xfd, 0x71, 0xdd, 0x68, 0xab, 0x6b, 0xd6, 0x32, 0x68, 0x08, 0xde,
	0xb7, 0x31, 0xef, 0x08, 0x4f, 0x6f, 0x66, 0x96, 0x76, 0x49, 0x40, 0x75, 0xe4, 0x21, 0x68, 0x56,
	0x22, 0x94, 0x8a, 0x7d, 0x70, 0x31, 0x77, 0xa4, 0xe4, 0x5c, 0x2f, 0x97, 0x93, 0x03, 0xb7, 0xce,
	0x66, 0xba, 0xda, 0x79, 0x0e, 0xcb, 0x02, 0xcb, 0x3a, 0xf2, 0xbb, 0x88, 0xf1, 0x1d, 0x7e, 0x80,
	0x13, 0x9c, 0x46, 0xef, 0x51, 0xe2, 0x61, 0xad, 0xee, 0x0e, 0x58, 0x99, 0x82, 0x51, 0xfa, 0x16,
	0xc1, 0x39, 0x92, 0x6d, 0x08, 0x55, 0x17, 0xda, 0x72, 0x61, 0xad, 0x81, 0xe7, 0xca, 0xae, 0xb6,
	0xfa, 0xd4, 0xfb, 0xbc, 0x33, 0x22, 0x1e, 0xf6, 0x75, 0x90, 0x6d, 0xb0, 0x3a, 0x13, 0x79, 0x1c,
	0xaa, 0x9b, 0x6d, 0x8b, 0x50, 0x67, 0xdb, 0x72, 0x61, 0xdd, 0x38, 0x26, 0xd0, 0x97, 0x77, 0x06,
	0x98, 0xf0, 0xdd, 0x2c, 0x31, 0xde, 0x0f, 0x02, 0x86, 0xb9, 0x8e, 0xd5, 0x02, 0x6b, 0xb3, 0xa1,
	0x2a, 0xd8, 0x12, 0x98, 0xa7, 0x62, 0x47, 0x45, 0x53, 0x2b, 0xeb, 0x13, 0xe0, 0x08, 0x8e, 0x8e,
	0x7e, 0xf8, 0x7b, 0xbe, 0x9f, 0x60, 0xc6, 0xde, 0x4a, 0x68, 0xa4, 0x49, 0xd5, 0x96, 0x0a, 0x0b,
	0x6f, 0x80, 0x4b, 0x58, 0x9d, 0xb8, 0x48, 0x1e, 0xa9, 0xd7, 0xba, 0x88, 0x27, 0x6f, 0x58, 0x2e,
	0x78, 0xa1, 0x3e, 0xbb, 0x52, 0x7a, 0x13, 0x2c, 0x8c, 0xb3, 0x20, 0xc7, 0x7f, 0x89, 0xe5, 0x78,
	0xac, 0x55, 0x70, 0x3d, 0xf7, 0xdc, 0xe2, 0xa5, 0xf7, 0x63, 0x1f, 0x71, 0xbc, 0x17, 0x46, 0xe3,
	0x8f, 0xff, 0xb5, 0x51, 0xf8, 0x84, 0x05, 0xa4, 0x12, 0xf0, 0x29, 0x30, 0xfb, 0x88, 0x71, 0x17,
	0xf3, 0x03, 0x57, 0x7c, 0x13, 0x37, 0x15, 0x20, 0x37, 0x2b, 0x3f, 0x95, 0xad, 0xa6, 0x2d, 0x6b,
	0xd3, 0xd6, 0xb5, 0x69, 0xef, 0xe9, 0xda, 0x6c, 0x9d, 0xcf, 0x52, 0xf4, 0xe1, 0x5f, 0x4d, 0xa3,
	0xbd, 0xd4, 0x2f, 0x8d, 0x94, 0x4f, 0xa7, 0x5d, 0xf2, 0x19, 0xf6, 0x38, 0xf6, 0xf7, 0x86, 0x4c,
	0x3f, 0x94, 0x96, 0xbd, 0x33, 0x99, 0x4e, 0xa5, 0x48, 0x25, 0xdb, 0x04, 0xe7, 0xf5, 0xf3, 0xa8,
	0x6f, 0x3c, 0x5e, 0x6f, 0x7d, 0xff, 0x34, 0x38, 0x27, 0x78, 0xe0, 0x37, 0x06, 0x98, 0x97, 0x25,
	0x0e, 0x6f, 0xda, 0x15, 0x9d, 0xd7, 0x2e, 0x36, 0x15, 0x73, 0xa3, 0x1e, 0x58, 0x6a, 0xb1, 0x56,
	0xbf, 0xfa, 0xe5, 0x9f, 0x6f, 0xcf, 0xac, 0xc0, 0xa6, 0x53, 0x35, 0x01, 0x64, 0x4f, 0x81, 0x3f,
	0x1b, 0x60, 0xa1, 0x50, 0x8c, 0xf0, 0xce, 0xf4, 0x60, 0x53, 0x8a, 0xdc, 0x7c, 0xf5, 0x34, 0x57,
	0x95, 0xea, 0xdb, 0x42, 0xb5, 0x0d, 0x37, 0x2a, 0x55, 0xeb, 0xbc, 0x90, 0xc9, 0x2f, 0x7a, 0x03,
	0xfc, 0xdd, 0x00, 0x97, 0x2b, 0x4a, 0x1d, 0x6e, 0x9f, 0x48, 0x4d, 0xb1, 0x9d, 0x98, 0x6f, 0x9c,
	0x9e, 0x40, 0x99, 0x7a, 0x4d, 0x98, 0x7a, 0x11, 0xde, 0xaa, 0x69, 0x4a, 0x66, 0x3c, 0x93, 0xfa,
	0xff, 0x30, 0xc0, 0x95, 0xaa, 0xd6, 0x02, 0x67, 0x6b, 0x9b, 0xd1, 0xc0, 0xcc, 0x7b, 0xff, 0x83,
	0x41, 0xd9, 0xbb, 0x2b, 0xec, 0xbd, 0x04, 0x6f, 0x57, 0xda, 0x1b, 0x3b, 0xc3, 0x19, 0x87, 0x2b,
	0x06, 0xac, 0x2b, 0xbb, 0x1f, 0xfc, 0xc9, 0x28, 0x8c, 0x23, 0xf8, 0xf2, 0x4c, 0x51, 0xe5, 0xd3,
	0xcf, 0x7c, 0xe5, 0xe4, 0x17, 0x95, 0x89, 0x2d, 0x61, 0x62, 0x03, 0xae, 0x57, 0x9a, 0x28, 0xfc,
	0x13, 0x01, 0xbf, 0x3b, 0x03, 0xae, 0xd5, 0x68, 0xab, 0xf0, 0x9d, 0xe9, 0xaa, 0xea, 0xf7, 0x7d,
	0x73, 0xf7, 0x09, 0x30, 0x29, 0xc3, 0x1f, 0x0b, 0xc3, 0xfb, 0xb0, 0x53, 0x6d, 0x38, 0x3f, 0x02,
	0xdc, 0x20, 0xa1, 0x91, 0x9b, 0x1f, 0x3c, 0xce, 0x17, 0xf9, 0x9d, 0x2f, 0xe1, 0xaf, 0x06, 0x58,
	0x2a, 0x6f, 0xf1, 0xf0, 0xf5, 0xba, 0xe5, 0x54, 0x3e, 0x45, 0xcc, 0xed, 0x53, 0xdf, 0x3f, 0x71,
	0x35, 0x16, 0x47, 0xcf, 0xb8, 0xd3, 0x94, 0x4c, 0x81, 0x9a, 0x9d, 0xa6, 0x7a, 0xd2, 0xd4, 0xec,
	0x34, 0x53, 0x06, 0x50, 0x5d, 0x6f, 0xa1, 0xa2, 0x70, 0xf9, 0x90, 0xb9, 0x1a, 0xd5, 0xba, 0xff,
	0xe8, 0xb0, 0x61, 0x3c, 0x3e, 0x6c, 0x18, 0x7f, 0x1f, 0x36, 0x8c, 0x87, 0x47, 0x8d, 0xb9, 0xc7,
	0x47, 0x8d, 0xb9, 0xdf, 0x8e, 0x1a, 0x73, 0x1f, 0xdd, 0xed, 0x85, 0xfc, 0x20, 0xed, 0xda, 0x1e,
	0x8d, 0x04, 0xf1, 0xf3, 0x21, 0x09, 0x12, 0xc4, 0x78, 0x92, 0x7a, 0x3c, 0x4d, 0xb0, 0xdc, 0x3b,
	0x8e, 0x36, 0xd4, 0xf1, 0xf8, 0x28, 0xc6, 0xac, 0x3b, 0x2f, 0x06, 0xf4, 0xad, 0xff, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xf6, 0xd1, 0x91, 0x4b, 0x8b, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries the LastEthereumNonce.
	LastEthereumNonce(ctx context.Context, in *QueryGetLastEthereumNonceRequest, opts ...grpc.CallOption) (*QueryGetLastEthereumNonceResponse, error)
	// Queries the LastEthereumBlockSynced.
	LastEthereumBlockSynced(ctx context.Context, in *QueryGetLastEthereumBlockSyncedRequest, opts ...grpc.CallOption) (*QueryGetLastEthereumBlockSyncedResponse, error)
	// Queries the EthereumEventIndexOffset.
	EthereumEventIndexOffset(ctx context.Context, in *QueryGetEthereumEventIndexOffsetRequest, opts ...grpc.CallOption) (*QueryGetEthereumEventIndexOffsetResponse, error)
	// Queries the SupplyDeltaInfo.
	SupplyDeltaInfo(ctx context.Context, in *QueryGetSupplyDeltaInfoRequest, opts ...grpc.CallOption) (*QueryGetSupplyDeltaInfoResponse, error)
	// Queries a list of SequencerAddressFromEthereumAddress items.
	SequencerAddressFromEthereumAddress(ctx context.Context, in *QuerySequencerAddressFromEthereumAddressRequest, opts ...grpc.CallOption) (*QuerySequencerAddressFromEthereumAddressResponse, error)
	// Queries the LastEthBlockUpdateTime.
	LastEthBlockUpdateTime(ctx context.Context, in *QueryGetLastEthBlockUpdateTimeRequest, opts ...grpc.CallOption) (*QueryGetLastEthBlockUpdateTimeResponse, error)
	// Queries the LastInjectedTxsSequence.
	LastInjectedTxsSequence(ctx context.Context, in *QueryGetLastInjectedTxsSequenceRequest, opts ...grpc.CallOption) (*QueryGetLastInjectedTxsSequenceResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/fuelsequencer.bridge.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LastEthereumNonce(ctx context.Context, in *QueryGetLastEthereumNonceRequest, opts ...grpc.CallOption) (*QueryGetLastEthereumNonceResponse, error) {
	out := new(QueryGetLastEthereumNonceResponse)
	err := c.cc.Invoke(ctx, "/fuelsequencer.bridge.v1.Query/LastEthereumNonce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LastEthereumBlockSynced(ctx context.Context, in *QueryGetLastEthereumBlockSyncedRequest, opts ...grpc.CallOption) (*QueryGetLastEthereumBlockSyncedResponse, error) {
	out := new(QueryGetLastEthereumBlockSyncedResponse)
	err := c.cc.Invoke(ctx, "/fuelsequencer.bridge.v1.Query/LastEthereumBlockSynced", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EthereumEventIndexOffset(ctx context.Context, in *QueryGetEthereumEventIndexOffsetRequest, opts ...grpc.CallOption) (*QueryGetEthereumEventIndexOffsetResponse, error) {
	out := new(QueryGetEthereumEventIndexOffsetResponse)
	err := c.cc.Invoke(ctx, "/fuelsequencer.bridge.v1.Query/EthereumEventIndexOffset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SupplyDeltaInfo(ctx context.Context, in *QueryGetSupplyDeltaInfoRequest, opts ...grpc.CallOption) (*QueryGetSupplyDeltaInfoResponse, error) {
	out := new(QueryGetSupplyDeltaInfoResponse)
	err := c.cc.Invoke(ctx, "/fuelsequencer.bridge.v1.Query/SupplyDeltaInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SequencerAddressFromEthereumAddress(ctx context.Context, in *QuerySequencerAddressFromEthereumAddressRequest, opts ...grpc.CallOption) (*QuerySequencerAddressFromEthereumAddressResponse, error) {
	out := new(QuerySequencerAddressFromEthereumAddressResponse)
	err := c.cc.Invoke(ctx, "/fuelsequencer.bridge.v1.Query/SequencerAddressFromEthereumAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LastEthBlockUpdateTime(ctx context.Context, in *QueryGetLastEthBlockUpdateTimeRequest, opts ...grpc.CallOption) (*QueryGetLastEthBlockUpdateTimeResponse, error) {
	out := new(QueryGetLastEthBlockUpdateTimeResponse)
	err := c.cc.Invoke(ctx, "/fuelsequencer.bridge.v1.Query/LastEthBlockUpdateTime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LastInjectedTxsSequence(ctx context.Context, in *QueryGetLastInjectedTxsSequenceRequest, opts ...grpc.CallOption) (*QueryGetLastInjectedTxsSequenceResponse, error) {
	out := new(QueryGetLastInjectedTxsSequenceResponse)
	err := c.cc.Invoke(ctx, "/fuelsequencer.bridge.v1.Query/LastInjectedTxsSequence", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries the LastEthereumNonce.
	LastEthereumNonce(context.Context, *QueryGetLastEthereumNonceRequest) (*QueryGetLastEthereumNonceResponse, error)
	// Queries the LastEthereumBlockSynced.
	LastEthereumBlockSynced(context.Context, *QueryGetLastEthereumBlockSyncedRequest) (*QueryGetLastEthereumBlockSyncedResponse, error)
	// Queries the EthereumEventIndexOffset.
	EthereumEventIndexOffset(context.Context, *QueryGetEthereumEventIndexOffsetRequest) (*QueryGetEthereumEventIndexOffsetResponse, error)
	// Queries the SupplyDeltaInfo.
	SupplyDeltaInfo(context.Context, *QueryGetSupplyDeltaInfoRequest) (*QueryGetSupplyDeltaInfoResponse, error)
	// Queries a list of SequencerAddressFromEthereumAddress items.
	SequencerAddressFromEthereumAddress(context.Context, *QuerySequencerAddressFromEthereumAddressRequest) (*QuerySequencerAddressFromEthereumAddressResponse, error)
	// Queries the LastEthBlockUpdateTime.
	LastEthBlockUpdateTime(context.Context, *QueryGetLastEthBlockUpdateTimeRequest) (*QueryGetLastEthBlockUpdateTimeResponse, error)
	// Queries the LastInjectedTxsSequence.
	LastInjectedTxsSequence(context.Context, *QueryGetLastInjectedTxsSequenceRequest) (*QueryGetLastInjectedTxsSequenceResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) LastEthereumNonce(ctx context.Context, req *QueryGetLastEthereumNonceRequest) (*QueryGetLastEthereumNonceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LastEthereumNonce not implemented")
}
func (*UnimplementedQueryServer) LastEthereumBlockSynced(ctx context.Context, req *QueryGetLastEthereumBlockSyncedRequest) (*QueryGetLastEthereumBlockSyncedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LastEthereumBlockSynced not implemented")
}
func (*UnimplementedQueryServer) EthereumEventIndexOffset(ctx context.Context, req *QueryGetEthereumEventIndexOffsetRequest) (*QueryGetEthereumEventIndexOffsetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EthereumEventIndexOffset not implemented")
}
func (*UnimplementedQueryServer) SupplyDeltaInfo(ctx context.Context, req *QueryGetSupplyDeltaInfoRequest) (*QueryGetSupplyDeltaInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SupplyDeltaInfo not implemented")
}
func (*UnimplementedQueryServer) SequencerAddressFromEthereumAddress(ctx context.Context, req *QuerySequencerAddressFromEthereumAddressRequest) (*QuerySequencerAddressFromEthereumAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SequencerAddressFromEthereumAddress not implemented")
}
func (*UnimplementedQueryServer) LastEthBlockUpdateTime(ctx context.Context, req *QueryGetLastEthBlockUpdateTimeRequest) (*QueryGetLastEthBlockUpdateTimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LastEthBlockUpdateTime not implemented")
}
func (*UnimplementedQueryServer) LastInjectedTxsSequence(ctx context.Context, req *QueryGetLastInjectedTxsSequenceRequest) (*QueryGetLastInjectedTxsSequenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LastInjectedTxsSequence not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fuelsequencer.bridge.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LastEthereumNonce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetLastEthereumNonceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LastEthereumNonce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fuelsequencer.bridge.v1.Query/LastEthereumNonce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LastEthereumNonce(ctx, req.(*QueryGetLastEthereumNonceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LastEthereumBlockSynced_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetLastEthereumBlockSyncedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LastEthereumBlockSynced(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fuelsequencer.bridge.v1.Query/LastEthereumBlockSynced",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LastEthereumBlockSynced(ctx, req.(*QueryGetLastEthereumBlockSyncedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EthereumEventIndexOffset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetEthereumEventIndexOffsetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EthereumEventIndexOffset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fuelsequencer.bridge.v1.Query/EthereumEventIndexOffset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EthereumEventIndexOffset(ctx, req.(*QueryGetEthereumEventIndexOffsetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SupplyDeltaInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetSupplyDeltaInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SupplyDeltaInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fuelsequencer.bridge.v1.Query/SupplyDeltaInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SupplyDeltaInfo(ctx, req.(*QueryGetSupplyDeltaInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SequencerAddressFromEthereumAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySequencerAddressFromEthereumAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SequencerAddressFromEthereumAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fuelsequencer.bridge.v1.Query/SequencerAddressFromEthereumAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SequencerAddressFromEthereumAddress(ctx, req.(*QuerySequencerAddressFromEthereumAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LastEthBlockUpdateTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetLastEthBlockUpdateTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LastEthBlockUpdateTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fuelsequencer.bridge.v1.Query/LastEthBlockUpdateTime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LastEthBlockUpdateTime(ctx, req.(*QueryGetLastEthBlockUpdateTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LastInjectedTxsSequence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetLastInjectedTxsSequenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LastInjectedTxsSequence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fuelsequencer.bridge.v1.Query/LastInjectedTxsSequence",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LastInjectedTxsSequence(ctx, req.(*QueryGetLastInjectedTxsSequenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fuelsequencer.bridge.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "LastEthereumNonce",
			Handler:    _Query_LastEthereumNonce_Handler,
		},
		{
			MethodName: "LastEthereumBlockSynced",
			Handler:    _Query_LastEthereumBlockSynced_Handler,
		},
		{
			MethodName: "EthereumEventIndexOffset",
			Handler:    _Query_EthereumEventIndexOffset_Handler,
		},
		{
			MethodName: "SupplyDeltaInfo",
			Handler:    _Query_SupplyDeltaInfo_Handler,
		},
		{
			MethodName: "SequencerAddressFromEthereumAddress",
			Handler:    _Query_SequencerAddressFromEthereumAddress_Handler,
		},
		{
			MethodName: "LastEthBlockUpdateTime",
			Handler:    _Query_LastEthBlockUpdateTime_Handler,
		},
		{
			MethodName: "LastInjectedTxsSequence",
			Handler:    _Query_LastInjectedTxsSequence_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fuelsequencer/bridge/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetSupplyDeltaInfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSupplyDeltaInfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSupplyDeltaInfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetSupplyDeltaInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSupplyDeltaInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSupplyDeltaInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.SupplyDeltaInfo.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetLastEthereumNonceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetLastEthereumNonceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetLastEthereumNonceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetLastEthereumNonceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetLastEthereumNonceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetLastEthereumNonceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Nonce) > 0 {
		i -= len(m.Nonce)
		copy(dAtA[i:], m.Nonce)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Nonce)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetLastEthereumBlockSyncedRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetLastEthereumBlockSyncedRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetLastEthereumBlockSyncedRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetLastEthereumBlockSyncedResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetLastEthereumBlockSyncedResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetLastEthereumBlockSyncedResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Block != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Block))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetEthereumEventIndexOffsetRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetEthereumEventIndexOffsetRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetEthereumEventIndexOffsetRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetEthereumEventIndexOffsetResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetEthereumEventIndexOffsetResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetEthereumEventIndexOffsetResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Offset != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Offset))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QuerySequencerAddressFromEthereumAddressRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySequencerAddressFromEthereumAddressRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySequencerAddressFromEthereumAddressRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EthereumAddress) > 0 {
		i -= len(m.EthereumAddress)
		copy(dAtA[i:], m.EthereumAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.EthereumAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QuerySequencerAddressFromEthereumAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySequencerAddressFromEthereumAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySequencerAddressFromEthereumAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SequencerAddress) > 0 {
		i -= len(m.SequencerAddress)
		copy(dAtA[i:], m.SequencerAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.SequencerAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetLastEthBlockUpdateTimeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetLastEthBlockUpdateTimeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetLastEthBlockUpdateTimeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetLastEthBlockUpdateTimeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetLastEthBlockUpdateTimeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetLastEthBlockUpdateTimeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n3, err3 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.LastEthBlockUpdateTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.LastEthBlockUpdateTime):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintQuery(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetLastInjectedTxsSequenceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetLastInjectedTxsSequenceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetLastInjectedTxsSequenceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetLastInjectedTxsSequenceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetLastInjectedTxsSequenceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetLastInjectedTxsSequenceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Sequence != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Sequence))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetSupplyDeltaInfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetSupplyDeltaInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.SupplyDeltaInfo.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetLastEthereumNonceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetLastEthereumNonceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Nonce)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetLastEthereumBlockSyncedRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetLastEthereumBlockSyncedResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Block != 0 {
		n += 1 + sovQuery(uint64(m.Block))
	}
	return n
}

func (m *QueryGetEthereumEventIndexOffsetRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetEthereumEventIndexOffsetResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Offset != 0 {
		n += 1 + sovQuery(uint64(m.Offset))
	}
	return n
}

func (m *QuerySequencerAddressFromEthereumAddressRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.EthereumAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QuerySequencerAddressFromEthereumAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SequencerAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetLastEthBlockUpdateTimeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetLastEthBlockUpdateTimeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.LastEthBlockUpdateTime)
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetLastInjectedTxsSequenceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetLastInjectedTxsSequenceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Sequence != 0 {
		n += 1 + sovQuery(uint64(m.Sequence))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSupplyDeltaInfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSupplyDeltaInfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSupplyDeltaInfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSupplyDeltaInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSupplyDeltaInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSupplyDeltaInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SupplyDeltaInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SupplyDeltaInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetLastEthereumNonceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetLastEthereumNonceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetLastEthereumNonceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetLastEthereumNonceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetLastEthereumNonceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetLastEthereumNonceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nonce = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetLastEthereumBlockSyncedRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetLastEthereumBlockSyncedRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetLastEthereumBlockSyncedRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetLastEthereumBlockSyncedResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetLastEthereumBlockSyncedResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetLastEthereumBlockSyncedResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Block", wireType)
			}
			m.Block = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Block |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetEthereumEventIndexOffsetRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetEthereumEventIndexOffsetRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetEthereumEventIndexOffsetRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetEthereumEventIndexOffsetResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetEthereumEventIndexOffsetResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetEthereumEventIndexOffsetResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Offset", wireType)
			}
			m.Offset = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Offset |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySequencerAddressFromEthereumAddressRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySequencerAddressFromEthereumAddressRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySequencerAddressFromEthereumAddressRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EthereumAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EthereumAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySequencerAddressFromEthereumAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySequencerAddressFromEthereumAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySequencerAddressFromEthereumAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SequencerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SequencerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetLastEthBlockUpdateTimeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetLastEthBlockUpdateTimeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetLastEthBlockUpdateTimeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetLastEthBlockUpdateTimeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetLastEthBlockUpdateTimeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetLastEthBlockUpdateTimeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastEthBlockUpdateTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.LastEthBlockUpdateTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetLastInjectedTxsSequenceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetLastInjectedTxsSequenceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetLastInjectedTxsSequenceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetLastInjectedTxsSequenceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetLastInjectedTxsSequenceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetLastInjectedTxsSequenceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequence", wireType)
			}
			m.Sequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
