package config

import (
	"errors"
	"time"

	"github.com/fuel-infrastructure/blob-storage/pkg/blobgen"
)

type Profile struct {
	// MaxRate is the maximum rate of bytes/sec that the profiler will try to reach before stopping
	MaxRate int `json:"max_rate"` // bytes/sec
	// Rate is the bytes/sec rate at which of that the profiler will try to match ongoing throughput
	Rate func(since time.Duration) int `json:"rate"` // bytes/sec
	// Size is the total size of all blobs that the profiler intends to have generated by the time since the start
	// This is the integral of the Rate function (area under the curve)
	Size func(since time.Duration) int `json:"size"` // bytes

}

// Config holds the profiler configuration
type Config struct {
	BlobhubURL       string `json:"blobhub_url"`
	SequencerRPC     string `json:"sequencer_rpc"`
	Profile          `json:"profile"`
	BlobDistribution blobgen.BlobSizeDistribution `json:"blob_distribution"`
	MaxLatency       time.Duration                `json:"max_latency"`
	BufferDuration   time.Duration                `json:"buffer_duration"` // Duration as buffer to keep generated blobs before submitting
	BlobTimeout      time.Duration                `json:"blob_timeout"`
	Topic            string                       `json:"topic"`
	Sender           string                       `json:"sender"`
}

// Configuration validation errors
var (
	ErrEmptyBlobhubURL       = errors.New("blobhub URL cannot be empty")
	ErrEmptySequencerRPC     = errors.New("sequencer RPC address cannot be empty")
	ErrNilRateFunction       = errors.New("invalid profile rate function: must be non-nil")
	ErrNilSizeFunction       = errors.New("invalid profile size function: must be non-nil")
	ErrInvalidMaxRate        = errors.New("invalid profile max rate: must be positive")
	ErrInvalidMaxLatency     = errors.New("invalid max latency: must be positive")
	ErrInvalidBufferDuration = errors.New("invalid buffer duration: must be positive")
	ErrInvalidBlobTimeout    = errors.New("invalid blob timeout: must be positive")
)

// Validate checks if the configuration is valid
func (c *Config) Validate() error {
	if c.BlobhubURL == "" {
		return ErrEmptyBlobhubURL
	}
	if c.SequencerRPC == "" {
		return ErrEmptySequencerRPC
	}
	if c.Rate == nil {
		return ErrNilRateFunction
	}
	if c.Size == nil {
		return ErrNilSizeFunction
	}
	if c.MaxRate <= 0 {
		return ErrInvalidMaxRate
	}
	if err := blobgen.ValidateDistribution(c.BlobDistribution); err != nil {
		return err
	}
	if c.MaxLatency <= 0 {
		return ErrInvalidMaxLatency
	}
	if c.BufferDuration <= 0 {
		return ErrInvalidBufferDuration
	}
	if c.BlobTimeout <= 0 {
		return ErrInvalidBlobTimeout
	}
	return nil
}
