package config

import (
	"errors"
	"time"

	"github.com/fuel-infrastructure/blob-storage/pkg/blobgen"
)

// Profile defines the approach of the profiler for the generation of blobs
// - If both Duration and MaxRate are defined, the profile until any condition is reached
// - If Duration is not set, the profile will run until the MaxRate is reached
// -If MaxRate is not set, the profile will run for the duration set by Duration
// - If neither is set, it will run indefinitely
type Profile struct {
	// Duration is the duration the profile is allowed to run for
	time.Duration `json:"duration"`
	// MaxRate is the maximum rate of bytes/sec that the profiler will try to reach before stopping
	MaxRate int `json:"max_rate"` // bytes/sec
	// Rate is the bytes/sec rate at which of that the profiler will try to match ongoing throughput
	Rate func(since time.Duration) int `json:"rate"` // bytes/sec
	// Size is the total size of all blobs that the profiler intends to have generated by the time since the start
	// This is the integral of the Rate function (area under the curve)
	Size func(since time.Duration) int `json:"size"` // bytes

}

// Config holds the profiler configuration
type Config struct {
	BlobhubURL       string                       `json:"blobhub_url"`   // Blobhub URL, the main shared instance for blob storage
	SequencerRPC     string                       `json:"sequencer_rpc"` // Sequencer RPC URL, an instance of the sequencer
	BlobpoolURL      string                       `json:"blobpool_url"`  // Blobpool URL, an instance of the blob-storage server, coupled to the sequencer's blobpool
	ParquetDir       string                       `json:"parquet_dir"`   // Directory to output measurement data as parquet files
	Profile          `json:"profile"`             // Profile configuration, including duration, max rate, rate function, and size function
	BlobDistribution blobgen.BlobSizeDistribution `json:"blob_distribution"` // Blob size distribution, used to generate blobs
	MaxLagRatio      float32                      `json:"max_lag_ratio"`     // When to consider actual throughput as lagging the planned throughput rate
	LagTolerance     time.Duration                `json:"lag_tolerance"`     // How long to tolerate throughput lagging before considering it as a failure
	BufferDuration   time.Duration                `json:"buffer_duration"`   // Duration as buffer to keep generated blobs before submitting
	Topic            string                       `json:"topic"`
	Sender           string                       `json:"sender"`
}

// Configuration validation errors
var (
	ErrEmptyBlobhubURL       = errors.New("blobhub URL cannot be empty")
	ErrEmptySequencerRPC     = errors.New("sequencer RPC address cannot be empty")
	ErrEmptyBlobpoolURL      = errors.New("blobpool URL cannot be empty")
	ErrInvalidDuration       = errors.New("invalid duration: must be positive")
	ErrNilRateFunction       = errors.New("invalid profile rate function: must be non-nil")
	ErrNilSizeFunction       = errors.New("invalid profile size function: must be non-nil")
	ErrInvalidMaxRate        = errors.New("invalid profile max rate: must be positive")
	ErrInvalidMaxLagRatio    = errors.New("invalid max lag ratio: must be positive")
	ErrInvalidLagTolerance   = errors.New("invalid lag tolerance: must be positive")
	ErrInvalidBufferDuration = errors.New("invalid buffer duration: must be positive")
)

// Validate checks if the configuration is valid
func (c *Config) Validate() error {
	if c.BlobhubURL == "" {
		return ErrEmptyBlobhubURL
	}
	if c.SequencerRPC == "" {
		return ErrEmptySequencerRPC
	}
	if c.BlobpoolURL == "" {
		return ErrEmptyBlobpoolURL
	}
	if c.Duration < 0 {
		return ErrInvalidDuration
	}
	if c.MaxRate < 0 {
		return ErrInvalidMaxRate
	}
	if c.Rate == nil {
		return ErrNilRateFunction
	}
	if c.Size == nil {
		return ErrNilSizeFunction
	}
	if c.MaxRate <= 0 {
		return ErrInvalidMaxRate
	}
	if err := blobgen.ValidateDistribution(c.BlobDistribution); err != nil {
		return err
	}
	if c.MaxLagRatio <= 0.0 {
		return ErrInvalidMaxLagRatio
	}
	if c.LagTolerance <= 0 {
		return ErrInvalidLagTolerance
	}
	if c.BufferDuration <= 0 {
		return ErrInvalidBufferDuration
	}
	return nil
}
