syntax = "proto3";

package fuelsequencer.bond.v1;

import "amino/amino.proto";
import "gogoproto/gogo.proto";
import "google/api/annotations.proto";
import "cosmos/base/query/v1beta1/pagination.proto";
import "fuelsequencer/bond/params.proto";
import "fuelsequencer/bond/state.proto";

option go_package = "github.com/fuel-infrastructure/fuel-sequencer/x/bond/types";

// Query defines the gRPC querier service.
service Query {
  // Parameters queries the parameters of the module.
  rpc Params(QueryParamsRequest) returns (QueryParamsResponse) {
    option (google.api.http).get = "/fuelsequencer/bond/v1/params";
  }

  // State queries the state of the module.
  rpc State(QueryStateRequest) returns (QueryStateResponse) {
    option (google.api.http).get = "/fuelsequencer/bond/v1/state";
  }
}

// QueryParamsRequest is request type for the Query/Params RPC method.
message QueryParamsRequest {}

// QueryParamsResponse is response type for the Query/Params RPC method.
message QueryParamsResponse {
  // params holds all the parameters of this module.
  Params params = 1
      [ (gogoproto.nullable) = false, (amino.dont_omitempty) = true ];
}

// QueryStateRequest is request type for the Query/State RPC method.
message QueryStateRequest {}

// QueryStateResponse is response type for the Query/State RPC method.
message QueryStateResponse {
  // state holds the state of this module.
  State state = 1
      [ (gogoproto.nullable) = false, (amino.dont_omitempty) = true ];
}