version: "2"
linters:
  enable:
    - lll
    - govet
    - staticcheck
    - ineffassign
    - unused
    - misspell
  settings:
    lll:
      line-length: 120
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      # NOTE: Regex is RE2 (Golang engine)
      #
      # Exclude paths which should not be linted; generated code, etc.
      - linters:
          - lll  # Don't enforce line length in generated protobuf files
        path: \.pb\.go$
      - linters:
          - lll  # Don't enforce line length in generated protobuf gateway files
        path: \.pb\.gw\.go$
      - linters:
          - lll  # Don't enforce line length in generated pulsar files
        path: \.pulsar\.go$
      - linters:
          - lll  # Don't enforce line length in Contract ABIs
        source: '[A-Za-z][A-Za-z]+ContractABI\s+=\s+`.*`'
      - linters:
          - lll  # Don't enforce line length in Logs (like fixture logs)
        source: '[A-Za-z][A-Za-z]+Logs\s+=\s+`.*`'
      - linters:
          - lll  # Don't enforce line length for hex/base64 data
        source: data(Hex|Base64)\s+:=\s+".*"
      - linters:
          - lll  # Don't enforce line length for hex data
        source: hexData\s+:=\s+".*"
      - linters:
          - lll  # Don't enforce line length for encoded tx data
        source: '\((?:injected|generated): [0-9A-F]+\)'
      - linters:
          - lll  # Don't enforce line length for URLs
        source: .*https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*).*
      - linters:
          - lll  # Don't enforce line length of public struct field instances with 
        source: \s+[A-Z][A-Za-z]+:\s+.*//.*
      - linters:
          - lll  # Don't enforce line length for struct tags
        source: \s+[A-Z][A-Za-z]+\s+.*\s+`.*`
      - linters:
          - lll  # Don't enforce line length for Starport scaffolding comments
        source: '// this line is used by starport scaffolding # stargate/.*'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
