version: 1
build:
  binary: "fuelsequencerd"
  main: ./cmd/fuelsequencerd
accounts:
  - name: alice
    coins:
      - 999996000000utest
    mnemonic: dinner crash nurse casino baby fold race cheese elite column sausage sleep close royal rain over mechanic minimum outdoor conduct cash wagon frog evidence
  - name: validator1
    coins:
      - 2000000utest
    address: fuelsequencer1cv0rl38sckgwyrkdd5vanyzf6v8clf808ttyf4
  - name: validator2
    coins:
      - 2000000utest
    address: fuelsequencer1ddjv8z30raavjc8ku6n6mqlm9rjhezs2u4jetp
client:
  openapi:
    path: docs/static/openapi.yml
validators:
  - name: alice
    bonded: 1000000utest
    config:
      consensus:
        timeout_propose: "1s"
        timeout_commit: "2s"
    home: ./data/fuelsequencer
genesis:
  genesis_time: "2024-04-19T08:00:00.000000Z"
  chain_id: "seq-devnet-1"
  consensus:
    params:
      block:
        max_bytes: "22020096"
        max_gas: "300000000"
  app_state:
    crisis:
      constant_fee:
        amount: "1000"
        denom: "utest"
    gov:
      params:
        voting_period: "10800s"
        expedited_voting_period: "3600s"
        min_deposit:
          - amount: "1000"
            denom: "utest"
        expedited_min_deposit:
          - amount: "2000"
            denom: "utest"
    mint:
      params:
        mint_denom: "utest"
    slashing:
      params:
        downtime_jail_duration: "14400s"
    staking:
      params:
        bond_denom: "utest"
        unbonding_time: "86400s"
        max_validators: 10
    bridge:
      params:
        bridge_denom: "utest"
        ethereum_proxy_contract_address: "0x44D4EB47eC1A511B58fe50399d57A6bc1D88f136"
        authorize_messages_allowed:
          - "*"  # allow all
        supply_delta_period: 1000
      last_ethereum_nonce: "0"
      last_ethereum_block_synced: "0"
    sequencing:
      params:
        max_blob_size_bytes: 1000000
