version: 1
build:
  binary: fuelsequencerd
  main: ./cmd/fuelsequencerd
accounts:
  - name: alice
    coins:
      - 200000000utest
    mnemonic: dinner crash nurse casino baby fold race cheese elite column sausage sleep close royal rain over mechanic minimum outdoor conduct cash wagon frog evidence
    # fuelsequencer1vtfzrk6f4m6kxt6ehyqt9j5su5hvcz5q3dmlsm
  - name: bob
    coins:
      - 100000000utest
    mnemonic: gaze drama excess raven follow antenna swallow beef upper myself question pitch course ill adult century crisp ice rough match praise sing unveil vintage
    # fuelsequencer163rsv65t4893t2rz5rmda9sly7lgdlq2jgr36m
  - name: carol
    coins:
      - 1000000000000000utest
    mnemonic: bar describe panda mosquito quiz room daring round nurse disagree swallow frown hat repeat recall flight skin sketch volume dutch range grunt assist nerve
    # fuelsequencer1n79wsstpakv0gw2efmruf9x8xs9m4rqfazfu8g
  - name: dexter
    coins:
      - 1000000000000000utest
    mnemonic: bonus clinic owner choose grief soda ride divorce album oval tone mixed mechanic coin defense wonder tumble vault sorry great hover neither security amazing
    # fuelsequencer1r8aaf8fjcft7h7tupnafyv0kzk0342gnjls2pu
validators:
  - name: alice
    bonded: 100000000utest
    home: ./data/fuelsequencer
    app:
      api:
        swagger: true
      grpc:
        address: 0.0.0.0:9090
  - name: bob
    bonded: 50000000utest
    home: ./data/fuelsequencer
    app:
      api:
        swagger: true
      grpc:
        address: 0.0.0.0:9090
genesis:
  app_version: "seq-sandbox-1"  # manually overridden for a more meaningful app version
  genesis_time: "2024-07-15T00:00:00Z"
  chain_id: "seq-sandbox-1"
  app_state:
    bridge:
      params:
        bridge_denom: "utest"  # for testnet purposes
        bridge_denom_total_supply: "10000000000000000000000000000"
        ethereum_proxy_contract_address: "0xeAaE78314aC1208ADF5799c47F91372392E407E1"
        supply_delta_period: "14400"
        vesting_start_time: "2023-07-17T00:00:00Z"
        max_eth_block_update_delay: "14400s"
        injected_event_tx_max_bytes: "1900000"
        max_authorize_messages: "5"
      last_ethereum_block_synced: "6321400"
    distribution:
      params:
        community_tax: "0.000000000000000000"
    gov:
      params:
        min_deposit:
          - amount: "2500000000000000000000"
            denom: "utest"  # for testnet purposes
        max_deposit_period: "604800s"
        voting_period: "60s"  # 1 minute for testnet purposes
        quorum: "0.400000000000000000"
        min_initial_deposit_ratio: "0.100000000000000000"
        expedited_min_deposit:
          - amount: "10000000000000000000000"
            denom: "utest"  # for testnet purposes
        proposal_cancel_ratio: "0.000000000000000000"
        proposal_cancel_dest: "fuelsequencer10d07y265gmmuvt4z0w9aw880jnsr700jdjfvk3"  # gov
        expedited_voting_period: "30s"  # 30 seconds for testnet purposes
        burn_vote_veto: false
    mint:
      minter:
        inflation: "0.060000000000000000"
      params:
        mint_denom: "utest"  # for testnet purposes
        inflation_rate_change: "0.000000000000000000"
        inflation_max: "0.060000000000000000"
        inflation_min: "0.060000000000000000"
        blocks_per_year: "5259600"  # assuming a block time of 6s
    sequencing:
      params:
        max_blob_size_bytes: "1048576"
        sequencer_tx_max_bytes: "1572864"
    slashing:
      params:
        signed_blocks_window: "10000"  # for testnet purposes
        min_signed_per_window: "0.050000000000000000"  # for testnet purposes
        downtime_jail_duration: "600s"  # for testnet purposes
        slash_fraction_double_sign: "0.050000000000000000"  # for testnet purposes
        slash_fraction_downtime: "0.000100000000000000"  # for testnet purposes
    staking:
      params:
        bond_denom: "utest"  # for testnet purposes
        unbonding_time: "86400s"  # for testnet purposes
        max_validators: "100"
        min_commission_rate: "0.050000000000000000"
  consensus:
    params:
      block:
        max_bytes: "2000000"
        max_gas: "100000000"
