version: 1
build:
  binary: fuelsequencerd
  main: ./cmd/fuelsequencerd
accounts:
  - name: alice
    mnemonic: dinner crash nurse casino baby fold race cheese elite column sausage sleep close royal rain over mechanic minimum outdoor conduct cash wagon frog evidence
    coins:
      - 9999760000000000000000000000test
validators:
  - name: alice
    bonded: 1000000test
    home: ./data/fuelsequencer
    app:
      sidecar:
        enabled: false  # to be able to run this config file more easily
genesis:
  app_version: "seq-testnet-1"  # manually overridden for a more meaningful app version
  genesis_time: "2024-09-26T10:00:00Z"
  chain_id: "seq-testnet-1"
  app_state:
    bridge:
      params:
        bridge_denom: "test"  # for testnet purposes
        bridge_denom_total_supply: "10000000000000000000000000000"
        ethereum_proxy_contract_address: "TODO"  # https://sepolia.etherscan.io/address/TODO
        supply_delta_period: "14400"
        vesting_start_time: "2023-09-29T10:00:00Z"
        max_eth_block_update_delay: "14400s"
        injected_event_tx_max_bytes: "1900000"
        max_authorize_messages: "5"
      last_ethereum_block_synced: "TODO"  # 1 block before deployment of Sequencer Proxy Contract (https://sepolia.etherscan.io/address/TODO)
    distribution:
      params:
        community_tax: "0.000000000000000000"
    gov:
      params:
        min_deposit:
          - amount: "2500000000000000000000"
            denom: "test"  # for testnet purposes
        max_deposit_period: "604800s"
        voting_period: "10800s"  # 3 hours for testnet purposes
        quorum: "0.400000000000000000"
        min_initial_deposit_ratio: "0.100000000000000000"
        expedited_min_deposit:
          - amount: "10000000000000000000000"
            denom: "test"  # for testnet purposes
        proposal_cancel_ratio: "0.000000000000000000"
        proposal_cancel_dest: "fuelsequencer10d07y265gmmuvt4z0w9aw880jnsr700jdjfvk3"  # gov
        expedited_voting_period: "3600s"
        burn_vote_veto: false
    mint:
      params:
        mint_denom: "test"  # for testnet purposes
        inflation_rate_change: "0.000000000000000000"
        inflation_max: "0.060000000000000000"
        inflation_min: "0.060000000000000000"
        blocks_per_year: "5259600"  # assuming a block time of 6s
    sequencing:
      params:
        max_blob_size_bytes: "2097152"  # 2MiB
        sequencer_tx_max_bytes: "2097152"  # 2MiB
    slashing:
      params:
        signed_blocks_window: "10000"  # for testnet purposes
        min_signed_per_window: "0.050000000000000000"  # for testnet purposes
        downtime_jail_duration: "600s"  # for testnet purposes
        slash_fraction_double_sign: "0.050000000000000000"  # for testnet purposes
        slash_fraction_downtime: "0.000100000000000000"  # for testnet purposes
    staking:
      params:
        bond_denom: "test"  # for testnet purposes
        unbonding_time: "86400s"  # for testnet purposes
        max_validators: "12"
        min_commission_rate: "0.050000000000000000"
  consensus:
    params:
      block:
        max_bytes: "3145728"  # 3MiB
        max_gas: "100000000"
