syntax = "proto3";
package fuelsequencer.sequencing;

import "amino/amino.proto";
import "gogoproto/gogo.proto";

option go_package = "github.com/fuel-infrastructure/fuel-sequencer/x/sequencing/types";

// Params defines the parameters for the module.
message Params {
  option (amino.name) = "fuelsequencer/x/sequencing/Params";
  option (gogoproto.equal) = true;

  // max_blob_size_bytes is the maximum size of blob that can be submitted in
  // bytes.
  uint64 max_blob_size_bytes = 1;

  // sequencer_tx_max_bytes specifies the maximum size, in bytes, that
  // Sequencer-native transactions can be. Sequencer-native transactions
  // with size bigger than this limit will get automatically rejected.
  // This is done to avoid having large transactions sitting in the
  // mempool forever due to never having enough block space. This happens
  // when size(tx) > RequestPrepareProposal.MaxBytes - size(MsgIndexTx).
  uint64 sequencer_tx_max_bytes = 2;
}
