// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fuelsequencer/reports/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_936212240f12383c, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_936212240f12383c, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryGetSlashReportRequest is request type for the Query/GetSlashReport RPC
// method.
type QueryGetSlashReportRequest struct {
	// the height of the slashing report to query from state
	Height uint64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *QueryGetSlashReportRequest) Reset()         { *m = QueryGetSlashReportRequest{} }
func (m *QueryGetSlashReportRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetSlashReportRequest) ProtoMessage()    {}
func (*QueryGetSlashReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_936212240f12383c, []int{2}
}
func (m *QueryGetSlashReportRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSlashReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSlashReportRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSlashReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSlashReportRequest.Merge(m, src)
}
func (m *QueryGetSlashReportRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSlashReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSlashReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSlashReportRequest proto.InternalMessageInfo

func (m *QueryGetSlashReportRequest) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

// QueryGetSlashReportResponse is response type for the Query/GetSlashReport RPC
// method.
type QueryGetSlashReportResponse struct {
	// slash_report holds the slashing report queried by height
	SlashReport SlashReport `protobuf:"bytes,1,opt,name=slash_report,json=slashReport,proto3" json:"slash_report"`
}

func (m *QueryGetSlashReportResponse) Reset()         { *m = QueryGetSlashReportResponse{} }
func (m *QueryGetSlashReportResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetSlashReportResponse) ProtoMessage()    {}
func (*QueryGetSlashReportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_936212240f12383c, []int{3}
}
func (m *QueryGetSlashReportResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSlashReportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSlashReportResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSlashReportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSlashReportResponse.Merge(m, src)
}
func (m *QueryGetSlashReportResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSlashReportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSlashReportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSlashReportResponse proto.InternalMessageInfo

func (m *QueryGetSlashReportResponse) GetSlashReport() SlashReport {
	if m != nil {
		return m.SlashReport
	}
	return SlashReport{}
}

// QueryAllSlashReportRequest is request type for the Query/AllSlashReport RPC
// method.
type QueryAllSlashReportRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllSlashReportRequest) Reset()         { *m = QueryAllSlashReportRequest{} }
func (m *QueryAllSlashReportRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllSlashReportRequest) ProtoMessage()    {}
func (*QueryAllSlashReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_936212240f12383c, []int{4}
}
func (m *QueryAllSlashReportRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllSlashReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllSlashReportRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllSlashReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllSlashReportRequest.Merge(m, src)
}
func (m *QueryAllSlashReportRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllSlashReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllSlashReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllSlashReportRequest proto.InternalMessageInfo

func (m *QueryAllSlashReportRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryAllSlashReportResponse is response type for the Query/AllSlashReport RPC
// method.
type QueryAllSlashReportResponse struct {
	// slash_report holds all the slashing reports stored in state
	SlashReport []SlashReport       `protobuf:"bytes,1,rep,name=slash_report,json=slashReport,proto3" json:"slash_report"`
	Pagination  *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllSlashReportResponse) Reset()         { *m = QueryAllSlashReportResponse{} }
func (m *QueryAllSlashReportResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllSlashReportResponse) ProtoMessage()    {}
func (*QueryAllSlashReportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_936212240f12383c, []int{5}
}
func (m *QueryAllSlashReportResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllSlashReportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllSlashReportResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllSlashReportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllSlashReportResponse.Merge(m, src)
}
func (m *QueryAllSlashReportResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllSlashReportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllSlashReportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllSlashReportResponse proto.InternalMessageInfo

func (m *QueryAllSlashReportResponse) GetSlashReport() []SlashReport {
	if m != nil {
		return m.SlashReport
	}
	return nil
}

func (m *QueryAllSlashReportResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryGetSlashEntryRequest is request type for the Query/GetSlashEntry RPC
// method.
type QueryGetSlashEntryRequest struct {
	// the height of the slashing entry to query from state
	Height uint64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	// address of the delegator delegating to the slashed validator
	DelegatorAddress string `protobuf:"bytes,2,opt,name=delegator_address,json=delegatorAddress,proto3" json:"delegator_address,omitempty"`
	// address of the validator that has been slashed
	ValidatorAddress string `protobuf:"bytes,3,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
}

func (m *QueryGetSlashEntryRequest) Reset()         { *m = QueryGetSlashEntryRequest{} }
func (m *QueryGetSlashEntryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetSlashEntryRequest) ProtoMessage()    {}
func (*QueryGetSlashEntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_936212240f12383c, []int{6}
}
func (m *QueryGetSlashEntryRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSlashEntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSlashEntryRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSlashEntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSlashEntryRequest.Merge(m, src)
}
func (m *QueryGetSlashEntryRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSlashEntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSlashEntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSlashEntryRequest proto.InternalMessageInfo

func (m *QueryGetSlashEntryRequest) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *QueryGetSlashEntryRequest) GetDelegatorAddress() string {
	if m != nil {
		return m.DelegatorAddress
	}
	return ""
}

func (m *QueryGetSlashEntryRequest) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

// QueryGetSlashEntryResponse is response type for the Query/GetSlashEntry RPC
// method.
type QueryGetSlashEntryResponse struct {
	// slash_entry holds the slashing entry queried by height, delegator, and
	// validator
	SlashEntry SlashEntry `protobuf:"bytes,1,opt,name=slash_entry,json=slashEntry,proto3" json:"slash_entry"`
}

func (m *QueryGetSlashEntryResponse) Reset()         { *m = QueryGetSlashEntryResponse{} }
func (m *QueryGetSlashEntryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetSlashEntryResponse) ProtoMessage()    {}
func (*QueryGetSlashEntryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_936212240f12383c, []int{7}
}
func (m *QueryGetSlashEntryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSlashEntryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSlashEntryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSlashEntryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSlashEntryResponse.Merge(m, src)
}
func (m *QueryGetSlashEntryResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSlashEntryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSlashEntryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSlashEntryResponse proto.InternalMessageInfo

func (m *QueryGetSlashEntryResponse) GetSlashEntry() SlashEntry {
	if m != nil {
		return m.SlashEntry
	}
	return SlashEntry{}
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "fuelsequencer.reports.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "fuelsequencer.reports.v1.QueryParamsResponse")
	proto.RegisterType((*QueryGetSlashReportRequest)(nil), "fuelsequencer.reports.v1.QueryGetSlashReportRequest")
	proto.RegisterType((*QueryGetSlashReportResponse)(nil), "fuelsequencer.reports.v1.QueryGetSlashReportResponse")
	proto.RegisterType((*QueryAllSlashReportRequest)(nil), "fuelsequencer.reports.v1.QueryAllSlashReportRequest")
	proto.RegisterType((*QueryAllSlashReportResponse)(nil), "fuelsequencer.reports.v1.QueryAllSlashReportResponse")
	proto.RegisterType((*QueryGetSlashEntryRequest)(nil), "fuelsequencer.reports.v1.QueryGetSlashEntryRequest")
	proto.RegisterType((*QueryGetSlashEntryResponse)(nil), "fuelsequencer.reports.v1.QueryGetSlashEntryResponse")
}

func init() {
	proto.RegisterFile("fuelsequencer/reports/v1/query.proto", fileDescriptor_936212240f12383c)
}

var fileDescriptor_936212240f12383c = []byte{
	// 704 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x95, 0xdf, 0x6a, 0x13, 0x4f,
	0x14, 0xc7, 0xb3, 0xfd, 0x13, 0xe8, 0xf4, 0xc7, 0x0f, 0x3b, 0x16, 0x69, 0xa3, 0x8d, 0xed, 0x22,
	0xb6, 0x16, 0xb3, 0x43, 0xda, 0x8a, 0x57, 0x82, 0x0d, 0xd4, 0x0a, 0x82, 0xd4, 0x2d, 0x58, 0xf4,
	0x26, 0x4c, 0x92, 0xe9, 0x66, 0x65, 0xb3, 0xb3, 0x9d, 0x99, 0x04, 0x4b, 0xe9, 0x8d, 0x2f, 0xa0,
	0xe0, 0x4b, 0x78, 0x25, 0x42, 0xfb, 0x10, 0xc5, 0xab, 0x52, 0x6f, 0x0a, 0x82, 0x48, 0x2b, 0xf8,
	0x1a, 0xb2, 0x33, 0xa7, 0xcd, 0x26, 0xdd, 0x98, 0xd6, 0x9b, 0x90, 0x3d, 0x39, 0xdf, 0x73, 0x3e,
	0xe7, 0xdf, 0x06, 0xdd, 0xd9, 0x6c, 0xb2, 0x40, 0xb2, 0xad, 0x26, 0x0b, 0xab, 0x4c, 0x10, 0xc1,
	0x22, 0x2e, 0x94, 0x24, 0xad, 0x22, 0xd9, 0x6a, 0x32, 0xb1, 0xed, 0x44, 0x82, 0x2b, 0x8e, 0x27,
	0x3a, 0xbc, 0x1c, 0xf0, 0x72, 0x5a, 0xc5, 0xdc, 0x64, 0x95, 0xcb, 0x06, 0x97, 0x65, 0xed, 0x47,
	0xcc, 0x83, 0x11, 0xe5, 0xc6, 0x68, 0xc3, 0x0f, 0x39, 0xd1, 0x9f, 0x60, 0x1a, 0xf7, 0xb8, 0xc7,
	0x8d, 0x6b, 0xfc, 0x0d, 0xac, 0xb7, 0x3c, 0xce, 0xbd, 0x80, 0x11, 0x1a, 0xf9, 0x84, 0x86, 0x21,
	0x57, 0x54, 0xf9, 0x3c, 0x3c, 0x0b, 0x33, 0x6f, 0x82, 0x92, 0x0a, 0x95, 0xcc, 0x40, 0x91, 0x56,
	0xb1, 0xc2, 0x14, 0x2d, 0x92, 0x88, 0x7a, 0x7e, 0xa8, 0x9d, 0xc1, 0xd7, 0x4e, 0xaf, 0x26, 0xa2,
	0x82, 0x36, 0xce, 0xe2, 0xcd, 0xa5, 0xfb, 0xc8, 0x80, 0xca, 0x7a, 0xd9, 0x3c, 0x19, 0x4f, 0x7b,
	0x1c, 0xe1, 0x17, 0x71, 0xbe, 0x35, 0x2d, 0x77, 0x63, 0x89, 0x54, 0xf6, 0x06, 0xba, 0xde, 0x61,
	0x95, 0x11, 0x0f, 0x25, 0xc3, 0x8f, 0x51, 0xd6, 0xa4, 0x99, 0xb0, 0xa6, 0xad, 0xb9, 0xd1, 0x85,
	0x29, 0x27, 0xbd, 0x67, 0x46, 0x56, 0x1a, 0x39, 0xf8, 0x71, 0x3b, 0xf3, 0xe9, 0xf7, 0x97, 0x79,
	0xcb, 0x05, 0x9d, 0xbd, 0x84, 0x72, 0x3a, 0xf0, 0x2a, 0x53, 0xeb, 0x31, 0x8c, 0xab, 0x15, 0x90,
	0x16, 0xdf, 0x40, 0xd9, 0x3a, 0xf3, 0xbd, 0xba, 0xd2, 0xf1, 0x87, 0x5c, 0x78, 0xb2, 0xdf, 0xa0,
	0x9b, 0xa9, 0x2a, 0xc0, 0x7a, 0x86, 0xfe, 0x4b, 0x56, 0x06, 0x70, 0x76, 0x0f, 0xb8, 0x44, 0x84,
	0xd2, 0x50, 0x4c, 0xe8, 0x8e, 0xca, 0xb6, 0xc9, 0xae, 0x01, 0xe1, 0x72, 0x10, 0xa4, 0x10, 0x3e,
	0x41, 0xa8, 0x3d, 0x10, 0x48, 0x74, 0xd7, 0x81, 0x95, 0x88, 0xa7, 0xe7, 0x98, 0x95, 0x82, 0xe9,
	0x39, 0x6b, 0xd4, 0x63, 0xa0, 0x75, 0x13, 0x4a, 0x7b, 0xcf, 0x82, 0x92, 0xba, 0xd3, 0xf4, 0x2c,
	0x69, 0xf0, 0x9f, 0x4b, 0xc2, 0xab, 0x1d, 0xd0, 0x03, 0x1a, 0x7a, 0xb6, 0x2f, 0xb4, 0x21, 0xe9,
	0xa0, 0xfe, 0x6a, 0xa1, 0xc9, 0x8e, 0x41, 0xac, 0x84, 0x4a, 0x6c, 0xf7, 0x99, 0x1e, 0x5e, 0x41,
	0x63, 0x35, 0x16, 0x30, 0x8f, 0x2a, 0x2e, 0xca, 0xb4, 0x56, 0x13, 0x4c, 0x4a, 0x4d, 0x31, 0x52,
	0x9a, 0x38, 0xda, 0x2f, 0x8c, 0x03, 0xc8, 0xb2, 0xf9, 0x65, 0x5d, 0x09, 0x3f, 0xf4, 0xdc, 0x6b,
	0xe7, 0x12, 0xb0, 0xe3, 0xe7, 0x68, 0xac, 0x45, 0x03, 0xbf, 0xd6, 0x11, 0x66, 0x50, 0x87, 0x99,
	0x39, 0xda, 0x2f, 0x4c, 0x41, 0x98, 0x97, 0x67, 0x3e, 0x5d, 0xf1, 0x5a, 0x5d, 0x76, 0x7b, 0xb3,
	0x6b, 0x15, 0xa1, 0x16, 0x18, 0xc0, 0x53, 0x64, 0x5a, 0x58, 0x66, 0xb1, 0x19, 0x26, 0x3d, 0xf3,
	0xb7, 0xfe, 0x6b, 0x3d, 0xb4, 0x1f, 0xc9, 0x73, 0xcb, 0xc2, 0xf7, 0x61, 0x34, 0xac, 0x13, 0xe1,
	0xf7, 0x16, 0xca, 0x9a, 0xd3, 0xc0, 0xf7, 0x9d, 0x5e, 0x6f, 0x1b, 0xe7, 0xe2, 0x39, 0xe6, 0x0a,
	0x97, 0xf4, 0x36, 0xec, 0xf6, 0xdc, 0xbb, 0x6f, 0xbf, 0x3e, 0x0e, 0xd8, 0x78, 0x9a, 0xf4, 0x7c,
	0xf1, 0x99, 0x73, 0xc4, 0x7b, 0x16, 0x1a, 0x4d, 0x2c, 0x0f, 0x5e, 0xea, 0x93, 0x28, 0xf5, 0x6c,
	0x73, 0x0f, 0xae, 0xa8, 0x02, 0xcc, 0x87, 0x1a, 0xb3, 0x88, 0x49, 0x6f, 0xcc, 0xe4, 0x0d, 0x90,
	0x1d, 0xb3, 0x4f, 0xbb, 0xf8, 0xb3, 0x85, 0xfe, 0x4f, 0x04, 0x5c, 0x0e, 0x82, 0xbe, 0xe0, 0xa9,
	0xd7, 0xdc, 0x17, 0x3c, 0xfd, 0x38, 0x6d, 0xa2, 0xc1, 0xef, 0xe1, 0xd9, 0xcb, 0x81, 0x4b, 0x7c,
	0x6c, 0x21, 0xd4, 0xde, 0x11, 0xbc, 0x78, 0xc9, 0x7e, 0x25, 0xaf, 0x2b, 0xb7, 0x74, 0x35, 0x11,
	0xa0, 0x96, 0x35, 0xea, 0x2b, 0xbc, 0x71, 0xc5, 0x1e, 0x93, 0x9d, 0x0b, 0x27, 0xbb, 0x4b, 0x76,
	0x2e, 0xdc, 0xdf, 0x6e, 0x69, 0xe3, 0xe0, 0x24, 0x6f, 0x1d, 0x9e, 0xe4, 0xad, 0x9f, 0x27, 0x79,
	0xeb, 0xc3, 0x69, 0x3e, 0x73, 0x78, 0x9a, 0xcf, 0x1c, 0x9f, 0xe6, 0x33, 0xaf, 0x1f, 0x79, 0xbe,
	0xaa, 0x37, 0x2b, 0x4e, 0x95, 0x37, 0x74, 0xf2, 0x82, 0x1f, 0x6e, 0x0a, 0x2a, 0x95, 0x68, 0x56,
	0x55, 0x53, 0x30, 0x63, 0x6b, 0x13, 0xbd, 0x3d, 0x67, 0x52, 0xdb, 0x11, 0x93, 0x95, 0xac, 0xfe,
	0x7f, 0x5a, 0xfc, 0x13, 0x00, 0x00, 0xff, 0xff, 0xbd, 0xad, 0x10, 0x58, 0xbd, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a slashing report by height.
	SlashReport(ctx context.Context, in *QueryGetSlashReportRequest, opts ...grpc.CallOption) (*QueryGetSlashReportResponse, error)
	// Queries all slashing reports in state.
	SlashReportAll(ctx context.Context, in *QueryAllSlashReportRequest, opts ...grpc.CallOption) (*QueryAllSlashReportResponse, error)
	// Queries a slashing entry by height, delegator, and validator.
	SlashEntry(ctx context.Context, in *QueryGetSlashEntryRequest, opts ...grpc.CallOption) (*QueryGetSlashEntryResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/fuelsequencer.reports.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SlashReport(ctx context.Context, in *QueryGetSlashReportRequest, opts ...grpc.CallOption) (*QueryGetSlashReportResponse, error) {
	out := new(QueryGetSlashReportResponse)
	err := c.cc.Invoke(ctx, "/fuelsequencer.reports.v1.Query/SlashReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SlashReportAll(ctx context.Context, in *QueryAllSlashReportRequest, opts ...grpc.CallOption) (*QueryAllSlashReportResponse, error) {
	out := new(QueryAllSlashReportResponse)
	err := c.cc.Invoke(ctx, "/fuelsequencer.reports.v1.Query/SlashReportAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SlashEntry(ctx context.Context, in *QueryGetSlashEntryRequest, opts ...grpc.CallOption) (*QueryGetSlashEntryResponse, error) {
	out := new(QueryGetSlashEntryResponse)
	err := c.cc.Invoke(ctx, "/fuelsequencer.reports.v1.Query/SlashEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a slashing report by height.
	SlashReport(context.Context, *QueryGetSlashReportRequest) (*QueryGetSlashReportResponse, error)
	// Queries all slashing reports in state.
	SlashReportAll(context.Context, *QueryAllSlashReportRequest) (*QueryAllSlashReportResponse, error)
	// Queries a slashing entry by height, delegator, and validator.
	SlashEntry(context.Context, *QueryGetSlashEntryRequest) (*QueryGetSlashEntryResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) SlashReport(ctx context.Context, req *QueryGetSlashReportRequest) (*QueryGetSlashReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SlashReport not implemented")
}
func (*UnimplementedQueryServer) SlashReportAll(ctx context.Context, req *QueryAllSlashReportRequest) (*QueryAllSlashReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SlashReportAll not implemented")
}
func (*UnimplementedQueryServer) SlashEntry(ctx context.Context, req *QueryGetSlashEntryRequest) (*QueryGetSlashEntryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SlashEntry not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fuelsequencer.reports.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SlashReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetSlashReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SlashReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fuelsequencer.reports.v1.Query/SlashReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SlashReport(ctx, req.(*QueryGetSlashReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SlashReportAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllSlashReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SlashReportAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fuelsequencer.reports.v1.Query/SlashReportAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SlashReportAll(ctx, req.(*QueryAllSlashReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SlashEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetSlashEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SlashEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fuelsequencer.reports.v1.Query/SlashEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SlashEntry(ctx, req.(*QueryGetSlashEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fuelsequencer.reports.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "SlashReport",
			Handler:    _Query_SlashReport_Handler,
		},
		{
			MethodName: "SlashReportAll",
			Handler:    _Query_SlashReportAll_Handler,
		},
		{
			MethodName: "SlashEntry",
			Handler:    _Query_SlashEntry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fuelsequencer/reports/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetSlashReportRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSlashReportRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSlashReportRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Height != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetSlashReportResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSlashReportResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSlashReportResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.SlashReport.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllSlashReportRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllSlashReportRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllSlashReportRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllSlashReportResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllSlashReportResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllSlashReportResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.SlashReport) > 0 {
		for iNdEx := len(m.SlashReport) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SlashReport[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetSlashEntryRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSlashEntryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSlashEntryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.DelegatorAddress) > 0 {
		i -= len(m.DelegatorAddress)
		copy(dAtA[i:], m.DelegatorAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.DelegatorAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.Height != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetSlashEntryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSlashEntryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSlashEntryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.SlashEntry.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetSlashReportRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovQuery(uint64(m.Height))
	}
	return n
}

func (m *QueryGetSlashReportResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.SlashReport.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllSlashReportRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllSlashReportResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.SlashReport) > 0 {
		for _, e := range m.SlashReport {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetSlashEntryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovQuery(uint64(m.Height))
	}
	l = len(m.DelegatorAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetSlashEntryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.SlashEntry.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSlashReportRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSlashReportRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSlashReportRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSlashReportResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSlashReportResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSlashReportResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashReport", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SlashReport.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllSlashReportRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllSlashReportRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllSlashReportRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllSlashReportResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllSlashReportResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllSlashReportResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashReport", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SlashReport = append(m.SlashReport, SlashReport{})
			if err := m.SlashReport[len(m.SlashReport)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSlashEntryRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSlashEntryRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSlashEntryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DelegatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSlashEntryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSlashEntryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSlashEntryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashEntry", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SlashEntry.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
