// Code generated by MockGen. DO NOT EDIT.
// Source: x/mint/types/expected_keepers.go

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"

	types "github.com/cosmos/cosmos-sdk/types"
	types0 "github.com/fuel-infrastructure/fuel-sequencer/x/bond/types"
	types1 "github.com/fuel-infrastructure/fuel-sequencer/x/bridge/types"
	gomock "github.com/golang/mock/gomock"
)

// MockBridgeKeeper is a mock of BridgeKeeper interface.
type MockBridgeKeeper struct {
	ctrl     *gomock.Controller
	recorder *MockBridgeKeeperMockRecorder
}

// MockBridgeKeeperMockRecorder is the mock recorder for MockBridgeKeeper.
type MockBridgeKeeperMockRecorder struct {
	mock *MockBridgeKeeper
}

// NewMockBridgeKeeper creates a new mock instance.
func NewMockBridgeKeeper(ctrl *gomock.Controller) *MockBridgeKeeper {
	mock := &MockBridgeKeeper{ctrl: ctrl}
	mock.recorder = &MockBridgeKeeperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBridgeKeeper) EXPECT() *MockBridgeKeeperMockRecorder {
	return m.recorder
}

// GetParams mocks base method.
func (m *MockBridgeKeeper) GetParams(ctx context.Context) types1.Params {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParams", ctx)
	ret0, _ := ret[0].(types1.Params)
	return ret0
}

// GetParams indicates an expected call of GetParams.
func (mr *MockBridgeKeeperMockRecorder) GetParams(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParams", reflect.TypeOf((*MockBridgeKeeper)(nil).GetParams), ctx)
}

// MockBondKeeper is a mock of BondKeeper interface.
type MockBondKeeper struct {
	ctrl     *gomock.Controller
	recorder *MockBondKeeperMockRecorder
}

// MockBondKeeperMockRecorder is the mock recorder for MockBondKeeper.
type MockBondKeeperMockRecorder struct {
	mock *MockBondKeeper
}

// NewMockBondKeeper creates a new mock instance.
func NewMockBondKeeper(ctrl *gomock.Controller) *MockBondKeeper {
	mock := &MockBondKeeper{ctrl: ctrl}
	mock.recorder = &MockBondKeeperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBondKeeper) EXPECT() *MockBondKeeperMockRecorder {
	return m.recorder
}

// AddCollectedBondStake mocks base method.
func (m *MockBondKeeper) AddCollectedBondStake(ctx context.Context, bond types.Coins) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCollectedBondStake", ctx, bond)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCollectedBondStake indicates an expected call of AddCollectedBondStake.
func (mr *MockBondKeeperMockRecorder) AddCollectedBondStake(ctx, bond interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCollectedBondStake", reflect.TypeOf((*MockBondKeeper)(nil).AddCollectedBondStake), ctx, bond)
}

// GetParams mocks base method.
func (m *MockBondKeeper) GetParams(ctx context.Context) types0.Params {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParams", ctx)
	ret0, _ := ret[0].(types0.Params)
	return ret0
}

// GetParams indicates an expected call of GetParams.
func (mr *MockBondKeeperMockRecorder) GetParams(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParams", reflect.TypeOf((*MockBondKeeper)(nil).GetParams), ctx)
}
