syntax = "proto3";

package fuelsequencer.commitments.v1;

import "gogoproto/gogo.proto";
import "google/api/annotations.proto";
import "fuelsequencer/commitments/types.proto";

option go_package = "github.com/fuel-infrastructure/fuel-sequencer/x/commitments/types";

// Query defines the gRPC querier service.
service Query {

  // BridgeCommitment collects the transactions results roots over a provided
  // ordered range of blocks, and then creates a new merkle root. The range is
  // end exclusive.
  //
  // e.g. bridge_commitment?start=1&end=2
  rpc BridgeCommitment(QueryBridgeCommitmentRequest)
      returns (QueryBridgeCommitmentResponse) {
    option (google.api.http).get =
        "/fuelsequencer/commitments/v1/bridge_commitment";
  }

  // BridgeCommitmentInclusionProof creates two inclusion proofs to verify that
  // a transaction response is included in a BridgeCommitment. Users can also
  // verify any data in the transactions responses for data availability. Users
  // need to provide the height and the transaction index that the inclusion
  // proof is for. They also need to provide the indexes of the start and end
  // blocks for which the BridgeCommitment merkle root is constructed from. The
  // range for BridgeCommitment is end exclusive.
  //
  // e.g. bridge_commitment_inclusion_proof?height=2&tx_index=0&start=2&end=10
  rpc BridgeCommitmentInclusionProof(QueryBridgeCommitmentInclusionProofRequest)
      returns (QueryBridgeCommitmentInclusionProofResponse) {
    option (google.api.http).get =
        "/fuelsequencer/commitments/v1/bridge_commitment_inclusion_proof";
  }
}

// QueryBridgeCommitmentRequest is request type for the Query/Params RPC method.
message QueryBridgeCommitmentRequest {

  // start is the start of the block range that the bridge commitment covers.
  uint64 start = 1;

  // end is the exclusive end of the block range that the bridge commitment
  // covers.
  uint64 end = 2;
}

// QueryBridgeCommitmentResponse contains the merkle root of successive
// BridgeCommitmentLeaf.
message QueryBridgeCommitmentResponse {
  bytes bridge_commitment = 1 [ (gogoproto.casttype) = "HexBytes" ];
}

// QueryBridgeCommitmentInclusionProofRequest is request type for the
// Query/Params RPC method.
message QueryBridgeCommitmentInclusionProofRequest {

  // height is the block from which the last results hash will be obtained.
  int64 height = 1;

  // tx_index is the index of the transaction at its original block height.
  int64 tx_index = 2;

  // start is the start of the block range including the height.
  uint64 start = 3;

  // end is the exclusive end of the block range including the height.
  uint64 end = 4;
}

// QueryBridgeCommitmentInclusionProofResponse contains merkle proofs to show
// that a transaction response was used to construct the BridgeCommitment merkle
// root. It also includes the marshalled deterministic transaction result.
message QueryBridgeCommitmentInclusionProofResponse {

  // bridge_commitment_leaf is the bridge commitment leaf involved in the
  // BridgeCommitmentMerkleProof and also the one containing the LastResultsHash
  // that is the root of the LastResultsMerkleProof.
  BridgeCommitmentLeaf bridge_commitment_leaf = 1
      [ (gogoproto.nullable) = false ];

  // bridge_commitment_proof is a merkle proof proving a BridgeCommitmentLeaf
  // was used to construct the BridgeCommitment merkle root.
  BinaryMerkleProof bridge_commitment_proof = 2
      [ (gogoproto.nullable) = false ];

  // tx_result_marshalled is the marshalled deterministic form of the queried
  // transaction's ExecTxResult.
  bytes tx_result_marshalled = 3 [ (gogoproto.casttype) = "HexBytes" ];

  // last_results_proof is a merkle proof proving a transaction response was
  // used to form the LastResultsHash merkle root.
  BinaryMerkleProof last_results_proof = 4;
}
