{
 "title": "Sequencer",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "Application Basics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "cometbft_consensus_height{job=\"$job\"}",
     "legendFormat": "Block"
    }
   ]
  },
  {
   "title": "Minted FUEL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "FUEL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sequencer_begin_block_minted_tokens{job=\"$job\"}",
     "legendFormat": "Last"
    },
    {
     "expr": "avg_over_time(sequencer_begin_block_minted_tokens{job=\"$job\"}[$__interval])",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Consensus Txs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sequencer_store_index_num_injected_txs_total{job=\"$job\"}",
     "legendFormat": "Num Injected"
    },
    {
     "expr": "sequencer_store_last_consensus_txs_sequence{job=\"$job\"}",
     "legendFormat": "Consensus Sequence"
    }
   ]
  },
  {
   "title": "Consensus Round Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_round_duration_seconds_bucket{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Begin Blockers",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "begin_blocker{module=\"bridge\", job=\"$job\"}",
     "legendFormat": "{{module}} ({{quantile}})"
    },
    {
     "expr": "begin_blocker{module=\"mint\", job=\"$job\"}",
     "legendFormat": "{{module}} ({{quantile}})"
    }
   ]
  },
  {
   "title": "End Blockers",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "end_blocker{module=\"bridge\", job=\"$job\"}",
     "legendFormat": "{{module}} ({{quantile}})"
    },
    {
     "expr": "end_blocker{module=\"mint\", job=\"$job\"}",
     "legendFormat": "{{module}} ({{quantile}})"
    }
   ]
  },
  { "title": "Ethereum Syncing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Time Since Last Eth Update",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sequencer_store_time_since_last_eth_update{job=\"$job\"}",
     "legendFormat": "Delay"
    }
   ]
  },
  {
   "title": "Last Ethereum Block Synced",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sequencer_store_last_ethereum_block_synced{job=\"$job\"}",
     "legendFormat": "Block"
    }
   ]
  },
  {
   "title": "Txs to Ethereum",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 10 },
   "targets": [
    {
     "expr": "sequencer_store_ethereum_event_index_offset{job=\"$job\"}",
     "legendFormat": "Index Offset"
    },
    {
     "expr": "sequencer_store_last_ethereum_nonce{job=\"$job\"}",
     "legendFormat": "Last Nonce"
    }
   ]
  },
  {
   "title": "Supply Delta Reports",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "FUEL" } },
   "targets": [
    {
     "expr": "sequencer_begin_block_supply_current{job=\"$job\"}",
     "legendFormat": "Current Supply"
    },
    {
     "expr": "sequencer_begin_block_supply_last{job=\"$job\"}",
     "legendFormat": "Last Supply"
    },
    {
     "expr": "sequencer_begin_block_supply_offset{job=\"$job\"}",
     "legendFormat": "Supply Offset"
    },
    {
     "expr": "(sequencer_begin_block_supply_current{job=\"$job\"} - sequencer_begin_block_supply_last{job=\"$job\"}) + sequencer_begin_block_supply_offset{job=\"$job\"}",
     "legendFormat": "Report"
    }
   ]
  },
  {
   "title": "Num Injected Messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 3, "x": 14, "y": 10 },
   "targets": [
    {
     "expr": "sequencer_ante_handler_injected_msg{job=\"$job\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Num Deposits",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 10 },
   "targets": [
    {
     "expr": "sequencer_tx_msg_deposit_from_ethereum{to_user=\"true\", job=\"$job\"}",
     "legendFormat": "Num Deposits to User"
    },
    {
     "expr": "sequencer_tx_msg_deposit_from_ethereum{to_user!=\"true\", job=\"$job\"}",
     "legendFormat": "Num Deposits to Governance"
    }
   ]
  },
  {
   "title": "Num Withdrawals",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 14 },
   "targets": [
    {
     "expr": "sequencer_tx_msg_withdraw_to_ethereum{job=\"$job\"}",
     "legendFormat": "Num Withdrawals"
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Syncing",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_blocksync_syncing{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_size_bytes{job=\"$job\"}",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Mempool Size (Num Txs)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "cometbft_mempool_size{job=\"$job\"}",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Block Processing Time",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 3, "x": 10, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_state_block_processing_time_bucket{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P2P Receive Total (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(cometbft_p2p_peer_receive_bytes_total{job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missing Validators",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_missing_validators{job=\"$job\"}",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Chain Size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "cometbft_consensus_chain_size_bytes{job=\"$job\"}",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Mempool Size (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "cometbft_mempool_size_bytes{job=\"$job\"}",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "P2P Send Total (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(cometbft_p2p_peer_send_bytes_total{job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P2P Message Receive (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "cometbft_p2p_message_receive_bytes_total{job=\"$job\"}",
     "legendFormat": "{{message_type}}"
    }
   ]
  },
  {
   "title": "P2P Message Send (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "cometbft_p2p_message_send_bytes_total{job=\"$job\"}",
     "legendFormat": "{{message_type}}"
    }
   ]
  },
  {
   "title": "P2P Peer Receive (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "cometbft_p2p_peer_receive_bytes_total{job=\"$job\"}",
     "legendFormat": "Peer({{peer_id}})"
    }
   ]
  },
  {
   "title": "P2P Peer Send (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "cometbft_p2p_peer_send_bytes_total{job=\"$job\"}",
     "legendFormat": "Peer({{peer_id}})"
    }
   ]
  }
 ]
}