syntax = "proto3";

package fuelsequencer.reports;

import "amino/amino.proto";
import "gogoproto/gogo.proto";
import "fuelsequencer/reports/params.proto";
import "fuelsequencer/reports/slash_report.proto";

option go_package = "github.com/fuel-infrastructure/fuel-sequencer/x/reports/types";

// GenesisState defines the reports module's genesis state.
message GenesisState {

  // params defines all the parameters of the module.
  Params params = 1
      [ (gogoproto.nullable) = false, (amino.dont_omitempty) = true ];

  // slash_report_list defines all slashing reports that should be set in state.
  repeated SlashReport slash_report_list = 2 [ (gogoproto.nullable) = false ];
}
