syntax = "proto3";
package fuelsequencer.reports;

import "amino/amino.proto";
import "gogoproto/gogo.proto";

option go_package = "github.com/fuel-infrastructure/fuel-sequencer/x/reports/types";

// Params defines the parameters for the module.
message Params {
  option (amino.name) = "fuelsequencer/x/reports/Params";
  option (gogoproto.equal) = true;

  // max_slash_report_age_blocks determines for how many blocks a slash report
  // will be kept in state before it gets removed by the EndBlocker.
  uint64 max_slash_report_age_blocks = 1;
}