syntax = "proto3";
package fuelsequencer.bond;

import "amino/amino.proto";
import "gogoproto/gogo.proto";
import "cosmos/base/v1beta1/coin.proto";

option go_package = "github.com/fuel-infrastructure/fuel-sequencer/x/bond/types";

// Params defines the parameters for the module.
message Params {
  option (amino.name) = "fuelsequencer/x/bond/Params";
  option (gogoproto.equal) = true;

  // Inflation defines the inflation rate for the bond module
  string inflation = 1 [
    (gogoproto.customtype) = "cosmossdk.io/math.LegacyDec",
    (gogoproto.nullable) = false
  ];

  // Authority defines the address that receives the inflation
  // and decides how many of it to distribute or burn
  string authority = 2;
}