syntax = "proto3";
package fuelsequencer.bond;

import "amino/amino.proto";
import "cosmos/msg/v1/msg.proto";
import "cosmos_proto/cosmos.proto";
import "gogoproto/gogo.proto";
import "fuelsequencer/bond/params.proto";
import "cosmos/base/v1beta1/coin.proto";

option go_package = "github.com/fuel-infrastructure/fuel-sequencer/x/bond/types";

// Msg defines the Msg service.
service Msg {
  option (cosmos.msg.v1.service) = true;

  // UpdateParams defines a (governance) operation for updating the module
  // parameters. The authority defaults to the x/gov module account.
  rpc UpdateParams(MsgUpdateParams) returns (MsgUpdateParamsResponse);

  // BurnCoins defines a message to burn coins
  rpc BurnCoins(MsgBurnCoins) returns (MsgBurnCoinsResponse);
}

// MsgUpdateParams is the Msg/UpdateParams request type.
message MsgUpdateParams {
  option (cosmos.msg.v1.signer) = "authority";
  option (amino.name) = "fuelsequencer/x/bond/MsgUpdateParams";

  // authority is the address that controls the module (defaults to x/gov unless
  // overwritten).
  string authority = 1 [ (cosmos_proto.scalar) = "cosmos.AddressString" ];

  // params defines the module parameters to update.
  //
  // NOTE: All parameters must be supplied.
  Params params = 2
      [ (gogoproto.nullable) = false, (amino.dont_omitempty) = true ];
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
message MsgUpdateParamsResponse {}

// MsgBurnCoins is the Msg/BurnCoins request type.
message MsgBurnCoins {
  option (cosmos.msg.v1.signer) = "sender";
  option (amino.name) = "fuelsequencer/x/bond/MsgBurnCoins";

  // sender is the address that will burn the coins
  string sender = 1 [ (cosmos_proto.scalar) = "cosmos.AddressString" ];

  // coins defines the coins to burn
  repeated cosmos.base.v1beta1.Coin coins = 2 [
    (gogoproto.nullable) = false,
    (gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.Coins"
  ];
}

// MsgBurnCoinsResponse defines the response structure for executing a
// MsgBurnCoins message.
message MsgBurnCoinsResponse {}