package utils

import (
	"encoding/json"
	"strconv"
	"testing"

	sdkmath "cosmossdk.io/math"
	sdk "github.com/cosmos/cosmos-sdk/types"
	banktypes "github.com/cosmos/cosmos-sdk/x/bank/types"
	distributiontypes "github.com/cosmos/cosmos-sdk/x/distribution/types"
	govtypesv1 "github.com/cosmos/cosmos-sdk/x/gov/types/v1"
	stakingtypes "github.com/cosmos/cosmos-sdk/x/staking/types"
	"github.com/ethereum/go-ethereum/accounts/abi"
	ethereumtypes "github.com/ethereum/go-ethereum/core/types"
	sidecartypes "github.com/fuel-infrastructure/fuel-sequencer/sidecar/service/types"
	bridgetypes "github.com/fuel-infrastructure/fuel-sequencer/x/bridge/types"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const (
	// Fixtures generated by running the test in e2e/tests/authorize-fixtures

	amount                        = 100
	bridgeDenom                   = "utest"
	vestingDurationSeconds        = "63072000"
	voteProposalId                = uint64(1)
	voteOption                    = int32(1)
	voteMetadata                  = "metadata"
	senderAddress                 = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
	receiverAddress               = "0xe53E6E952cf156b9f58A2A82da5ea537102Ba484"
	validator1Address             = "0xA12DAAf3C2C1505B288353B62cB3B4021C60c344"
	validator2Address             = "0x62d221dB49aEF5632f59B900B2cA90e52ECC0A80"
	sequencerProxyContractAddress = "0x0165878A594ca255338adfa4d48449f69242Eb8F"
	depositLogs                   = `[{"address":"0xe7f1725e7734ce288f8367e1bb143e90bb3f0512","topics":["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266","0x000000000000000000000000dc64a140aa3e981100a9beca4e685f962f0cf6c9"],"data":"0x0000000000000000000000000000000000000000000000000000000000000064","blockNumber":"0x59","transactionHash":"0xaf42b11084bb277707f2a7eeb730562038f7aa68180bf8f841745f6410b24def","transactionIndex":"0x0","blockHash":"0xf76012a9e04af408f153f44dfad505addbe6142451261af4ddae25cfdcc03648","logIndex":"0x0","removed":false},{"address":"0x0165878a594ca255338adfa4d48449f69242eb8f","topics":["0xdcbc1c05240f31ff3ad067ef1ee35ce4997762752e3a095284754544f4c709d7","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266"],"data":"0x00000000000000000000000000000000000000000000000000000000000000640000000000000000000000000000000000000000000000000000000000000000","blockNumber":"0x59","transactionHash":"0xaf42b11084bb277707f2a7eeb730562038f7aa68180bf8f841745f6410b24def","transactionIndex":"0x0","blockHash":"0xf76012a9e04af408f153f44dfad505addbe6142451261af4ddae25cfdcc03648","logIndex":"0x1","removed":false},{"address":"0x2279b7a0a67db372996a5fab50d91eaa73d2ebe6","topics":["0xe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266"],"data":"0x0000000000000000000000000000000000000000000000000000000000000064","blockNumber":"0x59","transactionHash":"0xaf42b11084bb277707f2a7eeb730562038f7aa68180bf8f841745f6410b24def","transactionIndex":"0x0","blockHash":"0xf76012a9e04af408f153f44dfad505addbe6142451261af4ddae25cfdcc03648","logIndex":"0x2","removed":false}]`
	depositForLogs                = `[{"address":"0xe7f1725e7734ce288f8367e1bb143e90bb3f0512","topics":["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266","0x000000000000000000000000dc64a140aa3e981100a9beca4e685f962f0cf6c9"],"data":"0x0000000000000000000000000000000000000000000000000000000000000064","blockNumber":"0x5a","transactionHash":"0x0452fc836271a33a80b630d06861af5190e8b27614fcc53bbb4641cc16ef1211","transactionIndex":"0x0","blockHash":"0x6ed1c3997f2c44e38739b5f9b8a4a23efd942990752588c1140907e3e9290925","logIndex":"0x0","removed":false},{"address":"0x0165878a594ca255338adfa4d48449f69242eb8f","topics":["0xdcbc1c05240f31ff3ad067ef1ee35ce4997762752e3a095284754544f4c709d7","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266","0x000000000000000000000000e53e6e952cf156b9f58a2a82da5ea537102ba484"],"data":"0x00000000000000000000000000000000000000000000000000000000000000640000000000000000000000000000000000000000000000000000000000000000","blockNumber":"0x5a","transactionHash":"0x0452fc836271a33a80b630d06861af5190e8b27614fcc53bbb4641cc16ef1211","transactionIndex":"0x0","blockHash":"0x6ed1c3997f2c44e38739b5f9b8a4a23efd942990752588c1140907e3e9290925","logIndex":"0x1","removed":false},{"address":"0x2279b7a0a67db372996a5fab50d91eaa73d2ebe6","topics":["0xe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266"],"data":"0x0000000000000000000000000000000000000000000000000000000000000064","blockNumber":"0x5a","transactionHash":"0x0452fc836271a33a80b630d06861af5190e8b27614fcc53bbb4641cc16ef1211","transactionIndex":"0x0","blockHash":"0x6ed1c3997f2c44e38739b5f9b8a4a23efd942990752588c1140907e3e9290925","logIndex":"0x2","removed":false}]`
	depositWithLockupLogs         = `[{"address":"0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0","topics":["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266","0x0000000000000000000000000000000000000000000000000000000000000000"],"data":"0x000000000000000000000000000000000000000000000000000000003b9aca00","blockNumber":"0x5e","transactionHash":"0xa90c20759c443357fc5ea9a5948ad5e61b6c92b05fc0f949908757077e2f3861","transactionIndex":"0x0","blockHash":"0xf54f48cafda6ba55d461c6165e06ce47517440027cf3b88c1c5ff00681e2bdbb","logIndex":"0x0","removed":false},{"address":"0xe7f1725e7734ce288f8367e1bb143e90bb3f0512","topics":["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef","0x000000000000000000000000610178da211fef7d417bc0e6fed39f05609ad788","0x0000000000000000000000002279b7a0a67db372996a5fab50d91eaa73d2ebe6"],"data":"0x0000000000000000000000000000000000000000000000000000000000000064","blockNumber":"0x5e","transactionHash":"0xa90c20759c443357fc5ea9a5948ad5e61b6c92b05fc0f949908757077e2f3861","transactionIndex":"0x0","blockHash":"0xf54f48cafda6ba55d461c6165e06ce47517440027cf3b88c1c5ff00681e2bdbb","logIndex":"0x1","removed":false},{"address":"0xe7f1725e7734ce288f8367e1bb143e90bb3f0512","topics":["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef","0x0000000000000000000000002279b7a0a67db372996a5fab50d91eaa73d2ebe6","0x000000000000000000000000dc64a140aa3e981100a9beca4e685f962f0cf6c9"],"data":"0x0000000000000000000000000000000000000000000000000000000000000064","blockNumber":"0x5e","transactionHash":"0xa90c20759c443357fc5ea9a5948ad5e61b6c92b05fc0f949908757077e2f3861","transactionIndex":"0x0","blockHash":"0xf54f48cafda6ba55d461c6165e06ce47517440027cf3b88c1c5ff00681e2bdbb","logIndex":"0x2","removed":false},{"address":"0x0165878a594ca255338adfa4d48449f69242eb8f","topics":["0xdcbc1c05240f31ff3ad067ef1ee35ce4997762752e3a095284754544f4c709d7","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266"],"data":"0x00000000000000000000000000000000000000000000000000000000000000640000000000000000000000000000000000000000000000000000000003c26700","blockNumber":"0x5e","transactionHash":"0xa90c20759c443357fc5ea9a5948ad5e61b6c92b05fc0f949908757077e2f3861","transactionIndex":"0x0","blockHash":"0xf54f48cafda6ba55d461c6165e06ce47517440027cf3b88c1c5ff00681e2bdbb","logIndex":"0x3","removed":false},{"address":"0x2279b7a0a67db372996a5fab50d91eaa73d2ebe6","topics":["0xe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266"],"data":"0x0000000000000000000000000000000000000000000000000000000000000064","blockNumber":"0x5e","transactionHash":"0xa90c20759c443357fc5ea9a5948ad5e61b6c92b05fc0f949908757077e2f3861","transactionIndex":"0x0","blockHash":"0xf54f48cafda6ba55d461c6165e06ce47517440027cf3b88c1c5ff00681e2bdbb","logIndex":"0x4","removed":false}]`
	delegateLogs                  = `[{"address":"0x0165878a594ca255338adfa4d48449f69242eb8f","topics":["0x510b11bb3f3c799b11307c01ab7db0d335683ef5b2da98f7697de744f465eacc","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266","0x000000000000000000000000a12daaf3c2c1505b288353b62cb3b4021c60c344"],"data":"0x0000000000000000000000000000000000000000000000000000000000000064","blockNumber":"0x60","transactionHash":"0xa264399e1b43b9435025021bd39dc3064b162dcc4e2ae205a8a0fa211675c891","transactionIndex":"0x0","blockHash":"0xd02bee360759e0ad43d9843f269c6823eeef334a517f6b4f9084e5657d3cca10","logIndex":"0x0","removed":false}]`
	redelegateLogs                = `[{"address":"0x0165878a594ca255338adfa4d48449f69242eb8f","topics":["0x3ca49cdc02409b294ed8ec6b982a9785702a2ae85e08b6208625dd6beee36036","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266","0x000000000000000000000000a12daaf3c2c1505b288353b62cb3b4021c60c344","0x00000000000000000000000062d221db49aef5632f59b900b2ca90e52ecc0a80"],"data":"0x0000000000000000000000000000000000000000000000000000000000000064","blockNumber":"0x62","transactionHash":"0x956640782f7a183b59685bd5573f78c0f07f7dd5e3c2b3c89894e6329060c481","transactionIndex":"0x0","blockHash":"0xce60cea4bca403a0d4a9bd46855f82f0b706a227a0956be7e2d2895558a5ec03","logIndex":"0x0","removed":false}]`
	claimRewardsLogs              = `[{"address":"0x0165878a594ca255338adfa4d48449f69242eb8f","topics":["0x62fb75d791ef63ca4ed94dc4e1eb6076c3c2c78651c6b34abf935e52e0d8dea7","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266","0x000000000000000000000000a12daaf3c2c1505b288353b62cb3b4021c60c344"],"data":"0x","blockNumber":"0x63","transactionHash":"0xd9c8104e2b443db7a7e02984df973bb21c476681f5e0570a1222644d42fc1ca6","transactionIndex":"0x0","blockHash":"0x21942ce150ace57f6e9347fde6fdc96a4c4a48b015aa13d746ef9e1924fc920c","logIndex":"0x0","removed":false}]`
	unbondLogs                    = `[{"address":"0x0165878a594ca255338adfa4d48449f69242eb8f","topics":["0x815134b5aa3c5caabcdaf305b7dc586ca56abde81012388563e8c4c2174a90f5","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266","0x000000000000000000000000a12daaf3c2c1505b288353b62cb3b4021c60c344"],"data":"0x0000000000000000000000000000000000000000000000000000000000000064","blockNumber":"0x65","transactionHash":"0x0b3e6f927c5480b2d742af164b305c70ec1d3ee433dcdf533ff854410e8525d7","transactionIndex":"0x0","blockHash":"0x833f73ef2eb8a8c1ef57bf17d4256adb907d11842dd0ba003464ccfc4c3657f7","logIndex":"0x0","removed":false}]`
	withdrawLogs                  = `[{"address":"0x0165878a594ca255338adfa4d48449f69242eb8f","topics":["0x9b1bfa7fa9ee420a16e124f794c35ac9f90472acc99140eb2f6447c714cad8eb","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266"],"data":"0x0000000000000000000000000000000000000000000000000000000000000064","blockNumber":"0x66","transactionHash":"0x900e856f6d0994b79f9f1ca4e84542b0c524bdd3cf75c664c21212ed593dcc45","transactionIndex":"0x0","blockHash":"0xfe872b5461492ce6a87f9c828d2c9ff2a6fc753ff4e0e05ee5ebda5f70ffcee6","logIndex":"0x0","removed":false}]`
	withdrawToLogs                = `[{"address":"0x0165878a594ca255338adfa4d48449f69242eb8f","topics":["0x9b1bfa7fa9ee420a16e124f794c35ac9f90472acc99140eb2f6447c714cad8eb","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266","0x000000000000000000000000e53e6e952cf156b9f58a2a82da5ea537102ba484"],"data":"0x0000000000000000000000000000000000000000000000000000000000000064","blockNumber":"0x68","transactionHash":"0x887732a8781bc5eeac061a7a41a1abacb582e1f7641e0736b6fc68fdbf070802","transactionIndex":"0x0","blockHash":"0xf8802ce5ef596db3fd5626308d15f1c8f4f77efac42200a450e25a61ab8ff11f","logIndex":"0x0","removed":false}]`
	transferLogs                  = `[{"address":"0x0165878a594ca255338adfa4d48449f69242eb8f","topics":["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266","0x000000000000000000000000e53e6e952cf156b9f58a2a82da5ea537102ba484"],"data":"0x0000000000000000000000000000000000000000000000000000000000000064","blockNumber":"0x69","transactionHash":"0x1dbec20a047a967423c0e306b55d625157ebd71d7c0423864118911dc6d87e4f","transactionIndex":"0x0","blockHash":"0xc796e98f9ffc3ca3a0997e16ad40efe2f7fdf14eb66eb7ae984e7326024ce06d","logIndex":"0x0","removed":false}]`
	voteLogs                      = `[{"address":"0x0165878a594ca255338adfa4d48449f69242eb8f","topics":["0x456317ab0c14ca006fefb6a12ba5ce82adf54fd3cf455be6b1286e1f612d3d19","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266","0x0000000000000000000000000000000000000000000000000000000000000001"],"data":"0x0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000086d65746164617461000000000000000000000000000000000000000000000000","blockNumber":"0x6a","transactionHash":"0xab74ceb05497ec2bb280bbabead4e82de50547fe49d5e54c72a1e3f392f50ce8","transactionIndex":"0x0","blockHash":"0x9726452d30ff8fd747322e5f0bc7745a4dc5658c578a915445d959b1be66a0bf","logIndex":"0x0","removed":false}]`
	setRewardRecipientLogs        = `[{"address":"0x0165878a594ca255338adfa4d48449f69242eb8f","topics":["0xc6b66e0e282673c442421e1c6b89458b7631f26f5dcd0b2b216c45831ca1d7d5","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266","0x000000000000000000000000e53e6e952cf156b9f58a2a82da5ea537102ba484"],"data":"0x","blockNumber":"0x6c","transactionHash":"0xe6b78077c4abec9067110bab1b06cfdc506ac1e1505923486e6cdbe1f2ef0b6a","transactionIndex":"0x0","blockHash":"0x9e67e15c6ee71325f7b31bbbf257e2eab1c3157c5f7d21b5fb57474fac187e9b","logIndex":"0x0","removed":false}]`
	authorizeLogs                 = `[{"address":"0x0165878a594ca255338adfa4d48449f69242eb8f","topics":["0x38cf2222fd9da5a0ceb8506c44fa5bcd7011fe00163dc14950d5628d8c301f04","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266"],"data":"0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000890a86010a1c2f636f736d6f732e62616e6b2e763162657461312e4d736753656e6412660a2a307866333946643665353161616438384636463463653661423838323732373963666646623932323636122a3078653533453645393532636631353662396635384132413832646135656135333731303242613438341a0c0a05757465737412033130300000000000000000000000000000000000000000000000","blockNumber":"0x6d","transactionHash":"0xee9d29a0a95b7489e1864e3d0b92e420a7e4c1b3be2cacd3248207ec12e1ae77","transactionIndex":"0x0","blockHash":"0xc76f73c7f26d7e451f8fde7484b3454cfec2ca2043b7a5b69b181792ea11395f","logIndex":"0x0","removed":false}]`
)

func sequencerProxyContractABI(t *testing.T) abi.ABI {
	var contractAbi abi.ABI
	err := contractAbi.UnmarshalJSON([]byte(sidecartypes.SequencerProxyContractABI))
	require.NoError(t, err)
	return contractAbi
}

func eventFromMsg(t *testing.T, msg sdk.Msg) *sidecartypes.Event {
	data, err := AuthorizeTxFromMsg(msg)
	require.NoError(t, err)

	authorizeEvent := sidecartypes.AuthorizeEvent{
		Sender: senderAddress,
		Data:   data,
	}
	authorizeEventBz, err := authorizeEvent.Marshal()
	require.NoError(t, err)

	event := &sidecartypes.Event{
		EventType:       sidecartypes.AuthorizeEventName,
		Data:            authorizeEventBz,
		ContractAddress: sequencerProxyContractAddress,
	}
	return event
}

func eventFromDepositEvent(t *testing.T, depositEvent sidecartypes.DepositEvent) *sidecartypes.Event {
	depositEventBz, err := depositEvent.Marshal()
	require.NoError(t, err)

	return &sidecartypes.Event{
		EventType:       sidecartypes.DepositEventName,
		Data:            depositEventBz,
		ContractAddress: sequencerProxyContractAddress,
	}
}

func TestExtractLogDataToEvent_AuthorizeTxFromEvent(t *testing.T) {
	sequencerProxyABI := sequencerProxyContractABI(t)
	amountParsed := sdkmath.NewInt(amount)

	testCases := []struct {
		name        string
		logs        string
		getExpEvent func() *sidecartypes.Event
		expErrMsg   string
	}{
		{
			name: "Deposit event via Deposit",
			logs: depositLogs,
			getExpEvent: func() *sidecartypes.Event {
				return eventFromDepositEvent(t, sidecartypes.DepositEvent{
					Depositor: senderAddress,
					Recipient: senderAddress, // sender deposits to themselves
					Amount:    strconv.FormatInt(amount, 10),
					Lockup:    "0",
				})
			},
		},
		{
			name: "Deposit event via DepositFor",
			logs: depositForLogs,
			getExpEvent: func() *sidecartypes.Event {
				return eventFromDepositEvent(t, sidecartypes.DepositEvent{
					Depositor: senderAddress,
					Recipient: receiverAddress,
					Amount:    strconv.FormatInt(amount, 10),
					Lockup:    "0",
				})
			},
		},
		{
			name: "Deposit event with lockup",
			logs: depositWithLockupLogs,
			getExpEvent: func() *sidecartypes.Event {
				return eventFromDepositEvent(t, sidecartypes.DepositEvent{
					Depositor: senderAddress,
					Recipient: senderAddress, // sender deposits to themselves
					Amount:    strconv.FormatInt(amount, 10),
					Lockup:    vestingDurationSeconds,
				})
			},
		},
		{
			name: "Delegate event",
			logs: delegateLogs,
			getExpEvent: func() *sidecartypes.Event {
				return eventFromMsg(t, &stakingtypes.MsgDelegate{
					DelegatorAddress: senderAddress,
					ValidatorAddress: validator1Address,
					Amount:           sdk.NewCoin(bridgeDenom, amountParsed),
				})
			},
		},
		{
			name: "Redelegate event",
			logs: redelegateLogs,
			getExpEvent: func() *sidecartypes.Event {
				return eventFromMsg(t, &stakingtypes.MsgBeginRedelegate{
					DelegatorAddress:    senderAddress,
					ValidatorSrcAddress: validator1Address,
					ValidatorDstAddress: validator2Address,
					Amount:              sdk.NewCoin(bridgeDenom, amountParsed),
				})
			},
		},
		{
			name: "ClaimRewards event",
			logs: claimRewardsLogs,
			getExpEvent: func() *sidecartypes.Event {
				return eventFromMsg(t, &distributiontypes.MsgWithdrawDelegatorReward{
					DelegatorAddress: senderAddress,
					ValidatorAddress: validator1Address,
				})
			},
		},
		{
			name: "Unbond event",
			logs: unbondLogs,
			getExpEvent: func() *sidecartypes.Event {
				return eventFromMsg(t, &stakingtypes.MsgUndelegate{
					DelegatorAddress: senderAddress,
					ValidatorAddress: validator1Address,
					Amount:           sdk.NewCoin(bridgeDenom, amountParsed),
				})
			},
		},
		{
			name: "Withdraw event via Withdraw",
			logs: withdrawLogs,
			getExpEvent: func() *sidecartypes.Event {
				return eventFromMsg(t, &bridgetypes.MsgWithdrawToEthereum{
					From:   senderAddress,
					To:     senderAddress, // sender withdraws to themselves
					Amount: sdk.NewCoin(bridgeDenom, amountParsed),
				})
			},
		},
		{
			name: "Withdraw event via WithdrawTo",
			logs: withdrawToLogs,
			getExpEvent: func() *sidecartypes.Event {
				return eventFromMsg(t, &bridgetypes.MsgWithdrawToEthereum{
					From:   senderAddress,
					To:     receiverAddress,
					Amount: sdk.NewCoin(bridgeDenom, amountParsed),
				})
			},
		},
		{
			name: "Transfer event",
			logs: transferLogs,
			getExpEvent: func() *sidecartypes.Event {
				return eventFromMsg(t, &banktypes.MsgSend{
					FromAddress: senderAddress,
					ToAddress:   receiverAddress,
					Amount:      sdk.NewCoins(sdk.NewCoin(bridgeDenom, amountParsed)),
				})
			},
		},
		{
			name: "Vote event",
			logs: voteLogs,
			getExpEvent: func() *sidecartypes.Event {
				return eventFromMsg(t, &govtypesv1.MsgVote{
					ProposalId: voteProposalId,
					Voter:      senderAddress,
					Option:     govtypesv1.VoteOption(voteOption),
					Metadata:   voteMetadata,
				})
			},
		},
		{
			name: "SetRewardRecipient event",
			logs: setRewardRecipientLogs,
			getExpEvent: func() *sidecartypes.Event {
				return eventFromMsg(t, &distributiontypes.MsgSetWithdrawAddress{
					DelegatorAddress: senderAddress,
					WithdrawAddress:  receiverAddress,
				})
			},
		},
		{
			name: "Authorize event",
			logs: authorizeLogs,
			getExpEvent: func() *sidecartypes.Event {
				return eventFromMsg(t, &banktypes.MsgSend{
					FromAddress: senderAddress,
					ToAddress:   receiverAddress,
					Amount:      sdk.NewCoins(sdk.NewCoin(bridgeDenom, amountParsed)),
				})
			},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			expectedEvent := tc.getExpEvent()

			// Parse log into Log struct
			var parsedLog []ethereumtypes.Log
			err := json.Unmarshal([]byte(tc.logs), &parsedLog)
			require.NoError(t, err)

			// There might be multiple logs. Check that there is exactly one log that matches the expected log.
			matches := 0
			for _, log := range parsedLog {
				event, err := ExtractLogDataToEvent(log, sequencerProxyABI, bridgeDenom)
				if tc.expErrMsg != "" {
					require.EqualError(t, err, tc.expErrMsg)
					return
				}
				require.NoError(t, err)

				if assert.ObjectsAreEqual(expectedEvent, event) {
					matches += 1
				}
			}

			require.Equal(t, 1, matches)
		})
	}
}
