package utils

import (
	"encoding/json"
	"strconv"
	"testing"

	sdkmath "cosmossdk.io/math"
	sdk "github.com/cosmos/cosmos-sdk/types"
	banktypes "github.com/cosmos/cosmos-sdk/x/bank/types"
	distributiontypes "github.com/cosmos/cosmos-sdk/x/distribution/types"
	govtypesv1 "github.com/cosmos/cosmos-sdk/x/gov/types/v1"
	stakingtypes "github.com/cosmos/cosmos-sdk/x/staking/types"
	"github.com/ethereum/go-ethereum/accounts/abi"
	ethereumtypes "github.com/ethereum/go-ethereum/core/types"
	sidecartypes "github.com/fuel-infrastructure/fuel-sequencer/sidecar/service/types"
	bridgetypes "github.com/fuel-infrastructure/fuel-sequencer/x/bridge/types"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const (
	// Fixtures generated by running the test in e2e/tests/authorize-fixtures

	amount                        = 100
	bridgeDenom                   = "utest"
	vestingDurationSeconds        = "63072000"
	voteProposalId                = uint64(1)
	voteOption                    = int32(1)
	voteMetadata                  = "metadata"
	senderAddress                 = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
	receiverAddress               = "0xe53E6E952cf156b9f58A2A82da5ea537102Ba484"
	validator1Address             = "0xA12DAAf3C2C1505B288353B62cB3B4021C60c344"
	validator2Address             = "0x62d221dB49aEF5632f59B900B2cA90e52ECC0A80"
	sequencerProxyContractAddress = "0x0165878A594ca255338adfa4d48449f69242Eb8F"
	depositLogs                   = `[{"address":"0xe7f1725e7734ce288f8367e1bb143e90bb3f0512","topics":["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266","0x000000000000000000000000dc64a140aa3e981100a9beca4e685f962f0cf6c9"],"data":"0x0000000000000000000000000000000000000000000000000000000000000064","blockNumber":"0x58","transactionHash":"0x29a5ff0e2e5ea456a765cc8a4a0a6368b6bd5f81e7c513b506270c59d5d98196","transactionIndex":"0x0","blockHash":"0xdd6cec8aefca2202159e1a22a19f072f25aebed658921cda3b58f88539ff2476","logIndex":"0x0","removed":false},{"address":"0x0165878a594ca255338adfa4d48449f69242eb8f","topics":["0xdcbc1c05240f31ff3ad067ef1ee35ce4997762752e3a095284754544f4c709d7","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266"],"data":"0x00000000000000000000000000000000000000000000000000000000000000640000000000000000000000000000000000000000000000000000000000000000","blockNumber":"0x58","transactionHash":"0x29a5ff0e2e5ea456a765cc8a4a0a6368b6bd5f81e7c513b506270c59d5d98196","transactionIndex":"0x0","blockHash":"0xdd6cec8aefca2202159e1a22a19f072f25aebed658921cda3b58f88539ff2476","logIndex":"0x1","removed":false},{"address":"0x2279b7a0a67db372996a5fab50d91eaa73d2ebe6","topics":["0xe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266"],"data":"0x0000000000000000000000000000000000000000000000000000000000000064","blockNumber":"0x58","transactionHash":"0x29a5ff0e2e5ea456a765cc8a4a0a6368b6bd5f81e7c513b506270c59d5d98196","transactionIndex":"0x0","blockHash":"0xdd6cec8aefca2202159e1a22a19f072f25aebed658921cda3b58f88539ff2476","logIndex":"0x2","removed":false}]`
	depositForLogs                = `[{"address":"0xe7f1725e7734ce288f8367e1bb143e90bb3f0512","topics":["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266","0x000000000000000000000000dc64a140aa3e981100a9beca4e685f962f0cf6c9"],"data":"0x0000000000000000000000000000000000000000000000000000000000000064","blockNumber":"0x59","transactionHash":"0x778f840b68f8280ed967f32114145eda2e1bb22713cd9e9b4e8f3e6b491a6431","transactionIndex":"0x0","blockHash":"0xcc5a7d492a0e6e6b68fbdb84d5cca3ce2b8d821166866be95d1d032faa8e96ad","logIndex":"0x0","removed":false},{"address":"0x0165878a594ca255338adfa4d48449f69242eb8f","topics":["0xdcbc1c05240f31ff3ad067ef1ee35ce4997762752e3a095284754544f4c709d7","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266","0x000000000000000000000000e53e6e952cf156b9f58a2a82da5ea537102ba484"],"data":"0x00000000000000000000000000000000000000000000000000000000000000640000000000000000000000000000000000000000000000000000000000000000","blockNumber":"0x59","transactionHash":"0x778f840b68f8280ed967f32114145eda2e1bb22713cd9e9b4e8f3e6b491a6431","transactionIndex":"0x0","blockHash":"0xcc5a7d492a0e6e6b68fbdb84d5cca3ce2b8d821166866be95d1d032faa8e96ad","logIndex":"0x1","removed":false},{"address":"0x2279b7a0a67db372996a5fab50d91eaa73d2ebe6","topics":["0xe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266"],"data":"0x0000000000000000000000000000000000000000000000000000000000000064","blockNumber":"0x59","transactionHash":"0x778f840b68f8280ed967f32114145eda2e1bb22713cd9e9b4e8f3e6b491a6431","transactionIndex":"0x0","blockHash":"0xcc5a7d492a0e6e6b68fbdb84d5cca3ce2b8d821166866be95d1d032faa8e96ad","logIndex":"0x2","removed":false}]`
	depositWithLockupLogs         = `[{"address":"0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0","topics":["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266","0x0000000000000000000000000000000000000000000000000000000000000000"],"data":"0x000000000000000000000000000000000000000000000000000000003b9aca00","blockNumber":"0x5d","transactionHash":"0x621a4d58f47363bd465687f326ae3aab08f920e7355a072b987cf9ef67aca072","transactionIndex":"0x0","blockHash":"0xcb5954ef9d92e7b73f298a39f60202845931d0f64ae0b705ec23fa91ec3529a8","logIndex":"0x0","removed":false},{"address":"0xe7f1725e7734ce288f8367e1bb143e90bb3f0512","topics":["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef","0x000000000000000000000000610178da211fef7d417bc0e6fed39f05609ad788","0x0000000000000000000000002279b7a0a67db372996a5fab50d91eaa73d2ebe6"],"data":"0x0000000000000000000000000000000000000000000000000000000000000064","blockNumber":"0x5d","transactionHash":"0x621a4d58f47363bd465687f326ae3aab08f920e7355a072b987cf9ef67aca072","transactionIndex":"0x0","blockHash":"0xcb5954ef9d92e7b73f298a39f60202845931d0f64ae0b705ec23fa91ec3529a8","logIndex":"0x1","removed":false},{"address":"0xe7f1725e7734ce288f8367e1bb143e90bb3f0512","topics":["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef","0x0000000000000000000000002279b7a0a67db372996a5fab50d91eaa73d2ebe6","0x000000000000000000000000dc64a140aa3e981100a9beca4e685f962f0cf6c9"],"data":"0x0000000000000000000000000000000000000000000000000000000000000064","blockNumber":"0x5d","transactionHash":"0x621a4d58f47363bd465687f326ae3aab08f920e7355a072b987cf9ef67aca072","transactionIndex":"0x0","blockHash":"0xcb5954ef9d92e7b73f298a39f60202845931d0f64ae0b705ec23fa91ec3529a8","logIndex":"0x2","removed":false},{"address":"0x0165878a594ca255338adfa4d48449f69242eb8f","topics":["0xdcbc1c05240f31ff3ad067ef1ee35ce4997762752e3a095284754544f4c709d7","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266"],"data":"0x00000000000000000000000000000000000000000000000000000000000000640000000000000000000000000000000000000000000000000000000003c26700","blockNumber":"0x5d","transactionHash":"0x621a4d58f47363bd465687f326ae3aab08f920e7355a072b987cf9ef67aca072","transactionIndex":"0x0","blockHash":"0xcb5954ef9d92e7b73f298a39f60202845931d0f64ae0b705ec23fa91ec3529a8","logIndex":"0x3","removed":false},{"address":"0x2279b7a0a67db372996a5fab50d91eaa73d2ebe6","topics":["0xe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266"],"data":"0x0000000000000000000000000000000000000000000000000000000000000064","blockNumber":"0x5d","transactionHash":"0x621a4d58f47363bd465687f326ae3aab08f920e7355a072b987cf9ef67aca072","transactionIndex":"0x0","blockHash":"0xcb5954ef9d92e7b73f298a39f60202845931d0f64ae0b705ec23fa91ec3529a8","logIndex":"0x4","removed":false}]`
	delegateLogs                  = `[{"address":"0x0165878a594ca255338adfa4d48449f69242eb8f","topics":["0x510b11bb3f3c799b11307c01ab7db0d335683ef5b2da98f7697de744f465eacc","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266","0x000000000000000000000000a12daaf3c2c1505b288353b62cb3b4021c60c344"],"data":"0x0000000000000000000000000000000000000000000000000000000000000064","blockNumber":"0x5f","transactionHash":"0x827b301074f552db824c039b7f3f436182df8f622c7eb566218e05eecd28d11f","transactionIndex":"0x0","blockHash":"0x4b2da61941db5c17ddfa25597370ffeb92b1b425e80f2b0916a2d6ee6a93e79f","logIndex":"0x0","removed":false}]`
	redelegateLogs                = `[{"address":"0x0165878a594ca255338adfa4d48449f69242eb8f","topics":["0x3ca49cdc02409b294ed8ec6b982a9785702a2ae85e08b6208625dd6beee36036","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266","0x000000000000000000000000a12daaf3c2c1505b288353b62cb3b4021c60c344","0x00000000000000000000000062d221db49aef5632f59b900b2ca90e52ecc0a80"],"data":"0x0000000000000000000000000000000000000000000000000000000000000064","blockNumber":"0x60","transactionHash":"0x0a5fb2192c4dd26fcacc44acb28fe8eca44a4091f81ce32642df30785863a6e4","transactionIndex":"0x0","blockHash":"0x3c346a60a203890f995c57ad6698680a2e30ac30dc7bb5e438848aaacafdeb4c","logIndex":"0x0","removed":false}]`
	claimRewardsLogs              = `[{"address":"0x0165878a594ca255338adfa4d48449f69242eb8f","topics":["0x62fb75d791ef63ca4ed94dc4e1eb6076c3c2c78651c6b34abf935e52e0d8dea7","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266","0x000000000000000000000000a12daaf3c2c1505b288353b62cb3b4021c60c344"],"data":"0x","blockNumber":"0x61","transactionHash":"0x9a2a68cc8ca07c10861b362c75136c52f2e94609639bc515bafa063c6764a2a7","transactionIndex":"0x0","blockHash":"0x3a874e7efd0c3802b48dfd3d50d086443d6a242649d1e6251587da1556173471","logIndex":"0x0","removed":false}]`
	unbondLogs                    = `[{"address":"0x0165878a594ca255338adfa4d48449f69242eb8f","topics":["0x815134b5aa3c5caabcdaf305b7dc586ca56abde81012388563e8c4c2174a90f5","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266","0x000000000000000000000000a12daaf3c2c1505b288353b62cb3b4021c60c344"],"data":"0x0000000000000000000000000000000000000000000000000000000000000064","blockNumber":"0x63","transactionHash":"0xdc803524c4a7bc0644c5c7bcf114e42a1a8a21505369c25b9d263dc65fbd4e0a","transactionIndex":"0x0","blockHash":"0xb0f057ae359948dd99fb55c21c5f664fa42e80f49877905074fe5d64cefc3e6b","logIndex":"0x0","removed":false}]`
	withdrawLogs                  = `[{"address":"0x0165878a594ca255338adfa4d48449f69242eb8f","topics":["0x9b1bfa7fa9ee420a16e124f794c35ac9f90472acc99140eb2f6447c714cad8eb","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266"],"data":"0x0000000000000000000000000000000000000000000000000000000000000064","blockNumber":"0x64","transactionHash":"0x231423722b32154eff7980e3b246a8aadd6156544fa82b9919132b26dc3ee059","transactionIndex":"0x0","blockHash":"0xf4ff3a0c5eba436a13b9a88a2a0a31d36b7ca9fd4e32c349201be5dc6fb343c5","logIndex":"0x0","removed":false}]`
	withdrawToLogs                = `[{"address":"0x0165878a594ca255338adfa4d48449f69242eb8f","topics":["0x9b1bfa7fa9ee420a16e124f794c35ac9f90472acc99140eb2f6447c714cad8eb","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266","0x000000000000000000000000e53e6e952cf156b9f58a2a82da5ea537102ba484"],"data":"0x0000000000000000000000000000000000000000000000000000000000000064","blockNumber":"0x65","transactionHash":"0xdd5b951aa8d812009e9c648f9c4bc441e38ffd080c4d618d136677a0e894b53d","transactionIndex":"0x0","blockHash":"0xee2b6426f79e500ad96af8ecbf42b0b5d00a6846bb0a8f16da1e79d01b4c4554","logIndex":"0x0","removed":false}]`
	transferLogs                  = `[{"address":"0x0165878a594ca255338adfa4d48449f69242eb8f","topics":["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266","0x000000000000000000000000e53e6e952cf156b9f58a2a82da5ea537102ba484"],"data":"0x0000000000000000000000000000000000000000000000000000000000000064","blockNumber":"0x67","transactionHash":"0x7bfc149ddfa53bbe0a88a8cb02b105107f22155c143dae8702405915fffc5cdf","transactionIndex":"0x0","blockHash":"0xd39a6bb82d24ac55e9327b96489fd64ad8538b8f8e57c31b8e309680cbb810dd","logIndex":"0x0","removed":false}]`
	voteLogs                      = `[{"address":"0x0165878a594ca255338adfa4d48449f69242eb8f","topics":["0x456317ab0c14ca006fefb6a12ba5ce82adf54fd3cf455be6b1286e1f612d3d19","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266"],"data":"0x00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000086d65746164617461000000000000000000000000000000000000000000000000","blockNumber":"0x68","transactionHash":"0xb4e020bca0d786bcd2c3bb167d942792aef5892606dd2c57e3d5fa718f55898e","transactionIndex":"0x0","blockHash":"0xbdb9ddc08e4610aa39e7cb9e997da64e770c6c099db9a4a71c9312e3a5450806","logIndex":"0x0","removed":false}]`
	setRewardRecipientLogs        = `[{"address":"0x0165878a594ca255338adfa4d48449f69242eb8f","topics":["0xc6b66e0e282673c442421e1c6b89458b7631f26f5dcd0b2b216c45831ca1d7d5","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266","0x000000000000000000000000e53e6e952cf156b9f58a2a82da5ea537102ba484"],"data":"0x","blockNumber":"0x69","transactionHash":"0xe1adc744d74e13deb3780f2bcba62a615f7cec4ae762e73b93434b3aa83debd0","transactionIndex":"0x0","blockHash":"0xe9a5d23dd09d4700d8aca53c70a6af7818d92e672fb5c8bf30fdb836b6267ddb","logIndex":"0x0","removed":false}]`
	authorizeLogs                 = `[{"address":"0x0165878a594ca255338adfa4d48449f69242eb8f","topics":["0x38cf2222fd9da5a0ceb8506c44fa5bcd7011fe00163dc14950d5628d8c301f04","0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266"],"data":"0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000890a86010a1c2f636f736d6f732e62616e6b2e763162657461312e4d736753656e6412660a2a307866333946643665353161616438384636463463653661423838323732373963666646623932323636122a3078653533453645393532636631353662396635384132413832646135656135333731303242613438341a0c0a05757465737412033130300000000000000000000000000000000000000000000000","blockNumber":"0x6b","transactionHash":"0x388f44250f49fac18c824270669c5340f4c342d7d09b0f1f8bce39394cfba8a4","transactionIndex":"0x0","blockHash":"0x39ec5ee55b9210560db27c4fd8a20cd460b53aafecac12a74023dda9fd505a62","logIndex":"0x0","removed":false}]`
)

func sequencerProxyContractABI(t *testing.T) abi.ABI {
	var contractAbi abi.ABI
	err := contractAbi.UnmarshalJSON([]byte(sidecartypes.SequencerProxyContractABI))
	require.NoError(t, err)
	return contractAbi
}

func eventFromMsg(t *testing.T, msg sdk.Msg) *sidecartypes.Event {
	data, err := AuthorizeTxFromMsg(msg)
	require.NoError(t, err)

	authorizeEvent := sidecartypes.AuthorizeEvent{
		Sender: senderAddress,
		Data:   data,
	}
	authorizeEventBz, err := authorizeEvent.Marshal()
	require.NoError(t, err)

	event := &sidecartypes.Event{
		EventType:       sidecartypes.AuthorizeEventName,
		Data:            authorizeEventBz,
		ContractAddress: sequencerProxyContractAddress,
	}
	return event
}

func eventFromDepositEvent(t *testing.T, depositEvent sidecartypes.DepositEvent) *sidecartypes.Event {
	depositEventBz, err := depositEvent.Marshal()
	require.NoError(t, err)

	return &sidecartypes.Event{
		EventType:       sidecartypes.DepositEventName,
		Data:            depositEventBz,
		ContractAddress: sequencerProxyContractAddress,
	}
}

func TestExtractLogDataToEvent_AuthorizeTxFromEvent(t *testing.T) {
	sequencerProxyABI := sequencerProxyContractABI(t)
	amountParsed := sdkmath.NewInt(amount)

	testCases := []struct {
		name        string
		logs        string
		getExpEvent func() *sidecartypes.Event
		expErrMsg   string
	}{
		{
			name: "Deposit event via Deposit",
			logs: depositLogs,
			getExpEvent: func() *sidecartypes.Event {
				return eventFromDepositEvent(t, sidecartypes.DepositEvent{
					Depositor: senderAddress,
					Recipient: senderAddress, // sender deposits to themselves
					Amount:    strconv.FormatInt(amount, 10),
					Lockup:    "0",
				})
			},
		},
		{
			name: "Deposit event via DepositFor",
			logs: depositForLogs,
			getExpEvent: func() *sidecartypes.Event {
				return eventFromDepositEvent(t, sidecartypes.DepositEvent{
					Depositor: senderAddress,
					Recipient: receiverAddress,
					Amount:    strconv.FormatInt(amount, 10),
					Lockup:    "0",
				})
			},
		},
		{
			name: "Deposit event with lockup",
			logs: depositWithLockupLogs,
			getExpEvent: func() *sidecartypes.Event {
				return eventFromDepositEvent(t, sidecartypes.DepositEvent{
					Depositor: senderAddress,
					Recipient: senderAddress, // sender deposits to themselves
					Amount:    strconv.FormatInt(amount, 10),
					Lockup:    vestingDurationSeconds,
				})
			},
		},
		{
			name: "Delegate event",
			logs: delegateLogs,
			getExpEvent: func() *sidecartypes.Event {
				return eventFromMsg(t, &stakingtypes.MsgDelegate{
					DelegatorAddress: senderAddress,
					ValidatorAddress: validator1Address,
					Amount:           sdk.NewCoin(bridgeDenom, amountParsed),
				})
			},
		},
		{
			name: "Redelegate event",
			logs: redelegateLogs,
			getExpEvent: func() *sidecartypes.Event {
				return eventFromMsg(t, &stakingtypes.MsgBeginRedelegate{
					DelegatorAddress:    senderAddress,
					ValidatorSrcAddress: validator1Address,
					ValidatorDstAddress: validator2Address,
					Amount:              sdk.NewCoin(bridgeDenom, amountParsed),
				})
			},
		},
		{
			name: "ClaimRewards event",
			logs: claimRewardsLogs,
			getExpEvent: func() *sidecartypes.Event {
				return eventFromMsg(t, &distributiontypes.MsgWithdrawDelegatorReward{
					DelegatorAddress: senderAddress,
					ValidatorAddress: validator1Address,
				})
			},
		},
		{
			name: "Unbond event",
			logs: unbondLogs,
			getExpEvent: func() *sidecartypes.Event {
				return eventFromMsg(t, &stakingtypes.MsgUndelegate{
					DelegatorAddress: senderAddress,
					ValidatorAddress: validator1Address,
					Amount:           sdk.NewCoin(bridgeDenom, amountParsed),
				})
			},
		},
		{
			name: "Withdraw event via Withdraw",
			logs: withdrawLogs,
			getExpEvent: func() *sidecartypes.Event {
				return eventFromMsg(t, &bridgetypes.MsgWithdrawToEthereum{
					From:   senderAddress,
					To:     senderAddress, // sender withdraws to themselves
					Amount: sdk.NewCoin(bridgeDenom, amountParsed),
				})
			},
		},
		{
			name: "Withdraw event via WithdrawTo",
			logs: withdrawToLogs,
			getExpEvent: func() *sidecartypes.Event {
				return eventFromMsg(t, &bridgetypes.MsgWithdrawToEthereum{
					From:   senderAddress,
					To:     receiverAddress,
					Amount: sdk.NewCoin(bridgeDenom, amountParsed),
				})
			},
		},
		{
			name: "Transfer event",
			logs: transferLogs,
			getExpEvent: func() *sidecartypes.Event {
				return eventFromMsg(t, &banktypes.MsgSend{
					FromAddress: senderAddress,
					ToAddress:   receiverAddress,
					Amount:      sdk.NewCoins(sdk.NewCoin(bridgeDenom, amountParsed)),
				})
			},
		},
		{
			name: "Vote event",
			logs: voteLogs,
			getExpEvent: func() *sidecartypes.Event {
				return eventFromMsg(t, &govtypesv1.MsgVote{
					ProposalId: voteProposalId,
					Voter:      senderAddress,
					Option:     govtypesv1.VoteOption(voteOption),
					Metadata:   voteMetadata,
				})
			},
		},
		{
			name: "SetRewardRecipient event",
			logs: setRewardRecipientLogs,
			getExpEvent: func() *sidecartypes.Event {
				return eventFromMsg(t, &distributiontypes.MsgSetWithdrawAddress{
					DelegatorAddress: senderAddress,
					WithdrawAddress:  receiverAddress,
				})
			},
		},
		{
			name: "Authorize event",
			logs: authorizeLogs,
			getExpEvent: func() *sidecartypes.Event {
				return eventFromMsg(t, &banktypes.MsgSend{
					FromAddress: senderAddress,
					ToAddress:   receiverAddress,
					Amount:      sdk.NewCoins(sdk.NewCoin(bridgeDenom, amountParsed)),
				})
			},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			expectedEvent := tc.getExpEvent()

			// Parse log into Log struct
			var parsedLog []ethereumtypes.Log
			err := json.Unmarshal([]byte(tc.logs), &parsedLog)
			require.NoError(t, err)

			// There might be multiple logs. Check that there is exactly one log that matches the expected log.
			matches := 0
			for _, log := range parsedLog {
				event, err := ExtractLogDataToEvent(log, sequencerProxyABI, bridgeDenom)
				if tc.expErrMsg != "" {
					require.EqualError(t, err, tc.expErrMsg)
					return
				}
				require.NoError(t, err)

				if assert.ObjectsAreEqual(expectedEvent, event) {
					matches += 1
				}
			}

			require.Equal(t, 1, matches)
		})
	}
}
