syntax = "proto3";

package fuelsequencer.commitments;

option go_package = "github.com/fuel-infrastructure/fuel-sequencer/x/commitments/types";

message BridgeCommitmentLeaf {

  uint64 height = 1;

  string last_results_hash = 2;
}

message BridgeCommitmentLeafRaw {

  uint64 height = 1;

  bytes last_results_hash = 2;
}

message BinaryMerkleProof {

  // Total number of items.
  int64 total = 1;

  // Index of item to prove.
  int64 index = 2;

  // Hash of item value.
  string leaf_hash = 3;

  // Hashes from leaf's sibling to a root's child.
  repeated string aunts = 4;
}
