syntax = "proto3";
package fuelsequencer.blob;

import "amino/amino.proto";
import "cosmos/msg/v1/msg.proto";
import "cosmos_proto/cosmos.proto";
import "gogoproto/gogo.proto";
import "google/protobuf/timestamp.proto";
import "fuelsequencer/blob/params.proto";

option go_package = "github.com/fuel-infrastructure/fuel-sequencer/x/blob/types";

// Msg defines the Msg service.
service Msg {
  option (cosmos.msg.v1.service) = true;

  // UpdateParams defines a (governance) operation for updating the module
  // parameters. The authority defaults to the x/gov module account.
  rpc UpdateParams(MsgUpdateParams) returns (MsgUpdateParamsResponse);

  // PostBlobMetadata posts metadata for a blob
  rpc PostBlobMetadata(MsgBlobMetadataTx) returns (MsgBlobMetadataTxResponse);
}

// BlobMetadata represents the metadata for a blob that will be stored on-chain
message BlobMetadata {
  bytes hash = 1;
  uint64 size = 2;
  string topic = 3;
  uint64 nonce = 4;
  google.protobuf.Timestamp timestamp = 5
      [ (gogoproto.nullable) = false, (gogoproto.stdtime) = true ];
}

// MsgUpdateParams is the Msg/UpdateParams request type.
message MsgUpdateParams {
  option (cosmos.msg.v1.signer) = "authority";
  option (amino.name) = "fuelsequencer/x/blob/MsgUpdateParams";

  // authority is the address that controls the module (defaults to x/gov unless
  // overwritten).
  string authority = 1 [ (cosmos_proto.scalar) = "cosmos.AddressString" ];

  // params defines the module parameters to update.
  //
  // NOTE: All parameters must be supplied.
  Params params = 2
      [ (gogoproto.nullable) = false, (amino.dont_omitempty) = true ];
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
message MsgUpdateParamsResponse {}

// MsgBlobMetadataTx represents a transaction that posts blob metadata
message MsgBlobMetadataTx {
  option (cosmos.msg.v1.signer) = "sender";

  bytes blob_hash = 1;
  uint64 size = 2;
  string topic = 3;
  uint64 nonce = 4;
  string sender = 5;
}

// MsgBlobMetadataTxResponse defines the Msg/BlobMetadataTx response type.
message MsgBlobMetadataTxResponse {}