// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fuelsequencer/commitments/types.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type BridgeCommitmentLeaf struct {
	Height uint64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	// The ResultsHash of blocks is derived at (Height + 1) in the LastResultsHash
	// variable in the Tendermint block header, ref:
	// https://github.com/cometbft/cometbft/blob/v0.38.5/proto/tendermint/types/types.proto#L66.
	// Thus, to reconstruct this root at Height X, you would need the transactions
	// results from Height X - 1.
	LastResultsHash string `protobuf:"bytes,2,opt,name=last_results_hash,json=lastResultsHash,proto3" json:"last_results_hash,omitempty"`
}

func (m *BridgeCommitmentLeaf) Reset()         { *m = BridgeCommitmentLeaf{} }
func (m *BridgeCommitmentLeaf) String() string { return proto.CompactTextString(m) }
func (*BridgeCommitmentLeaf) ProtoMessage()    {}
func (*BridgeCommitmentLeaf) Descriptor() ([]byte, []int) {
	return fileDescriptor_90526fd5c330b101, []int{0}
}
func (m *BridgeCommitmentLeaf) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BridgeCommitmentLeaf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BridgeCommitmentLeaf.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BridgeCommitmentLeaf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BridgeCommitmentLeaf.Merge(m, src)
}
func (m *BridgeCommitmentLeaf) XXX_Size() int {
	return m.Size()
}
func (m *BridgeCommitmentLeaf) XXX_DiscardUnknown() {
	xxx_messageInfo_BridgeCommitmentLeaf.DiscardUnknown(m)
}

var xxx_messageInfo_BridgeCommitmentLeaf proto.InternalMessageInfo

func (m *BridgeCommitmentLeaf) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BridgeCommitmentLeaf) GetLastResultsHash() string {
	if m != nil {
		return m.LastResultsHash
	}
	return ""
}

type BridgeCommitmentLeafRaw struct {
	Height uint64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	// The ResultsHash of blocks is derived at (Height + 1) in the LastResultsHash
	// variable in the Tendermint block header, ref:
	// https://github.com/cometbft/cometbft/blob/v0.38.5/proto/tendermint/types/types.proto#L66.
	// Thus, to reconstruct this root at Height X, you would need the transactions
	// results from Height X - 1.
	LastResultsHash []byte `protobuf:"bytes,2,opt,name=last_results_hash,json=lastResultsHash,proto3" json:"last_results_hash,omitempty"`
}

func (m *BridgeCommitmentLeafRaw) Reset()         { *m = BridgeCommitmentLeafRaw{} }
func (m *BridgeCommitmentLeafRaw) String() string { return proto.CompactTextString(m) }
func (*BridgeCommitmentLeafRaw) ProtoMessage()    {}
func (*BridgeCommitmentLeafRaw) Descriptor() ([]byte, []int) {
	return fileDescriptor_90526fd5c330b101, []int{1}
}
func (m *BridgeCommitmentLeafRaw) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BridgeCommitmentLeafRaw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BridgeCommitmentLeafRaw.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BridgeCommitmentLeafRaw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BridgeCommitmentLeafRaw.Merge(m, src)
}
func (m *BridgeCommitmentLeafRaw) XXX_Size() int {
	return m.Size()
}
func (m *BridgeCommitmentLeafRaw) XXX_DiscardUnknown() {
	xxx_messageInfo_BridgeCommitmentLeafRaw.DiscardUnknown(m)
}

var xxx_messageInfo_BridgeCommitmentLeafRaw proto.InternalMessageInfo

func (m *BridgeCommitmentLeafRaw) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BridgeCommitmentLeafRaw) GetLastResultsHash() []byte {
	if m != nil {
		return m.LastResultsHash
	}
	return nil
}

type BinaryMerkleProof struct {
	// Total number of items.
	Total int64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// Index of item to prove.
	Index int64 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// Hash of item value.
	LeafHash string `protobuf:"bytes,3,opt,name=leaf_hash,json=leafHash,proto3" json:"leaf_hash,omitempty"`
	// Hashes from leaf's sibling to a root's child.
	Aunts []string `protobuf:"bytes,4,rep,name=aunts,proto3" json:"aunts,omitempty"`
}

func (m *BinaryMerkleProof) Reset()         { *m = BinaryMerkleProof{} }
func (m *BinaryMerkleProof) String() string { return proto.CompactTextString(m) }
func (*BinaryMerkleProof) ProtoMessage()    {}
func (*BinaryMerkleProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_90526fd5c330b101, []int{2}
}
func (m *BinaryMerkleProof) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BinaryMerkleProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BinaryMerkleProof.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BinaryMerkleProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BinaryMerkleProof.Merge(m, src)
}
func (m *BinaryMerkleProof) XXX_Size() int {
	return m.Size()
}
func (m *BinaryMerkleProof) XXX_DiscardUnknown() {
	xxx_messageInfo_BinaryMerkleProof.DiscardUnknown(m)
}

var xxx_messageInfo_BinaryMerkleProof proto.InternalMessageInfo

func (m *BinaryMerkleProof) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *BinaryMerkleProof) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *BinaryMerkleProof) GetLeafHash() string {
	if m != nil {
		return m.LeafHash
	}
	return ""
}

func (m *BinaryMerkleProof) GetAunts() []string {
	if m != nil {
		return m.Aunts
	}
	return nil
}

func init() {
	proto.RegisterType((*BridgeCommitmentLeaf)(nil), "fuelsequencer.commitments.BridgeCommitmentLeaf")
	proto.RegisterType((*BridgeCommitmentLeafRaw)(nil), "fuelsequencer.commitments.BridgeCommitmentLeafRaw")
	proto.RegisterType((*BinaryMerkleProof)(nil), "fuelsequencer.commitments.BinaryMerkleProof")
}

func init() {
	proto.RegisterFile("fuelsequencer/commitments/types.proto", fileDescriptor_90526fd5c330b101)
}

var fileDescriptor_90526fd5c330b101 = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xcd, 0x4a, 0x03, 0x31,
	0x14, 0x85, 0x3b, 0x4e, 0x2d, 0x36, 0x08, 0xd2, 0xa1, 0x68, 0x45, 0x08, 0xa5, 0x20, 0x14, 0xc1,
	0x76, 0xe1, 0x13, 0x58, 0x37, 0x2e, 0x14, 0x24, 0xcb, 0x8a, 0x94, 0xb4, 0xbd, 0xd3, 0x04, 0xd3,
	0xa4, 0x26, 0x37, 0xd8, 0xbe, 0x85, 0x8f, 0xe5, 0xb2, 0x4b, 0x97, 0xd2, 0x79, 0x11, 0xc9, 0x44,
	0xfc, 0xa1, 0x6e, 0x5c, 0x9e, 0x2f, 0x37, 0x5f, 0xc8, 0x3d, 0xe4, 0x34, 0xf7, 0xa0, 0x1c, 0x3c,
	0x79, 0xd0, 0x13, 0xb0, 0xfd, 0x89, 0x99, 0xcf, 0x25, 0xce, 0x41, 0xa3, 0xeb, 0xe3, 0x6a, 0x01,
	0xae, 0xb7, 0xb0, 0x06, 0x4d, 0x76, 0xfc, 0x6b, 0xac, 0xf7, 0x63, 0xac, 0x33, 0x24, 0xcd, 0x81,
	0x95, 0xd3, 0x19, 0x5c, 0x7d, 0xc1, 0x1b, 0xe0, 0x79, 0x76, 0x48, 0x6a, 0x02, 0xe4, 0x4c, 0x60,
	0x2b, 0x69, 0x27, 0xdd, 0x2a, 0xfb, 0x4c, 0xd9, 0x19, 0x69, 0x28, 0xee, 0x70, 0x64, 0xc1, 0x79,
	0x85, 0x6e, 0x24, 0xb8, 0x13, 0xad, 0x9d, 0x76, 0xd2, 0xad, 0xb3, 0x83, 0x70, 0xc0, 0x22, 0xbf,
	0xe6, 0x4e, 0x74, 0x1e, 0xc8, 0xd1, 0x5f, 0x6e, 0xc6, 0x9f, 0xff, 0xaf, 0xdf, 0xdf, 0xd6, 0x5b,
	0xd2, 0x18, 0x48, 0xcd, 0xed, 0xea, 0x16, 0xec, 0xa3, 0x82, 0x3b, 0x6b, 0x4c, 0x9e, 0x35, 0xc9,
	0x2e, 0x1a, 0xe4, 0xaa, 0xf4, 0xa6, 0x2c, 0x86, 0x40, 0xa5, 0x9e, 0xc2, 0xb2, 0x54, 0xa5, 0x2c,
	0x86, 0xec, 0x84, 0xd4, 0x15, 0xf0, 0x3c, 0x3e, 0x92, 0x96, 0x7f, 0xd8, 0x0b, 0x20, 0xd8, 0xc3,
	0x15, 0xee, 0x35, 0xba, 0x56, 0xb5, 0x9d, 0x76, 0xeb, 0x2c, 0x86, 0xc1, 0xfd, 0xeb, 0x86, 0x26,
	0xeb, 0x0d, 0x4d, 0xde, 0x37, 0x34, 0x79, 0x29, 0x68, 0x65, 0x5d, 0xd0, 0xca, 0x5b, 0x41, 0x2b,
	0xc3, 0xcb, 0x99, 0x44, 0xe1, 0xc7, 0x61, 0xb9, 0xfd, 0xb0, 0xee, 0x73, 0xa9, 0x73, 0xcb, 0x1d,
	0x5a, 0x3f, 0x41, 0x6f, 0x21, 0xb2, 0xef, 0xaa, 0x96, 0xdb, 0x65, 0x8d, 0x6b, 0x65, 0x5b, 0x17,
	0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x51, 0x0c, 0x69, 0x61, 0xd6, 0x01, 0x00, 0x00,
}

func (m *BridgeCommitmentLeaf) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BridgeCommitmentLeaf) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BridgeCommitmentLeaf) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.LastResultsHash) > 0 {
		i -= len(m.LastResultsHash)
		copy(dAtA[i:], m.LastResultsHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.LastResultsHash)))
		i--
		dAtA[i] = 0x12
	}
	if m.Height != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BridgeCommitmentLeafRaw) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BridgeCommitmentLeafRaw) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BridgeCommitmentLeafRaw) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.LastResultsHash) > 0 {
		i -= len(m.LastResultsHash)
		copy(dAtA[i:], m.LastResultsHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.LastResultsHash)))
		i--
		dAtA[i] = 0x12
	}
	if m.Height != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BinaryMerkleProof) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BinaryMerkleProof) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BinaryMerkleProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Aunts) > 0 {
		for iNdEx := len(m.Aunts) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Aunts[iNdEx])
			copy(dAtA[i:], m.Aunts[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.Aunts[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.LeafHash) > 0 {
		i -= len(m.LeafHash)
		copy(dAtA[i:], m.LeafHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.LeafHash)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Index != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x10
	}
	if m.Total != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Total))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BridgeCommitmentLeaf) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovTypes(uint64(m.Height))
	}
	l = len(m.LastResultsHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *BridgeCommitmentLeafRaw) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovTypes(uint64(m.Height))
	}
	l = len(m.LastResultsHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *BinaryMerkleProof) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Total != 0 {
		n += 1 + sovTypes(uint64(m.Total))
	}
	if m.Index != 0 {
		n += 1 + sovTypes(uint64(m.Index))
	}
	l = len(m.LeafHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if len(m.Aunts) > 0 {
		for _, s := range m.Aunts {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BridgeCommitmentLeaf) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BridgeCommitmentLeaf: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BridgeCommitmentLeaf: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastResultsHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastResultsHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BridgeCommitmentLeafRaw) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BridgeCommitmentLeafRaw: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BridgeCommitmentLeafRaw: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastResultsHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastResultsHash = append(m.LastResultsHash[:0], dAtA[iNdEx:postIndex]...)
			if m.LastResultsHash == nil {
				m.LastResultsHash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BinaryMerkleProof) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BinaryMerkleProof: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BinaryMerkleProof: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			m.Total = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Total |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeafHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LeafHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Aunts", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Aunts = append(m.Aunts, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
