// Test suite inspired by https://github.com/PeggyJV/sommelier/tree/v7.0.1/integration_tests

package testsuite

import (
	"bytes"
	"context"
	"fmt"
	"math/big"
	"os"
	osuser "os/user"
	"path/filepath"
	"regexp"
	"strconv"
	"testing"
	"time"

	sdkmath "cosmossdk.io/math"
	rpchttp "github.com/cometbft/cometbft/rpc/client/http"
	sdk "github.com/cosmos/cosmos-sdk/types"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/ethclient"
	"github.com/fuel-infrastructure/fuel-sequencer/app"
	"github.com/ory/dockertest/v3"
	"github.com/ory/dockertest/v3/docker"
	"github.com/stretchr/testify/suite"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest"
)

func init() {
	app.InitSDKConfig()
	app.InitCometBFTConfig()

	sdk.DefaultBondDenom = BridgeDenom
}

const (
	ethBlockTimeSeconds = 3

	BridgeDenom = "utest"

	// Gas configs
	minGasPrices = "0.01"
	defaultTxGas = 1000000

	// Genesis configs
	supplyDeltaPeriod      = uint64(10)       // default - can be overridden
	governanceVotingPeriod = time.Second * 20 // default - can be overridden

	// FuelSequencer validator configs
	fuelSequencerValidatorDefaultHome = "/home/fuelsequencer/.fuelsequencer"
	fuelSequencerBinary               = "fuelsequencerd"

	// Docker configs. These should not be used directly. Instead, use the exported variables which can be overridden.
	fuelSequencerDockerImageRepo      = "fuel-infrastructure/fuel-sequencer"
	fuelSequencerDockerImageTag       = "latest"
	ethereumNodeDockerImageRepo       = "ghcr.io/foundry-rs/foundry"
	ethereumNodeDockerImageTag        = "nightly-4351742481c98adaa9ca3e8642e619aa986b3cee"
	ethereumDeploymentDockerImageRepo = "fuel-rollup/ethereum-deployment"
	ethereumDeploymentDockerImageTag  = "latest"

	// TestSuite configs
	blocksToWaitForGovProposalToPass = uint64(25)

	// DeployerPrivateKey is the private key of the address deploying the contracts.
	// Ref: https://github.com/FuelLabs/fuel-rollup/blob/main/deploy/hardhat/011.set_fuelstreamx_config.ts#L18
	// This is the private key at index 0 in the list of private keys generated by anvil, available in the anvil logs.
	// This is filled-in later on in SetupTest, once the address codec has been initialised.
	DeployerPrivateKey = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
	// GuardianPrivateKey is the private key of the address assigned as the 'guardian'.
	// Ref: https://github.com/FuelLabs/fuel-rollup/blob/923743af2fb3cff122f076c4f490b05486ba4ec3/deploy/hardhat/011.set_fuelstreamx_config.ts#L43-L49
	// This is the private key at index 19 in the list of private keys generated by anvil, available in the anvil logs.
	// This is filled-in later on in SetupTest, once the address codec has been initialised.
	GuardianPrivateKey = "0xdf57089febbacf7ba0bc227dafbffa9fc08a93fdc68e1e42411a14efcf23656e"
	// UserPrivateKey is the private key of an address with no particular elevated privileges.
	// This is the private key at index 1 in the list of private keys generated by anvil, available in the anvil logs.
	// This is filled-in later on in SetupTest, once the address codec has been initialised.
	UserPrivateKey = "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"
)

var (
	BridgeDenomTotalSupply, var1Valid = sdkmath.NewIntFromString("10000000000000000000") // 10 bil x 1e9

	// Balance and staked amount per validator
	initBalance, var2Valid = sdkmath.NewIntFromString("20000000000000000000") // 20 bil x 1e9
	initStaked, var3Valid  = sdkmath.NewIntFromString("2000000000")           // 2e9
	InitBalanceCoin        = sdk.NewCoin(BridgeDenom, initBalance)
	InitStakedCoin         = sdk.NewCoin(BridgeDenom, initStaked)
	// NOTE: we need initStaked to be at least 2x PowerReduction so that if we undelegate half of it, like we do in some
	// of our tests, the validator will still have enough stake to be in the validator set.

	// MNEMONICS dictates how many Sequencer nodes will be created by specifying their mnemonic.
	// The first mnemonic is reused for the Ethereum validator mnemonic.
	MNEMONICS = []string{
		// This corresponds to the typically used signer in the contracts.
		"test test test test test test test test test test test junk",
		// Alice
		"dinner crash nurse casino baby fold race cheese elite column sausage sleep close royal rain over mechanic minimum outdoor conduct cash wagon frog evidence",
		// Bob
		"gaze drama excess raven follow antenna swallow beef upper myself question pitch course ill adult century crisp ice rough match praise sing unveil vintage",
	}

	// Slashing params - 50% of every 10-block window has to be signed.
	// Otherwise, the validator not signing will get slashed by 50%.
	SignedBlocksWindow    = int64(10)
	MinSignedPerWindow    = sdkmath.LegacyMustNewDecFromStr("0.5")
	SlashFractionDowntime = sdkmath.LegacyMustNewDecFromStr("0.5")

	// Inflation params
	Inflation           = sdkmath.LegacyMustNewDecFromStr("0.10") // this is overridden if InflationMin == InflationMax
	InflationRateChange = sdkmath.LegacyMustNewDecFromStr("0.13") // this is not actually used by the custom mint module
	InflationMax        = sdkmath.LegacyMustNewDecFromStr("0.2")  // sets the inflation rate if equal to InflationMin
	InflationMin        = sdkmath.LegacyMustNewDecFromStr("0.07") // sets the inflation rate if equal to InflationMax
	GoalBonded          = sdkmath.LegacyMustNewDecFromStr("0.67")
	BlocksPerYear       = uint64(6311520)

	// NOTE: the below contract address are obtained from the logs of the Ethereum deployment Docker container.

	// FuelStreamXContractAddressStr is the address of the contract that holds bridge commitments.
	FuelStreamXContractAddressStr = ""
	FuelStreamXContractAddress    = common.Address{}
	// TokenContractAddressStr is the address of the FUEL V2 token contract.
	TokenContractAddressStr = ""
	TokenContractAddress    = common.Address{}
	// SequencerInterfaceContractAddressStr is the address of the contract that has the batchAuthorize function.
	SequencerInterfaceContractAddressStr = ""
	SequencerInterfaceContractAddress    = common.Address{}
	// MigratedTokenContractAddressStr is the address of the FUEL V1 token contract.
	MigratedTokenContractAddressStr = ""
	MigratedTokenContractAddress    = common.Address{}
	// VaultContractAddressStr is the address of the vault contract.
	VaultContractAddressStr = ""
	VaultContractAddress    = common.Address{}
	// SequencerProxyContractAddressStr is the address of the contract that emits Deposit and Authorize events.
	SequencerProxyContractAddressStr = ""
	SequencerProxyContractAddress    = common.Address{}
	// TokenMigratorContractAddressStr is the address of the V1 to V2 token migrator contract.
	TokenMigratorContractAddressStr = ""
	TokenMigratorContractAddress    = common.Address{}
	// FaucetContractAddressStr is the address of the token faucet contract.
	FaucetContractAddressStr = ""
	FaucetContractAddress    = common.Address{}

	// Vesting params

	VestingStartTimeDelay = time.Duration(0)         // Set to zero because latest requirements indicate no cliffs
	VestingDuration2Years = time.Hour * 24 * 365 * 2 // 2 years, to be used when migrating V1 tokens to V2

	// V1 to V2 migration

	// MigrateAmountUpscalingFactor counteracts the DECIMALS_DOWNSCALING_FACTOR of 1e9 applied by the migrator contract.
	MigrateAmountUpscalingFactor = big.NewInt(1000000000)

	// MigrationRatio is the factor by which v1 tokens will be converted to v2 tokens. i.e. 1 v1 token = 100 v2 tokens
	MigrationRatio = big.NewInt(100)

	// Logging

	LogLevel = zaptest.Level(zap.DebugLevel)
)

type E2ETestSuite struct {
	suite.Suite

	log *zap.Logger

	Chain         *chain
	dockerPool    *dockertest.Pool
	dockerNetwork *dockertest.Network

	ethNodeResource       *dockertest.Resource
	ethDeploymentResource *dockertest.Resource
	valResources          []*dockertest.Resource

	// govProposalIdCounter keeps track of the latest governance proposal ID, so we can vote using the ID.
	govProposalIdCounter int

	// genesisOverrides are extra changes applied to genesis before the Sequencer is started. For these overrides to be
	// applied, SetupTest needs to be overridden so that genesisOverrides can be changed before invoking SetupTest.
	GenesisOverrides *ModifyGenesisFunc

	// Docker images, which can be overridden
	FuelSequencerDockerImageRepo      string
	FuelSequencerDockerImageTag       string
	EthereumNodeDockerImageRepo       string
	EthereumNodeDockerImageTag        string
	EthereumDeploymentDockerImageRepo string
	EthereumDeploymentDockerImageTag  string

	// SeqKeys are the FuelSequencer wallets derived from the above MNEMONICS, with hex versions of the addresses.
	// This is filled-in later on in SetupTest, once the address codec has been initialised.
	SeqKeys []*SequencerKey

	// EthKeys are the Ethereum wallets derived from the above MNEMONICS, with Bech32 versions of the addresses.
	// This is filled-in later on in SetupTest, once the address codec has been initialised.
	EthKeys []*EthereumKey

	// EthGuardian is the Ethereum key derived from GuardianPrivateKey.
	EthGuardian *EthereumKey

	// EthDeployer is the Ethereum key derived from DeployerPrivateKey.
	EthDeployer *EthereumKey

	// EthUser is the Ethereum key derived from UserPrivateKey.
	EthUser *EthereumKey
}

func (s *E2ETestSuite) SetupSuite() {

	// Set Docker images, which can be overridden
	s.FuelSequencerDockerImageRepo = fuelSequencerDockerImageRepo
	s.FuelSequencerDockerImageTag = fuelSequencerDockerImageTag
	s.EthereumNodeDockerImageRepo = ethereumNodeDockerImageRepo
	s.EthereumNodeDockerImageTag = ethereumNodeDockerImageTag
	s.EthereumDeploymentDockerImageRepo = ethereumDeploymentDockerImageRepo
	s.EthereumDeploymentDockerImageTag = ethereumDeploymentDockerImageTag
}

func (s *E2ETestSuite) SetupTest() {
	if testing.Short() {
		s.T().Skip()
	}

	s.T().Log("setting up E2E test...")

	// Check vars were set without issues
	s.Require().True(var1Valid)
	s.Require().True(var2Valid)
	s.Require().True(var3Valid)

	s.log = zaptest.NewLogger(s.T(), LogLevel)

	var err error
	s.Chain, err = newChain(len(MNEMONICS))
	s.Require().NoError(err)
	s.dockerPool, err = dockertest.NewPool("")
	s.Require().NoError(err)
	s.dockerNetwork, err = s.dockerPool.CreateNetwork(fmt.Sprintf("%s-testnet", s.Chain.id))
	s.Require().NoError(err)

	s.T().Logf("starting E2E infrastructure; Chain-id: %s; datadir: %s", s.Chain.id, s.Chain.dataDir)

	// Derive and print the Ethereum keys with the hex and bech32 representation of the addresses.
	for _, mnemonic := range MNEMONICS {
		s.EthKeys = append(s.EthKeys, mustNewEthereumKeyFromMnemonic(mnemonic))
	}
	s.EthGuardian = mustNewEthereumKeyFromPrivateKey(GuardianPrivateKey)
	s.EthDeployer = mustNewEthereumKeyFromPrivateKey(DeployerPrivateKey)
	s.EthUser = mustNewEthereumKeyFromPrivateKey(UserPrivateKey)
	s.T().Logf("ethereum keys:")
	for _, key := range append(s.EthKeys, s.EthGuardian, s.EthDeployer, s.EthUser) {
		s.T().Logf("\tpriv:%s hex:%s seq:%s", key.PrivateKeyHex, key.AddressHex, key.AddressSeq)
	}

	// Derive and print the Sequencer keys with the hex and bech32 representation of the addresses.
	for _, mnemonic := range MNEMONICS {
		s.SeqKeys = append(s.SeqKeys, mustNewSequencerKeyFromMnemonic(mnemonic))
	}
	s.T().Logf("sequencer keys:")
	for _, key := range s.SeqKeys {
		s.T().Logf("\tacc:%s val:%s hex:%s", key.AddressSeq, key.ValAddressSeq, key.AddressHex)
	}

	// Initialization
	s.initFuelSequencerNodes(MNEMONICS)

	// Run Ethereum node and deploy contracts
	s.runEthereumNodeContainer()
	s.runEthereumDeploymentContainer()
	s.initEthereumRPCClient()

	// Deployment is done so we can get the contract addresses
	s.setContractAddresses()

	// Run FuelSequencer nodes and sidecars
	s.initFuelSequencerGenesis()
	s.initFuelSequencerValidatorConfigs()
	s.RunSequencerValidators()
	s.initGRPCClients()
	s.initRPCClient()
	s.initSidecarClient()

	// We need the genesis header for solidity smart contracts
	err = s.WaitForSequencerBlocks(s.Ctx(), 1, time.Minute)
	s.Require().NoError(err)

	// Get genesis header
	genesisBlockHeaderHash, err := s.Chain.GetBlockHeaderHash(s.Ctx(), 1)
	s.Require().NoError(err)

	// Check that the deployer has the DEFAULT_ADMIN_ROLE, allowing them to set the genesis header
	hasRole, err := s.QueryEthereumAddressHasRole_FuelStreamXContract(
		s.Ctx(), s.EthDeployer.Address, common.HexToHash(DefaultAdminRoleHash),
	)
	s.Require().NoError(err)
	s.Require().True(hasRole)

	// Set the genesis header
	data := PackUpdateGenesisStateMessage(1, common.BytesToHash(genesisBlockHeaderHash))
	_, err = s.SendEthTransactionToFuelStreamXContractAsDeployer(data)
	s.Require().NoError(err)

	// Reset the proposal counter since we're starting a new chain.
	s.govProposalIdCounter = 1
}

func (s *E2ETestSuite) TearDownTest() {
	if str := os.Getenv("E2E_SKIP_CLEANUP"); len(str) > 0 {
		skipCleanup, err := strconv.ParseBool(str)
		s.Require().NoError(err)

		if skipCleanup {
			s.T().Log("skipping teardown")
			return
		}
	}

	s.T().Log("tearing down e2e integration test suite...")

	s.Require().NoError(s.Chain.rpcClient.Stop())
	s.Require().NoError(os.RemoveAll(s.Chain.dataDir))
	s.Require().NoError(s.dockerPool.Purge(s.ethNodeResource))
	s.Require().NoError(s.dockerPool.Purge(s.ethDeploymentResource))

	for _, vc := range s.valResources {
		s.Require().NoError(s.dockerPool.Purge(vc))
	}

	s.Require().NoError(s.dockerPool.RemoveNetwork(s.dockerNetwork))

	s.govProposalIdCounter = 1
	s.GenesisOverrides = nil

	s.SeqKeys = nil
	s.EthKeys = nil
	s.EthGuardian = nil
	s.EthDeployer = nil
	s.EthUser = nil
}

// initFuelSequencerNodes initialises FuelSequencer nodes with mnemonics (if specified) or random keys.
// It also sets up the genesis file using the first validator and copies it to all other validator nodes.
func (s *E2ETestSuite) initFuelSequencerNodes(mnemonics []string) {
	s.Require().NoError(s.Chain.createAndInitFuelSequencerValidators(mnemonics))

	// initialize a genesis file for the first validator
	val0ConfigDir := s.Chain.validators[0].configDir()
	for _, val := range s.Chain.validators {
		s.Require().NoError(
			addGenesisAccount(val0ConfigDir, "", InitBalanceCoin.String(), val.address()),
		)
	}

	// copy the genesis file to the remaining validators
	for _, val := range s.Chain.validators[1:] {
		err := copyFile(
			filepath.Join(val0ConfigDir, "config", "genesis.json"),
			filepath.Join(val.configDir(), "config", "genesis.json"),
		)
		s.Require().NoError(err)
	}
}

func (s *E2ETestSuite) runEthereumNodeContainer() {
	s.T().Log("starting Ethereum node container...")
	var err error
	runOpts := dockertest.RunOptions{
		Name:       "ethereum-node",
		Repository: s.EthereumNodeDockerImageRepo,
		Tag:        s.EthereumNodeDockerImageTag,
		NetworkID:  s.dockerNetwork.Network.ID,
		PortBindings: map[docker.Port][]docker.PortBinding{
			"8545/tcp": {{HostIP: "", HostPort: "8545"}},
		},
		ExposedPorts: []string{"8545/tcp"},
		Entrypoint: []string{
			"anvil",
			"--host", "0.0.0.0",
			"--mnemonic", MNEMONICS[0],
			"--accounts", "20",
			"--slots-in-an-epoch", "1",
			"--block-time", fmt.Sprintf("%d", ethBlockTimeSeconds),
			"--mixed-mining",
		},
		Platform: "linux/amd64",
	}

	s.ethNodeResource, err = s.dockerPool.RunWithOptions(
		&runOpts,
		noRestart,
	)
	s.Require().NoError(err)

	ethClient, err := ethclient.Dial(fmt.Sprintf("http://%s", s.ethNodeResource.GetHostPort("8545/tcp")))
	s.Require().NoError(err)

	// Wait for the Ethereum node to respond to a request
	s.Require().Eventually(
		func() bool {
			ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
			defer cancel()

			balance, err := ethClient.BalanceAt(ctx, s.EthKeys[0].Address, nil)
			if err != nil {
				s.T().Logf("error querying balance: %e", err)
				return false
			}

			if balance == nil {
				s.T().Logf("balance for first validator is nil")
			}

			if balance.Cmp(big.NewInt(0)) == 0 {
				s.T().Logf("balance for first validator is %s", balance.String())
				return false
			}

			return true
		},
		1*time.Minute,
		1*time.Second,
		"ethereum node failed to respond",
	)

	s.T().Logf("started Ethereum node container: %s", s.ethNodeResource.Container.ID)
}

func (s *E2ETestSuite) runEthereumDeploymentContainer() {
	s.T().Log("starting Ethereum deployment container to deploy contracts...")
	var err error
	runOpts := dockertest.RunOptions{
		Name:       "ethereum-deployment",
		Repository: s.EthereumDeploymentDockerImageRepo,
		Tag:        s.EthereumDeploymentDockerImageTag,
		NetworkID:  s.dockerNetwork.Network.ID,
		Env: []string{
			"RPC_URL=http://ethereum-node:8545",
		},
		Cmd: []string{"npx", "hardhat", "deploy", "--network", "localhost", "--reset"},
	}

	s.ethDeploymentResource, err = s.dockerPool.RunWithOptions(
		&runOpts,
		noRestart,
	)
	s.Require().NoError(err)

	// Wait for the contracts to be deployed, i.e. for the deployment container to stop
	s.T().Logf("waiting for Ethereum contracts to be deployed...")
	waitContext, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()
	_, err = s.dockerPool.Client.WaitContainerWithContext(s.ethDeploymentResource.Container.ID, waitContext)
	s.Require().NoError(err)
}

func (s *E2ETestSuite) setContractAddresses() {

	logs := s.logsByContainerID(s.ethDeploymentResource.Container.ID)

	getAddressFromFirstMatch := func(reString string) (string, common.Address) {
		re := regexp.MustCompile(reString)
		matches := re.FindAllStringSubmatch(logs, -1)
		s.Require().Len(matches, 1)
		return matches[0][1], common.HexToAddress(matches[0][1])
	}
	FuelStreamXContractAddressStr, FuelStreamXContractAddress = getAddressFromFirstMatch(
		`Deployed FuelStreamX at (0x[a-fA-F0-9]{40})`,
	)
	SequencerInterfaceContractAddressStr, SequencerInterfaceContractAddress = getAddressFromFirstMatch(
		`Deployed SequencerInterface at (0x[a-fA-F0-9]{40})`,
	)
	MigratedTokenContractAddressStr, MigratedTokenContractAddress = getAddressFromFirstMatch(
		`deploying "MigratedToken" \(tx: 0x[a-fA-F0-9]{64}\)\.\.\.: deployed at (0x[a-fA-F0-9]{40})`,
	)
	VaultContractAddressStr, VaultContractAddress = getAddressFromFirstMatch(
		`Deployed Vault at (0x[a-fA-F0-9]{40})`,
	)
	SequencerProxyContractAddressStr, SequencerProxyContractAddress = getAddressFromFirstMatch(
		`Deployed SequencerProxy at (0x[a-fA-F0-9]{40})`,
	)
	TokenMigratorContractAddressStr, TokenMigratorContractAddress = getAddressFromFirstMatch(
		`Deployed TokenMigrator at (0x[a-fA-F0-9]{40})`,
	)
	TokenContractAddressStr, TokenContractAddress = getAddressFromFirstMatch(
		`Deployed Token at (0x[a-fA-F0-9]{40})`,
	)
	FaucetContractAddressStr, FaucetContractAddress = getAddressFromFirstMatch(
		`deploying "TokenFaucet" \(tx: 0x[a-fA-F0-9]{64}\)\.\.\.: deployed at (0x[a-fA-F0-9]{40})`,
	)

	s.T().Logf("%s :: FuelStreamX contract", FuelStreamXContractAddressStr)
	s.T().Logf("%s :: SequencerInterface contract", SequencerInterfaceContractAddressStr)
	s.T().Logf("%s :: MigratedToken contract", MigratedTokenContractAddressStr)
	s.T().Logf("%s :: Vault contract", VaultContractAddressStr)
	s.T().Logf("%s :: SequencerProxy contract", SequencerProxyContractAddressStr)
	s.T().Logf("%s :: TokenMigrator contract", TokenMigratorContractAddressStr)
	s.T().Logf("%s :: Token contract", TokenContractAddressStr)
	s.T().Logf("%s :: Faucet contract", FaucetContractAddressStr)
}

func (s *E2ETestSuite) PauseSequencer(i int) {
	s.Require().NoError(s.dockerPool.Client.PauseContainer(s.valResources[i].Container.ID))
}

func (s *E2ETestSuite) UnpauseSequencer(i int) {
	s.Require().NoError(s.dockerPool.Client.UnpauseContainer(s.valResources[i].Container.ID))
}

func (s *E2ETestSuite) StopSequencer(i int) {
	timeout := uint(1) // seconds before killing the container instead of stopping it gracefully
	s.Require().NoError(s.dockerPool.Client.StopContainer(s.valResources[i].Container.ID, timeout))
}

func (s *E2ETestSuite) RemoveSequencer(i int) {
	opts := docker.RemoveContainerOptions{ID: s.valResources[i].Container.ID, Force: true}
	s.Require().NoError(s.dockerPool.Client.RemoveContainer(opts))
}

func (s *E2ETestSuite) PauseAllSequencerNodes() {
	for i, _ := range s.valResources {
		s.PauseSequencer(i)
	}
}

func (s *E2ETestSuite) UnpauseAllSequencerNodes() {
	for i, _ := range s.valResources {
		s.UnpauseSequencer(i)
	}
}

func (s *E2ETestSuite) StopAllSequencerNodes() {
	for i, _ := range s.valResources {
		s.StopSequencer(i)
	}
}

func (s *E2ETestSuite) RemoveAllSequencerNodes() {
	for i, _ := range s.valResources {
		s.RemoveSequencer(i)
	}
}

func (s *E2ETestSuite) PauseEthereum() {
	s.Require().NoError(s.dockerPool.Client.PauseContainer(s.ethNodeResource.Container.ID))
}

func (s *E2ETestSuite) UnpauseEthereum() {
	s.Require().NoError(s.dockerPool.Client.UnpauseContainer(s.ethNodeResource.Container.ID))
}

func (s *E2ETestSuite) RunSequencerValidators() {
	s.runSequencerValidatorsWithOverrides(nil, nil, true)
}

func (s *E2ETestSuite) ExportSequencerState() string {
	s.runSequencerValidatorsWithOverrides([]string{"fuelsequencerd", "export"}, nil, false)

	matches := s.FindSequencerLogs(regexp.MustCompile("{.*"))
	s.Require().Len(matches, 1)
	genesis := matches[0]

	s.RemoveAllSequencerNodes()

	return genesis
}

func (s *E2ETestSuite) UnsafeResetSequencerState() {
	s.runSequencerValidatorsWithOverrides([]string{"fuelsequencerd", "comet", "unsafe-reset-all"}, nil, false)
	s.RemoveAllSequencerNodes()
}

func (s *E2ETestSuite) runSequencerValidatorsWithOverrides(
	entrypoint []string,
	cmd []string,
	waitForChainToStart bool, // if this is false, the assumption is that we should wait for the container to stop
) {
	s.T().Log("starting validator containers...")

	// Get user from OS to ensure permissions match up when the container writes files.
	user, err := osuser.Current()
	s.Require().NoError(err)

	s.valResources = make([]*dockertest.Resource, len(s.Chain.validators))
	for i, val := range s.Chain.validators {
		runOpts := &dockertest.RunOptions{
			Name:       val.instanceName(),
			NetworkID:  s.dockerNetwork.Network.ID,
			Repository: s.FuelSequencerDockerImageRepo,
			Tag:        s.FuelSequencerDockerImageTag,
			Mounts: []string{
				fmt.Sprintf("%s/:%s", val.configDir(), fuelSequencerValidatorDefaultHome),
			},
			User:       fmt.Sprintf("%s:%s", user.Uid, user.Gid),
			Entrypoint: entrypoint,
			Cmd:        cmd,
			// Assumption: image entrypoint is a script that runs a node and a sidecar.
		}

		// expose the first validator for debugging and communication
		if val.index == 0 {
			runOpts.PortBindings = map[docker.Port][]docker.PortBinding{
				"1317/tcp":  {{HostIP: "", HostPort: "1317"}},  // Sequencer REST
				"9090/tcp":  {{HostIP: "", HostPort: "9090"}},  // Sequencer gRPC
				"26656/tcp": {{HostIP: "", HostPort: "26656"}}, // Sequencer P2P
				"26657/tcp": {{HostIP: "", HostPort: "26657"}}, // Sequencer RPC
				"26660/tcp": {{HostIP: "", HostPort: "26660"}}, // Sequencer Prometheus
				"8080/tcp":  {{HostIP: "", HostPort: "8080"}},  // Sidecar gRPC
				"8081/tcp":  {{HostIP: "", HostPort: "8081"}},  // Sidecar Prometheus
			}
			runOpts.ExposedPorts = []string{
				"1317/tcp", "9090/tcp", "26656/tcp", "26657/tcp", "26660/tcp", "8080/tcp", "8081/tcp",
			}
		}

		resource, err := s.dockerPool.RunWithOptions(runOpts, noRestart)
		s.Require().NoError(err)

		port1317 := resource.Container.NetworkSettings.Ports["1317/tcp"][0].HostPort
		val.hostAPIPort = fmt.Sprintf("tcp://localhost:%s", port1317)
		port9090 := resource.Container.NetworkSettings.Ports["9090/tcp"][0].HostPort
		val.hostGRPCPort = fmt.Sprintf("localhost:%s", port9090)
		port26657 := resource.Container.NetworkSettings.Ports["26657/tcp"][0].HostPort
		val.hostRPCPort = fmt.Sprintf("tcp://localhost:%s", port26657)
		port8080 := resource.Container.NetworkSettings.Ports["8080/tcp"][0].HostPort
		val.sidecarGRPCPort = fmt.Sprintf("localhost:%s", port8080)

		s.valResources[i] = resource
		s.T().Logf("started validator container: %s", resource.Container.ID)
	}
	if !waitForChainToStart {
		// Assume that since we're not waiting for the chain to start, we should wait for the container to stop.
		for _, resource := range s.valResources {
			s.T().Logf("waiting for validator container to stop: %s", resource.Container.ID)
			waitContext, cancel := context.WithTimeout(context.Background(), time.Minute)
			defer cancel()
			_, err = s.dockerPool.Client.WaitContainerWithContext(resource.Container.ID, waitContext)
			s.Require().NoError(err)
		}
		return
	}

	rpcClient, err := rpchttp.New("tcp://localhost:26657", "/websocket")
	s.Require().NoError(err)

	s.Require().Eventually(
		func() bool {
			status, err := rpcClient.Status(context.Background())
			if err != nil {
				s.T().Logf("can't get container status: %s", err.Error())
			}
			if status == nil {
				container, ok := s.dockerPool.ContainerByName("fuelsequencer0")
				if !ok {
					s.T().Logf("no container by 'fuelsequencer0'")
				} else {
					if container.Container.State.Status == "exited" {
						s.Fail("validators exited", "state: %s logs: \n%s", container.Container.State.String(), s.logsByContainerID(container.Container.ID))
						s.T().FailNow()
					}
					s.T().Logf("state: %v, health: %v", container.Container.State.Status, container.Container.State.Health)
				}
				return false
			}

			// let the node produce a few blocks
			if status.SyncInfo.CatchingUp {
				s.T().Logf("catching up: %t", status.SyncInfo.CatchingUp)
				return false
			}
			if status.SyncInfo.LatestBlockHeight < 2 {
				s.T().Logf("block height %d", status.SyncInfo.LatestBlockHeight)
				return false
			}

			return true
		},
		1*time.Minute,
		1*time.Second,
		"validator node failed to produce blocks",
	)
}

func noRestart(config *docker.HostConfig) {
	// in this case we don't want the nodes to restart on failure
	config.RestartPolicy = docker.RestartPolicy{
		Name: "no",
	}
}

func (s *E2ETestSuite) logsByContainerID(id string) string {
	var containerLogsBuf bytes.Buffer
	s.Require().NoError(s.dockerPool.Client.Logs(
		docker.LogsOptions{
			Container:    id,
			OutputStream: &containerLogsBuf,
			ErrorStream:  &containerLogsBuf,
			Stdout:       true,
			Stderr:       true,
		},
	))

	return containerLogsBuf.String()
}

func (s *E2ETestSuite) Ctx() context.Context {
	return context.Background()
}

func (s *E2ETestSuite) Logger() *zap.Logger {
	return s.log.With(
		zap.String("test", s.T().Name()),
	)
}
