syntax = "proto3";
package fuelsequencer.bridge;

import "gogoproto/gogo.proto";
import "cosmos_proto/cosmos.proto";
import "cosmos/base/v1beta1/coin.proto";
import "google/protobuf/any.proto";

option go_package = "github.com/fuel-infrastructure/fuel-sequencer/x/bridge/types";

message EventSupplyDeltaReported {

  // supply_delta is the latest supply delta reported to Ethereum.
  string supply_delta = 1 [
    (cosmos_proto.scalar) = "cosmos.Int",
    (gogoproto.customtype) = "cosmossdk.io/math.Int",
    (gogoproto.nullable) = false
  ];

  // nonce is the latest nonce reported to Ethereum.
  string nonce = 2 [
    (cosmos_proto.scalar) = "cosmos.Int",
    (gogoproto.customtype) = "cosmossdk.io/math.Int",
    (gogoproto.nullable) = false
  ];
}

message EventWithdrawToEthereumReported {

  // nonce uniquely identifies any message that we send to Ethereum.
  string nonce = 1 [
    (cosmos_proto.scalar) = "cosmos.Int",
    (gogoproto.customtype) = "cosmossdk.io/math.Int",
    (gogoproto.nullable) = false
  ];

  // from is the user address on FuelSequencer that is sending the tokens.
  string from = 2;

  // to is the user address on Ethereum that will be receiving the tokens.
  string to = 3;

  // amount is the tokens being sent, which must be the expacted bridge token.
  cosmos.base.v1beta1.Coin amount = 4 [ (gogoproto.nullable) = false ];
}

message EventSendToSequencerEventProcessed {
  // from is the user address on FuelSequencer that is sending the tokens.
  string from = 1;

  // to is the user address on Ethereum that will be receiving the tokens.
  string to = 2;

  // amount is the tokens being sent, which must be the expected bridge token.
  cosmos.base.v1beta1.Coin amount = 3 [ (gogoproto.nullable) = false ];

  // vesting duration encoded in string to prevent loss of precision. Sign is
  // also preserved
  string duration = 4;
}

message EventSendToSequencerEventFailed {
  // event_details is the marshalled event that failed to be processed.
  bytes event_details = 1;
}