syntax = "proto3";

package fuelsequencer.bridge;

import "amino/amino.proto";
import "gogoproto/gogo.proto";
import "cosmos_proto/cosmos.proto";
import "fuelsequencer/bridge/params.proto";
import "fuelsequencer/bridge/supply_delta_info.proto";
import "google/protobuf/timestamp.proto";

option go_package = "github.com/fuel-infrastructure/fuel-sequencer/x/bridge/types";

// GenesisState defines the bridge module's genesis state.
message GenesisState {

  // params defines all the parameters of the module.
  Params params = 1
      [ (gogoproto.nullable) = false, (amino.dont_omitempty) = true ];

  // supply_delta_info is the starting point for changes in the bridge token
  // supply that we should report to Ethereum.
  SupplyDeltaInfo supply_delta_info = 2;

  // last_ethereum_nonce is the last nonce used in messages towards Ethereum.
  // In other words, the next nonce to be used is this value +1.
  bytes last_ethereum_nonce = 3 [
    (cosmos_proto.scalar) = "cosmos.Int",
    (gogoproto.customtype) = "cosmossdk.io/math.Int",
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];

  // last_ethereum_block_synced is the last Ethereum block synced.
  // In other words, the next block to be synced is this value +1.
  uint64 last_ethereum_block_synced = 4;

  // ethereum_event_index_offset is the number of events to skip
  // from the next Ethereum block to query from the Sidecar. This
  // is used if queried events are larger than the maximum block size.
  uint64 ethereum_event_index_offset = 5;

  // last_eth_block_update_time is the time of the last Sequencer
  // block at which consensus was reach by the validators to sync
  // up with an Ethereum block.
  google.protobuf.Timestamp last_eth_block_update_time = 6
      [ (gogoproto.stdtime) = true, (gogoproto.nullable) = false ];

  // last_injected_txs_sequence is the last nonce used in injected txs.
  // In other words, the next nonce to be used is this value +1.
  bytes last_injected_txs_sequence = 7 [
    (cosmos_proto.scalar) = "cosmos.Int",
    (gogoproto.customtype) = "cosmossdk.io/math.Int",
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
}
