syntax = "proto3";

package fuelsequencer.bridge;

import "amino/amino.proto";
import "gogoproto/gogo.proto";
import "fuelsequencer/bridge/params.proto";
import "fuelsequencer/bridge/supply_delta_info.proto";

option go_package = "github.com/fuel-infrastructure/fuel-sequencer/x/bridge/types";

// GenesisState defines the bridge module's genesis state.
message GenesisState {

  // params defines all the parameters of the module.
  Params params = 1
      [ (gogoproto.nullable) = false, (amino.dont_omitempty) = true ];
  SupplyDeltaInfo supplyDeltaInfo = 2;
}
