syntax = "proto3";

package fuelsequencer.bridge;

import "amino/amino.proto";
import "gogoproto/gogo.proto";
import "cosmos_proto/cosmos.proto";
import "fuelsequencer/bridge/params.proto";
import "fuelsequencer/bridge/supply_delta_info.proto";
import "fuelsequencer/bridge/eth_events_transaction.proto";

option go_package = "github.com/fuel-infrastructure/fuel-sequencer/x/bridge/types";

// GenesisState defines the bridge module's genesis state.
message GenesisState {

  // params defines all the parameters of the module.
  Params params = 1
      [ (gogoproto.nullable) = false, (amino.dont_omitempty) = true ];

  // supply_delta_info is the starting point for changes in the bridge token
  // supply that we should report to Ethereum.
  SupplyDeltaInfo supply_delta_info = 2;

  // last_ethereum_nonce is the last nonce used in messages towards Ethereum.
  // In other words, the next nonce to be used is this value +1.
  bytes last_ethereum_nonce = 3 [
    (cosmos_proto.scalar) = "cosmos.Int",
    (gogoproto.customtype) = "cosmossdk.io/math.Int",
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];

  // last_ethereum_block_synced is the last Ethereum block synced.
  // In other words, the next block to be synced is this value +1.
  bytes last_ethereum_block_synced = 4 [
    (cosmos_proto.scalar) = "cosmos.Int",
    (gogoproto.customtype) = "cosmossdk.io/math.Int",
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];

  // eth_events_tx defines the list of eth_events_tx, belonging to the
  // last_ethereum_block_synced +1.
  repeated EthEventsTx eth_events_tx = 5;
}
