syntax = "proto3";
package fuelsequencer.bridge;

import "amino/amino.proto";
import "gogoproto/gogo.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/duration.proto";

option go_package = "github.com/fuel-infrastructure/fuel-sequencer/x/bridge/types";

// Params defines the parameters for the module.
message Params {
  option (amino.name) = "fuelsequencer/x/bridge/Params";
  option (gogoproto.equal) = true;

  // bridge_denom is the assumed denom for the bridged token, used when minting
  // upon deposits, burning when withdrawing, and tracking changes in its
  // supply that will be reported to Ethereum, amongst other scenarios.
  string bridge_denom = 1;

  // ethereum_proxy_contract_address is the contract address we expect to
  // receive deposit and authorize messages from.
  string ethereum_proxy_contract_address = 2;

  // authorize_messages_allowed is a whitelist for authorize messages that we
  // can receive and process.
  repeated string authorize_messages_allowed = 3;

  // supply_delta_period is the frequency in block at which we report supply
  // delta info to Ethereum.
  uint64 supply_delta_period = 4;

  // vesting_start_time is the common vesting starting time for vesting accounts
  // that will be created through deposits from Ethereum.
  google.protobuf.Timestamp vesting_start_time = 5
      [ (gogoproto.nullable) = false, (gogoproto.stdtime) = true ];

  // additional_blocked_addresses is a list of Cosmos SDK-based addresses that
  // are explicitly disallowed from being controlled by authorize messages
  // within the Sequencer system. This can include addresses of module accounts,
  // validator operators, or any other addresses deemed necessary to protect
  // from unauthorized control actions.
  repeated string additional_blocked_addresses = 6;

  // max_eth_block_update_delay is the maximum amount of time that the Sequencer
  // allows validators to not sync up with Ethereum. Once
  // max_eth_block_update_delay is exceeded, the Sequencer's block production
  // will halt until validators sync up with next Ethereum block.
  google.protobuf.Duration max_eth_block_update_delay = 7
      [ (gogoproto.nullable) = false, (gogoproto.stdduration) = true ];

  // injected_event_tx_max_bytes is the maximum amount of block space that an
  // injected event tx can take in terms of bytes. An Authorize event gets
  // skipped and never included in a block if it can't be converted into a tx
  // that can respect this limit. On the other hand, if a Deposit event cannot
  // be converted into a Tx that can respect this limit, the chain halts.
  uint64 injected_event_tx_max_bytes = 8;

  // sequencer_txs_block_space is the maximum amount of bytes allocated for
  // Sequencer-native transactions during heavy bridge usage. Ensures blocks are
  // not solely filled with injected transactions when Sequencer transactions
  // are in the mempool. NOTE: The block space reserved for Sequencer
  // transactions is dynamically adjusted depending on the number of Ethereum
  // events in the block and the number of Sequencer transactions in the
  // mempool.
  uint64 sequencer_txs_block_space = 9;

  // max_authorize_messages is the maximum amount of Cosmos SDK messages that an
  // Authorize transaction can have
  uint64 max_authorize_messages = 10;
}
