syntax = "proto3";
package fuelsequencer.bridge;

import "amino/amino.proto";
import "gogoproto/gogo.proto";

option go_package = "github.com/fuel-infrastructure/fuel-sequencer/x/bridge/types";

// Params defines the parameters for the module.
message Params {
  option (amino.name) = "fuelsequencer/x/bridge/Params";
  option (gogoproto.equal) = true;

  // bridge_denom is the assumed denom for the bridged token, used when minting
  // upon deposits, burning when withdrawing, and tracking changes in its
  // supply, amongst other scenarios.
  string bridge_denom = 1;

  // ethereum_proxy_contract_address is the contract address we expect to
  // receive deposit and authorize messages from.
  string ethereum_proxy_contract_address = 2;

  // authorize_messages_allowed is a whitelist for authorize messages that we
  // can receive and process.
  repeated string authorize_messages_allowed = 3;

  // supply_delta_period is the frequency in block at which we report supply
  // delta info to Ethereum.
  uint64 supply_delta_period = 4;
}