{
 "title": "Sequencer",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Height",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cometbft_consensus_height", "legendFormat": "Block" }
   ]
  },
  {
   "title": "Consensus Txs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "sequencer_store_index_num_injected_txs_total",
     "legendFormat": "Num Injected"
    },
    {
     "expr": "sequencer_store_last_consensus_txs_sequence",
     "legendFormat": "Consensus Sequence"
    }
   ]
  },
  {
   "title": "Num Injected Messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "sequencer_ante_handler_injected_msg",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Num Deposits",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sequencer_tx_msg_deposit_from_ethereum{to_user=\"true\"}",
     "legendFormat": "Num Deposits to User"
    },
    {
     "expr": "sequencer_tx_msg_deposit_from_ethereum{to_user!=\"true\"}",
     "legendFormat": "Num Deposits to Governance"
    }
   ]
  },
  {
   "title": "Num Withdrawals",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 3, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "sequencer_tx_msg_withdraw_to_ethereum",
     "legendFormat": "Num Withdrawals"
    }
   ]
  },
  {
   "title": "Consensus Round Duration",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_round_duration_seconds_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Minted FUEL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "FUEL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sequencer_begin_block_minted_tokens",
     "legendFormat": "Last"
    },
    {
     "expr": "avg_over_time(sequencer_begin_block_minted_tokens[$__interval])",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Supply Delta Reports",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "FUEL" } },
   "targets": [
    {
     "expr": "sequencer_begin_block_supply_current",
     "legendFormat": "Current Supply"
    },
    {
     "expr": "sequencer_begin_block_supply_last",
     "legendFormat": "Last Supply"
    },
    {
     "expr": "sequencer_begin_block_supply_offset",
     "legendFormat": "Supply Offset"
    }
   ]
  },
  {
   "title": "Txs to Ethereum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 7, "y": 7 },
   "targets": [
    {
     "expr": "sequencer_store_ethereum_event_index_offset",
     "legendFormat": "Index Offset"
    },
    {
     "expr": "sequencer_store_last_ethereum_nonce",
     "legendFormat": "Last Nonce"
    }
   ]
  },
  {
   "title": "Time Since Last Eth Update",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sequencer_store_time_since_last_eth_update",
     "legendFormat": "Delay"
    }
   ]
  },
  {
   "title": "Begin Blockers",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "begin_blocker{module=\"bridge\"}",
     "legendFormat": "{{module}} ({{quantile}})"
    },
    {
     "expr": "begin_blocker{module=\"mint\"}",
     "legendFormat": "{{module}} ({{quantile}})"
    }
   ]
  },
  {
   "title": "End Blockers",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "end_blocker{module=\"bridge\"}",
     "legendFormat": "{{module}} ({{quantile}})"
    },
    {
     "expr": "end_blocker{module=\"mint\"}",
     "legendFormat": "{{module}} ({{quantile}})"
    }
   ]
  }
 ]
}