{
 "title": "Sidecar",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Syncing",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sidecar_store_last_synced_block",
     "legendFormat": "Last Synced Block"
    },
    {
     "expr": "sidecar_core_max_syncable_block",
     "legendFormat": "Max Syncable Block"
    },
    { "expr": "sidecar_core_last_header_seen", "legendFormat": "Last Header Seen" }
   ]
  },
  {
   "title": "Ethereum Header Delays",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sidecar_core_header_delay_seconds_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Queries Delays",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sidecar_eth_logs_query_delay_seconds_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "LEBS Queries Delays",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sidecar_seq_lebs_query_delay_seconds_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Pruning",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sidecar_store_blocks_pruned", "legendFormat": "Blocks Pruned" },
    {
     "expr": "sidecar_store_start_query_block",
     "legendFormat": "Oldest Block"
    }
   ]
  },
  {
   "title": "Catching Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sidecar_core_catching_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Block Events Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(sidecar_service_block_events_requests_total)",
     "legendFormat": "Total"
    },
    {
     "expr": "sidecar_service_block_events_requests_total{success=\"true\"}",
     "legendFormat": "Successful"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "sidecar_seq_lebs_query_error_count",
     "legendFormat": "LEBS Query Errors"
    }
   ]
  }
 ]
}