{
 "title": "Sidecar",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Syncing",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sidecar_store_last_synced_block{job=\"$job\"}",
     "legendFormat": "Last Synced Block"
    },
    {
     "expr": "sidecar_core_max_syncable_block{job=\"$job\"}",
     "legendFormat": "Max Syncable Block"
    },
    {
     "expr": "sidecar_core_last_header_seen{job=\"$job\"}",
     "legendFormat": "Last Header Seen"
    }
   ]
  },
  {
   "title": "Ethereum Header Delays",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sidecar_core_header_delay_seconds_bucket{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Queries Delays",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 4, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sidecar_eth_logs_query_delay_seconds_bucket{job=\"$job\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "LEBS Queries Delays",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 4, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sidecar_seq_lebs_query_delay_seconds_bucket{job=\"$job\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - sidecar_core_start_time{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Events Processed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sidecar_store_events_processed{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Events Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(sidecar_service_block_events_requests_total{job=\"$job\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sidecar_service_block_events_requests_total{success=\"true\", job=\"$job\"}",
     "legendFormat": "Successful"
    }
   ]
  },
  {
   "title": "Pruning",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sidecar_store_blocks_pruned{job=\"$job\"}",
     "legendFormat": "Blocks Pruned"
    },
    {
     "expr": "sidecar_store_start_query_block{job=\"$job\"}",
     "legendFormat": "Oldest Block"
    }
   ]
  },
  {
   "title": "Catching Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sidecar_core_catching_up{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 10, "y": 14 },
   "targets": [
    {
     "expr": "sidecar_seq_lebs_query_error_count{job=\"$job\"}",
     "legendFormat": "LEBS Query Errors"
    },
    {
     "expr": "sidecar_eth_logs_query_error_count{job=\"$job\"}",
     "legendFormat": "Logs Query Errors"
    }
   ]
  }
 ]
}